### ISSUE TITLE
SystemStackError when trying to generate documentation

### ISSUE THREAD

**Issue by jazzonmymind** [lsegal/yard#1011]
## Steps to reproduce

This is the minimal reproduction for the issue. I've done my best to remove
all extraneous code and unique environment state on my machine before providing
these steps:

1. `git clone https://github.com/jazzonmymind/zchannel.rb.git`
2. `cd zchannel.rb`
3. `bundle`
4. `bundle exec yardoc`

## Actual Output
```
$ yardoc --debug
[debug]: Parsing ["{lib,app}/**/*.rb", "ext/**/*.{c,cc,cxx,cpp}"] with `ruby` parser
[debug]: Parsing lib/zchannel.rb
[warn]: @param tag has unknown parameter name: (see
    in file `lib/zchannel.rb' near line 12
[debug]: Parsing lib/zchannel/version.rb
[debug]: Parsing lib/zchannel/unix_socket.rb
/usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.5/lib/yard/code_objects/base.rb:387:in `docstring': stack level too deep (SystemStackError)
        from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.5/lib/yard/code_objects/base.rb:532:in `tags'
        from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.5/lib/yard/code_objects/proxy.rb:194:in `method_missing'
        from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.5/lib/yard/tags/ref_tag_list.rb:14:in `tags'
        from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.5/lib/yard/docstring.rb:347:in `block in convert_ref_tags'
        from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.5/lib/yard/docstring.rb:347:in `map'
        from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.5/lib/yard/docstring.rb:347:in `convert_ref_tags'
        from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.5/lib/yard/docstring.rb:276:in `tags'
        from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.5/lib/yard/code_objects/base.rb:532:in `tags'
         ... 10699 levels...
        from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.5/lib/yard/cli/command.rb:13:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.5/bin/yardoc:12:in `<top (required)>'
        from /usr/local/bin/yardoc:23:in `load'
        from /usr/local/bin/yardoc:23:in `<main>'
```

## Expected Output

I expect to see docs being generated.

## Environment details:

* OS: OSX
* Ruby version (`ruby -v`): 2.3.1p112
* YARD version (`yard -v`): yard 0.9.5

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by lsegal** [comment]
Your `(see X)` tags in `ZChannel::UNIXSocket` are referencing each other, specifically `#send` is adding reftags for `#send!` and vice versa.

You can reproduce with this minimal code:

```ruby
class Foo
  # @param (see #b)
  def a; end

  # @param (see #a)
  def b; end
end
```

YARD could add an escape hatch on this recursive resolution so the stack doesn't blow up, but the above code will never resolve the way you want it to-- it would generate a warning for this instead.

**Comment by lsegal** [comment]
Thanks for reporting!

**Comment by jazzonmymind** [comment]
Thanks for the quick fix :)
