### ISSUE TITLE
macro via mixins-chain leads to unexpected behaviour

### ISSUE THREAD

**Issue by thedanielhanke** [lsegal/yard#1019]
* yard 0.8.7.6: a given macro output is added to the docu for each related call. in addition to that, the first argument of that macroed-method becomes a method in the docu too.
* yard 0.9.5: additional parsing warning, `@param` invalid. + same behaviour as above.

## Steps to reproduce

```ruby
module A
  module B
    def self.included(base)
      base.include C
    end

    module C
      def self.included(base)
        base.extend ClassMethods
      end

      module ClassMethods
        # adds an attribute
        #
        # @param [Symbol] name attribute name ***
        # @param [Hash] options attribute options
        #
        # @option options [Boolean] :readonly readonly attribute
        # @option options [Class] :type class of attribute
        # @option options [Object] :default default value
        #
        # @example add an attribute
        #   attribute :foo, type: :fixnum, read_only: true, default: 234
        #
        # @!macro [attach] attribute
        #   @!attribute [rw] $1
        #   @return [$2] the value of the $0
        def attribute(name, **options)
        end
      end
    end
  end
end

class Example
  include A::B
  attribute :foo
end
```
`***`: here 0.9.5 warns: `@param tag has unknown parameter name: name`

The code seems not to make sense in this reduced form, please assume that it actually does ;)

## Actual Output

docu for `A::B::C::ClassMethods` contains:

the correct description of `attribute` (removed unimportant): 
```
Instance Method Details

#attribute(name, **options) ⇒ options

Options Hash (**options):
  :readonly (Boolean) — readonly attribute
  :type (Class) — class of attribute
  :default (Object) — default value
```
but it also includes:
```
Instance Attribute Details

#name ⇒ options

Parameters:
   name (Symbol) — attribute name ***
  options (Hash) — attribute options
```

when i rename the attribute-methods parameter `name` to e.g  `rainbowsausage`, the generated doc features `#rainbowsausage` instead of `#name`

------------

Class: Example documentation is empty.
when i add `@!parse base.extend ....`comments @ each `self.included`, the result contains:

```
Instance Attribute Summary

#foo ⇒ Object
the value of the attribute.

#name ⇒ options included from A::B::C::ClassMethods
add an attribute.
```

removing `--embed-mixins` from yard-config replaces that `#name` info with:

```
Attributes included from A::B::C::ClassMethods
#name
```

## Expected Output

i`d expect to not have that #name-method added to the documentation. 
also, why are the options hash infos missing for that 2nd one? (no answer required just noticed)

## Environment details:

* OS: [Linux 4.7.1-1-ARCH ]
* Ruby version (`ruby -v`): [ruby 2.3.1p112]
* YARD version (`yard -v`): [yard 0.9.5]

If it turns out that my reading skills just suck, sorry. spent quite a while on the guides to figure out what i messed possibly up.

Thanks in advance.
Cheers.

P.S.: while testing around, i ended up with @!attribute and @return, started with @!method and return instead. the problem i am facing is happening in both cases.

**Comment by lsegal** [comment]
Macro attaching isn't supported on instance methods. Unfortunately YARD doesn't support the `ClassMethods` style (anti-)pattern. In order for a macro to be attachable, it must be a class method. This could be changed in the future, but it currently is not expected to work.

Hope that helps to clarify!

**Comment by lsegal** [comment]
FYI, currently the way to work around this would be to fake a class method on the module. I'm removing some of the ClassMethod metaprogramming stuff that gets in the way of the behavior, but you can do:

```ruby
module A
  module B
    # @!parse
    #   class << self
    #   private
    #   # @!macro [attach] attribute
    #   #   @!attribute [rw] $1
    #   #   @return [$2] the value of the $0
    #   def self.attribute(*) end
    #   end

    # adds an attribute
    #
    # @param [Symbol] name attribute name ***
    # @param [Hash] options attribute options
    #
    # @option options [Boolean] :readonly readonly attribute
    # @option options [Class] :type class of attribute
    # @option options [Object] :default default value
    #
    # @example add an attribute
    #   attribute :foo, type: :fixnum, read_only: true, default: 234
    def attribute(name, **options)
    end
  end
end

class Example
  extend A::B
  attribute :foo
end
```

Note the #attribute method stays the same but we introduce a fake `A::B.attribute` method (through the `@!parse` directive) that YARD can use to attach the macro. It's marked private so it doesn't show up in docs. Technically this method shouldn't exist or even work in this way, but this is the current workaround to make things work, since macros cannot be attached to instance methods.

**Comment by lsegal** [comment]
The above commit should allow your implementation to start working as of the next release (coming soon)
