### ISSUE TITLE
Filename _index.html breaks publishing to GitHub pages and makes Jekyll sad

### ISSUE THREAD

**Issue by whopper** [lsegal/yard#1027]
Hello, friends!

Semi-recently, we added support for publishing docs from our YARD-based project onto GitHub Pages (https://pages.github.com/). Unfortunately, `_index.html` is ignored in the push due to Jekyll's rules about hidden files and files containing site content (indicated by names that start with a `_`) : https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/

We can work around this by turning off Jekyll for now, but we'd like to not have to do that. Would it be possible to have _index.html's filename be configurable? 

(Note: If I'm wrong about not being able to change the filename, I'll be totally happy to close this issue :))

## Steps to reproduce

As explained in https://github.com/puppetlabs/puppet-strings#rake-tasks:

Generate docs via yard and save them into a `docs` directory of the repo in question. Then, checkout a `gh-pages` branch and commit the docs. Push this branch to GitHub, and the page will be setup.

## Actual Output

_index.html is ignored in the push, and the file will 404 when you attempt to access it.

## Expected Output

All YARD-generated docs should be accessible on github pages.

## Environment details:

* OS: Any
* Ruby version (`ruby -v`): Any
* YARD version (`yard -v`): 0.9.5
* Relevant software dependency/versions:
  * GitHub pages, Jekyll

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by lsegal** [comment]
You can also workaround this with the `include` directive discussed in the link you posted:

> use [the include directive][global-config] in your _config.yml to specify files that should not be ignored; or

There's no support in YARD to rename the `_index.html` directly, though there are a few ways to do it either programmatically or with a simple post-processing script. The best way, of course, seems like using the `_config.yml` file described above.

**Comment by whopper** [comment]
Thanks @lsegal, I think I'll just do that. Would you like me to leave this issue open as a future possibility, or close it out since there's a decent workaround?

**Comment by lsegal** [comment]
I'd go for closing this, since it's unlikely we would add explicit support for renaming the `_index` file (or any other possible underscore files that could be generated in the future).

**Comment by pboling** [comment]
As documented here on [the GitHub blog](https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/) you can avoid the Jekyll processing, and thus the ignoring of the documents that start with underscores, by:

1. adding a `.nojekyll` file to the root of your repom if Pages is deployed from root, or
2. adding a `.nojekyll` file to the `docs/ directory if Pages is deployed from `docs/`
