### ISSUE TITLE
@yieldreturn not specifying the type

### ISSUE THREAD

**Issue by victor987** [lsegal/yard#1031]
The method summary says it returns a Object even if @yieldreturn is specified with a type.

## Steps to reproduce

```
# @yieldreturn [Integer]
def something
  100
end
```

## Actual Output

```
Instance Method Summary

#something ⇒ Object
```

```
Instance Method Details

#something ⇒ Object

Yield Returns:
(Integer)
```

## Expected Output

```
Instance Method Summary

#something ⇒ Integer
```

```
Instance Method Details

#something ⇒ Integer

Yield Returns:
(Integer)
```

## Environment details:

* OS: Ubuntu 16.04
* Ruby version (`ruby -v`): `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]`
* YARD version (`yard -v`): `yard 0.9.5`

**Comment by lsegal** [comment]
I think you want `@return`, not `@yieldreturn`. The latter is for return values of blocks.

**Comment by victor987** [comment]
You're right, my bad, sorry.
