### ISSUE TITLE
Example of how to use YARD database?

### ISSUE THREAD

**Issue by thomthom** [lsegal/yard#1036]
If I want to use YARD to generate stubs from what its database - how do one go about doing that? 

Templates are the thing for this? Looking at the docs I'm a little confused at how one would approach templates from scratch. What part of the folder structure described here required? http://www.rubydoc.info/gems/yard/file/docs/Templates.md#Creating_a_Template

**Comment by lsegal** [comment]
You can access the registry programmatically to read objects:

http://www.rubydoc.info/gems/yard/YARD/Registry

See the [Architecture Overview](http://www.rubydoc.info/gems/yard/file/docs/Overview.md) to understand how the code objects and registry are related. You do not need to use YARD's templating layer to generate code. You can, but you don't have to.

**Comment by thomthom** [comment]
I think I got something working - using templates. When I looked at the `text` format template code instead of `html` it was a bit easier. Atm I have a simple script in `myplugin/default/fulldoc/text/setup.rb`. That seems to be all I need.

I was thinking the script to generate subs might be nice to wrap up into a gem. I guess using the registry directly vs template is no different in that context? Using the registry might be better - in avoiding the template system all together...

**Comment by lsegal** [comment]
Using the registry directly will also run faster. YARD's templating system is the slowest part because it's build to be hyper-extensible for sub-template modifications, template replacements, custom files, etc.

If your use case is pre-defined and does not involve any user-driven behavior overriding, templates are probably overkill.

Both can be used to generate CLI tools as a gem.

**Comment by thomthom** [comment]
So if I understand this correctly, `Registry.load` let me initiate the same parsing `yardoc` do? But I need to apply filtering myself - if I want to filter out any tags?

**Comment by lsegal** [comment]
> So if I understand this correctly, Registry.load let me initiate the same parsing yardoc do?

`Registry.load` does not parse code, it is *just* the database. See [Yardoc#run](https://github.com/lsegal/yard/blob/master/lib/yard/cli/yardoc.rb#L238-L277) for what `yardoc` does. The `load` call will load from disk, assuming the database exists. If you haven't yet parsed, you should use `YARD.parse`, or `yard -n` / `YARD::CLI::Yardoc.run('-n')`.

> But I need to apply filtering myself - if I want to filter out any tags?

Yes. If you're relying heavily on filters, that is definitely a benefit of using the template layer.

**Comment by thomthom** [comment]
Thank you very much for all the feedback. I got something to play around with. Will see what I end up with.

Really appreciate it.

**Comment by thomthom** [comment]
It appear that `Registry.load` will take care of parsing for you.

```
require 'yard'

project_path = File.expand_path(File.join(__dir__, '..', 'SUbD'))
pattern = File.join(project_path, 'Ruby', '**/*.rb')
files = Dir.glob(pattern).to_a

puts "#{files.size} files"

YARD::Registry.load(files)

puts YARD::Registry.all.count
```

That yielded:

```
178 files
1294
```

**Comment by lsegal** [comment]
Yes, you can use `Registry.load` to parse, but you probably don't want to do this (it requires manually specifying the files which avoids using your `.yardopts`).

**Comment by thomthom** [comment]
Gotcha. I'll keep playing around. I might end up using template in order to ensure parsing match `yardoc`. But I'm really enjoying tinkering with `Registry` directly here now. So much faster. I get ideas for more analysis tools. :D

**Comment by lsegal** [comment]
Great! Can this be marked as closed?

**Comment by thomthom** [comment]
Yes, I'm rolling! :D
