### ISSUE TITLE
Can't add "--readme" to options in raketask

### ISSUE THREAD

**Issue by PascalTurbo** [lsegal/yard#1043]
I've just created a rake task like described in the documentation:

```ruby
YARD::Rake::YardocTask.new do |t|
  t.files   = ['lib/**/*.rb', 'LICENSE']
  t.options = ['--readme README.md']
  t.stats_options = ['--list-undoc']
end
```

But when executing `rake yard` it will fail with

   [warn]: Unrecognized/invalid option: --readme README.md

Executing `yardoc --readme README.md` will work without a warning.

**Comment by lsegal** [comment]
The `.options` field is comma separated by word. You are passing `"--readme README.md"` as a single flag, the way you would do if you added quotations in your shell command:

```sh
yardoc '--readme README.md'
```

You want:

```ruby
t.options = ['--readme', 'README.md']
```

Hope that helps!
