### ISSUE TITLE
Please make the output reproducible

### ISSUE THREAD

**Issue by lamby** [lsegal/yard#1049]
via https://github.com/lsegal/yard/pull/1048#issuecomment-270011932

Whilst working on the Reproducible Builds effort [0], I noticed
that yardoc generates output that is not reproducible due to the
use of a fallback glob that relies on (non-deterministic)
filesystem ordering.

[0] https://reproducible-builds.org/

**Comment by lamby** [comment]
@lsegal Would you be able to provide a patch? Would be very willing to test.

**Comment by lsegal** [comment]
This is on the backlog. There's no ETA for a fix, though.
