### ISSUE TITLE
YARD 0.9.6 and up crashing while parsing certain strings with '/' characters

### ISSUE THREAD

**Issue by whopper** [lsegal/yard#1054]
Hello! As of 0.9.6, YARD has been crashing while parsing the following string...

```
commands foo: /usr/bin/foo\n
```

... with the following error:
```
[warn]: Syntax error in `(stdin)`:(51,20): unknown regexp option - b
[warn]: ParserSyntaxError: syntax error in `(stdin)`:(51,20): unknown regexp option - b
[warn]: Stack trace:
	/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/yard-0.9.7/lib/yard/parser/ruby/ruby_parser.rb:583:in `on_parse_error'
	/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/yard-0.9.7/lib/yard/parser/ruby/ruby_parser.rb:56:in `parse'
	/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/yard-0.9.7/lib/yard/parser/ruby/ruby_parser.rb:56:in `parse'
	/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/yard-0.9.7/lib/yard/parser/ruby/ruby_parser.rb:17:in `parse'
	/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/yard-0.9.7/lib/yard/parser/source_parser.rb:442:in `parse'
	/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/yard-0.9.7/lib/yard/parser/source_parser.rb:124:in `parse_string'
```

It seems that YARD sees the `/usr/` and thinks it's a regex, and so barfs on the following `b` thinking it's an invalid regex option.

After filing this issue, I realized that if the path is put in quotes everything works correctly. There's still a change of behavior from 0.9.5 here, so I'll leave this open.

## Steps to reproduce

I tracked this down with pry by running the following in a simple spec test:

```
YARD::Parser::SourceParser.parse_string(<<-SOURCE, :ruby)
Puppet::Type.type(:database).provide :linux do
  desc 'An example provider on Linux.'
  confine kernel: 'Linux'
  confine osfamily: 'RedHat'
  defaultfor :kernel => 'Linux'                                                                        
  defaultfor :osfamily => 'RedHat', :operatingsystemmajrelease => '7'
  has_feature :implements_some_feature                                                                 
  has_feature :some_other_feature
  commands foo: /usr/bin/foo
end
SOURCE
```
After looping over `parse_string` in `lib/yard/parser/source_parser.rb`, we hit the exception right after we're passed the `usr` string, which is tokenized with `AstNode.new`:

```
    255: def visit_ns_token(token, data, ast_token = false)
    256:   add_token(token, data)
    257:   ch = charno
    258:   @last_ns_token = [token, data]
    259:   @charno += data.length
    260:   @ns_charno = charno
    261:   @newline = [:semicolon, :comment, :kw, :op, :lparen, :lbrace].include?(token)
    262:   require 'pry' ; binding.pry if data == "usr"
    263:   if ast_token
 => 264:     AstNode.new(token, [data], :line => lineno..lineno, :char => ch..charno - 1, :token => true)
    265:   end
    266: end
```

## Actual Output

YARD blows up with an exception about an invalid regex option (stack trace above):

```
[warn]: Syntax error in `(stdin)`:(51,20): unknown regexp option - b
[warn]: ParserSyntaxError: syntax error in `(stdin)`:(51,20): unknown regexp option - b
```

If I change the string to include `/usr/zin/foo`, I get the same error but the `unknown regexp option - z`, confirming that this is some sort of weird mixup with the '/'.

## Expected Output

Prior to 0.9.6, this failure didn't happen. I assume it's a bug.

## Environment details:

* OS: Any
* Ruby version (`ruby -v`): Failing with 1.9.3 through 2.3.1
* YARD version (`yard -v`): 0.9.6 and 0.9.7

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by whopper** [comment]
Ah, if that path is put in quotes then everything works the same. Perhaps this is *not* a bug then, but I'll leave it open just in case, as the behavior did change from 0.9.5.

**Comment by lsegal** [comment]
I mean, it's not valid Ruby code, so the error seems like expected behavior to me. Does puppet actually allow that?

**Comment by whopper** [comment]
Ha, yeah, apparently. Although there's really no reason to do anything other than quote the thing on our end, so nevermind on this - closing! :)
