### ISSUE TITLE
Proper way to document class parameters

### ISSUE THREAD

**Issue by tshunter** [lsegal/yard#1060]
Is there a proper way to document the following in YARD:

```
# Custom delayed_job to assign project_id
#
# @param [Integer] project_id The project_id to be assigned
#
class AssignProjectIdJob < Struct.new(:project_id)
...
end
```

When running "yard doc" I receive the following:

"[warn]: @param tag has unknown parameter name: project_id"

**Comment by r-obert** [comment]
last time i wanted to do that i used the `@attr_reader` tag but that's deprecated in favour of the `@!attribute` tag, see [here](http://www.rubydoc.info/gems/yard/file/docs/Tags.md#attribute).

**Comment by lsegal** [comment]
`@!attribute` is indeed the correct way to do this.

Thanks for asking! Marking as closed.

**Comment by tshunter** [comment]
Got it, thank you both for the clarification :)
