### ISSUE TITLE
YARD::Handlers::Ruby::DSLHandler: Undocumentable method, missing name

### ISSUE THREAD

**Issue by kyrylo** [lsegal/yard#1061]
Apologies, if this is not a bug, but my misunderstanding.

1. Clone https://github.com/airbrake/airbrake-ruby.git
1. Checkout [`cb1d8b636c423bd`](https://github.com/airbrake/airbrake/blob/cb1d8b636c423bd5b2cb50e9e9abf920d80dced1/lib/airbrake/rack/notice_builder.rb) to make sure the file and line is present
2. Run `yardoc`
3. Evidence the following in the output:

```
<snip>
[warn]: in YARD::Handlers::Ruby::DSLHandler: Undocumentable method, missing name
[warn]:         in file 'lib/airbrake/rack/notice_builder.rb':52:

        52: add_builder do |notice, request|

<snip>
```

`add_builder` there is not a method definition, it also doesn't dynamically create methods, so I am not sure how I should resolve that warning. Thank you for your assistance.

* Ruby version (`ruby -v`): `ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]`
* YARD version (`yard -v`): `yard 0.9.8`

**Comment by lsegal** [comment]
@kyrylo you're using the RDoc "##" comment prefix, which is a legacy supported RDoc feature that forces the statement below the comment block to be treated explicitly as a method declaration (if it can conceivably be one). In other words, "##" isn't an aesthetic nicety, it has semantic meaning in both YARD and RDoc, and 99% of the time it's not what you want.

**Comment by lsegal** [comment]
Marking as closed.

**Comment by kyrylo** [comment]
Cool, thanks for the answer! I had never realised `##` meant something special, so I use it simply because I like how it looks visually.
