### ISSUE TITLE
Browser Back is not working

### ISSUE THREAD

**Issue by thomthom** [lsegal/yard#1071]
If you click on a method which takes you to the anchor for that method then clicking Back in the browser doesn't take up back up where you were. (Tested in Chrome, Windows 10)

## Steps to reproduce

This can be observed in the latest version (0.9.8). For instance, on this page for YARD itself; http://www.rubydoc.info/gems/yard/File (Generated by 0.9.8)

For instance, click on the `cleanpath` link under the "Manipulating Paths" section - then try the browser back button.

## Actual Output

When clicking back after clicking an anchor nothing happens. If I keep clicking it will navigate back to whatever URL I was coming from, but anchor history is broken.

## Expected Output

Expected behaviour would be for the browser history buttons to act upon the anchor history - like normally happens.

## Environment details:

* OS: Windows 10
* YARD version (`yard -v`): 0.9.8
* Relevant software dependency/versions:
  * Chrome 56.0.2924.87

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by noahgibbs** [comment]
I observe the same thing on Mac OS X v. 10.12.6 and Chrome 63.0.3239.84 64-bit official build.
