### ISSUE TITLE
attr_accessor Reference Tags Not Copying Across Classes

### ISSUE THREAD

**Issue by allcentury** [lsegal/yard#1073]
I am trying to link an `attr_accessor`'s documentation across two separate classes. The first class has the correct documentation.

## Steps to reproduce

In a file `lib/memory.rb`:

```ruby
class Memory
  # The main runner, must respond to #call
  # @return [Proc/Lambda] the runner
  attr_accessor :circuit
end
```

In a file `lib/redis.rb`

```ruby
class Redis
  # (see Memory#circuit)
  attr_accessor :circuit
end
```

Run `yard` from the shell.

## Actual Output

Here is the output for the Redis class:

<img width="1440" alt="screen shot 2017-02-17 at 7 59 44 am" src="https://cloud.githubusercontent.com/assets/5561166/23066163/25fa9396-f4e7-11e6-879c-08a9f88fa89b.png">

## Expected Output

I expected the docstring and return tag to be copied over. 

## Environment details:

* OS: OSX
* Ruby version 2.4.0
* YARD version 0.9.8

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

I just want to point out that `@see` and `@return (see Memory#circuit)` do in fact work. However I want the description as well.  The docs in reference tags say 

> [it] takes the docstring and all tags (param and return)

**Comment by lsegal** [comment]
Looking at `yard --debug` in this case, `lib/redis.rb` is being parsed before `lib/memory.rb`, which means that the see tag will fail to reference contents of the object. Unfortunately docstring see tags are file order dependent, because they are processed lexically.

To fix this you can use explicit file ordering in your .yardopts file:

```
lib/memory.rb
lib/**/*.rb
```

Or on the command line: `yard doc lib/memory.rb lib/**/*.rb'

**Comment by lsegal** [comment]
FWIW, a note for this in the docs may be useful here.

**Comment by lsegal** [comment]
Closing out some old issues. Given the significant age of this, it would be best to re-open with new context if it's still relevant.
