### ISSUE TITLE
Yard does not document prepended Modules in Classes

### ISSUE THREAD

**Issue by kmoschcau** [lsegal/yard#1074]
Yard does not generate any documentation for prepended Modules in a Class.

## Steps to reproduce

Write the following code and generate the documentation from it.

```ruby
module Bar
  def meth
    super + 'bar'
  end
end

class Foo
  prepend Bar

  def meth
    'foo'
  end
end

class Moo
  include Bar

  def meth
    'foo'
  end
end
```

## Actual Output

![Actual Output](http://i.imgur.com/CBGmqn8.jpg)

## Expected Output

I expected it to have at least a somewhat similar output to include.
![Expected Output](http://imgur.com/J57tuMl.jpg)

## Environment details:

* OS: `> uname -srmov`
  `Linux 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 GNU/Linux`
* Ruby version: `> ruby -v`
  `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]`
* YARD version: `> yard -v`
  `yard 0.9.8`

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by lsegal** [comment]
Closing out some old issues. Given the significant age of this, it would be best to re-open with new context if it's still relevant.
