### ISSUE TITLE
Type explainer can't parse methods ending in '?' and '!'

### ISSUE THREAD

**Issue by backus** [lsegal/yard#1077]
It would be nice to be able to document methods as `@param foo [#all?]` but the type explainer currently fails on methods like this. I realize [it is really hard](https://github.com/whitequark/parser/issues/213#issuecomment-154711061) to parse ruby methods so I'm definitely not asking for something comprehensive, but adding `?` and `!` would be nice.

## Steps to reproduce

```
$ irb
>> require 'yard'
>> YARD::Tags::TypesExplainer::Parser.parse('#all?')
SyntaxError: invalid character at ?
from /Users/johnbackus/.gem/ruby/2.3.1/gems/yard-0.9.8/lib/yard/tags/types_explainer.rb:154:in `block in parse'
>> YARD::Tags::TypesExplainer::Parser.parse('#gsub!')
SyntaxError: invalid character at !
from /Users/johnbackus/.gem/ruby/2.3.1/gems/yard-0.9.8/lib/yard/tags/types_explainer.rb:154:in `block in parse'
```

I would be happy to do a PR fixing this

**Comment by backus** [comment]
For context, I opened this issue because I am currently using the type explainer for [backus/yardcheck](https://github.com/backus/yardcheck). I realize it is private API and I intend on replacing it with my own parser, but I figured this would still be something YARD might want to fix

**Comment by lsegal** [comment]
You can actually probably use `CodeObjects::METHODNAMEMATCH` to parse most method names.

**Comment by backus** [comment]
Cool. I can open a PR in the future to support that. Any interest in making the type explainer API public at some point?

**Comment by lsegal** [comment]
I don't see where it's marked private. You should be able to use it already.

**Comment by backus** [comment]
Oh I assumed that it was private I guess because all of the namespaces within it are marked `@private` but that makes sense. Cool. I'm already using it in Yardcheck so glad to know it is public API

**Comment by backus** [comment]
Ah ok I see what I was concerned about before. `TypeExplainer.explain!` is public but I need to actually invoke the parser and get back objects. `explain!` just gives me a string

**Comment by lsegal** [comment]
Root issue is fixed. As far as making it public I'd be more open to it if it were documented. If you wanted to contribute docs that would help.
