### ISSUE TITLE
undefined method `namespace' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by intale** [lsegal/yard#1078]
How to reproduce an issue:
 - create an empty .yardoc folder
 - specify path to it with `--use-cache` option.

Example:
`yardoc --protected --private --use-cache .yardoc --output-dir tmp/cache/docs --no-yardopts '{app}/**/*.rb'`

Results in:
```
yard-0.9.8/lib/yard/serializers/file_system_serializer.rb:59:in `serialized_path': undefined method `namespace' for nil:NilClass (NoMethodError)
```
Because `YARD::Registry.root` becomes `nil`.
OS: Ubuntu 16.04
Ruby: 2.3.3
Rails: 5.0.2
Gem version: 0.9.8

**Comment by lsegal** [comment]
@intale thanks for reporting this. We can probably implement some safeguard to recreate the database. Can you explain how you got into this state, though? It seems like the database was corrupted somehow (files in the directory were removed).

**Comment by intale** [comment]
Well, I just wanted the static docs be present in production rails app. So I added a `.yardoc` folder to the list of `linked_dirs` in my capistrano script(+ docs generation command, of course) - not doing this and not using `--use-cache` option results into long time docs generation. Another words, yard db is generated for each release from scratch, which is unsuitable. But when testing deploy locally, I ran into this issue.

> We can probably implement some safeguard to recreate the database
From my point of view, the code shouldn't assume that db is present by `.yardoc` folder existence.

**Comment by lsegal** [comment]
> From my point of view, the code shouldn't assume that db is present by .yardoc folder existence.

@intale it does though-- the database is the entire directory node. There are historical reasons for this (namely YARD also supports the .yardoc being a file node), so the simplified "db exists?" check is "node exists?".

That said, recreating the db if the cache location is corrupt or cannot be unmarshaled would still probably resolve this, and probably other similar cases as well.

**Comment by lsegal** [comment]
Looks like we just weren't properly initializing database state when loading from disk. This can now be separated from any assumptions we make about the database node on disk-- i.e., you're free to pick an empty directory (you were before too, we just had this bug).
