### ISSUE TITLE
Missing @return tags in Ruby core documentation

### ISSUE THREAD

**Issue by castwide** [lsegal/yard#1081]
When parsing documentation for the Ruby core, @return tags are not getting added to docstrings. I confirmed that MethodObjects for Array#join and String#split have @return tags in the docstring text, but they're not in the MethodObject#tags array.

## Steps to reproduce

1. Download Ruby source (bug is identical in 2.0.0, 2.3.0, and 2.4.0)
2. Generate yardoc in the source directory with `yardoc *.c`
3. Do the following in IRB:
    require 'yard'
    yard = YARD::Registry.load!('.yardoc')
    obj = yard.at('Array#join')
    obj.tag(:return)

## Actual Output

    obj.tag(:return) #=> nil

## Expected Output

    obj.tag(:return) #=> #<YARD::Tags::Tag:[...]>

## Workaround

I currently have a workaround for this issue that parses a new docstring with leading whitespace removed from the @return tag. Example:

    yard = YARD::Registry.load!('.yardoc')
    obj = yard.at('Array#join')
    stripped = ''
    obj.docstring.all.lines.each { |line|
      stripped += "#{line.strip}\n"
    }
    new_doc = YARD::Docstring.new(stripped, obj)
    obj.docstring = new_doc
    obj.tag(:return).types #=> ["String"]

## Environment details:

* OS: CentOS 7 and Windows 10
* Ruby version: 2.3.0 (CentOS) and 2.3.3 (Windows)
* YARD version: 0.9.8

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by lsegal** [comment]
Ruby core doesn't use tag based documentation. We attempt to parse return types when parsing C code but it's not 100% reliable. 

Can you show where you found `@return` tags in source?

**Comment by castwide** [comment]
The yardoc I'm generating from core uses the C source (yardoc *.c). The generated docstrings contain @return tags, but they're not available from the tag method, i.e., obj.tag(:return) returns nil.

On further inspection, the relevant code might be lines 80-81 in lib/yard/parser/c/comment_parser.rb:

    overloads << "  @yield [#{blkparams}]" if blk
    overloads << "  @return [#{types.join(', ')}]" unless types.empty?
    
    #             ^ strings begin with 2 spaces

Is it possible those strings should have one space instead of two before the tag?

**Comment by lsegal** [comment]
Any amount of spaces are sufficient for indentation, but two spaces is indeed the recommended number for indenting.

If you're looking for overload tags, you need to look inside of `obj.tag(:overload).tags`, since that's where those kinds of tags are stored.

**Comment by castwide** [comment]
Confirmed the tag is available via `obj.tag(:overload).tag(:return)`. Thanks for your help.
