### ISSUE TITLE
`@param [Hash] opts` or `@param opts [Hash]` ?

### ISSUE THREAD

**Issue by ozgun** [lsegal/yard#1084]
Which one is correct:

```
@param [Hash] opts the options to create a message with.
@option opts [String] :subject The subject
```

or

```
@param opts [Hash] the options to create a message with.
@option opts [String] :subject The subject
```

According to http://www.rubydoc.info/gems/yard/file/docs/Tags.md#option page, the first one is correct, but according to http://www.rubydoc.info/gems/yard/file/docs/Tags.md#param page, the second one seems correct. I wonder if the useage of `@param` changes when it is used with `@option` tag.

Thanks.

**Comment by kmoschcau** [comment]
Both versions generally work with the `@param` tag. I usually prefer the `@param [Types] name` version, since that is the one that still works when you insert a line break between the types and the name or inside the types.

**Comment by ozgun** [comment]
@kmoschcau thanks!
