### ISSUE TITLE
Unhandled exception in YARD::Handlers::C::MixinHandler

### ISSUE THREAD

**Issue by davidalejandroaguilar** [lsegal/yard#1094]
Got the same error as becker1701 [here](https://github.com/pry/pry/issues/1598):

The `#show-method` method is throwing an unhandled exception in YARD::Handlers::C::MixinHandler. 

Basically doing the following in PRY:

```
require 'pg'
db = PG.connect(dbname: 'database')
result = db.exec('SELECT * FROM films;')
show-method result.values
# Error
```

Ruby 2.3.1
Pry 0.10.4
PG: 0.20.0 x86-mingw32
Yard: 0.9.9

[Here's a gist of the full stack.](https://gist.github.com/davidalejandroaguilar/0017fb046510e4077dbbe76b8662bdf4)

**Comment by lsegal** [comment]
This error looks like issue with the `pg` gem, not YARD. Occasionally, YARD requires source files to be properly ordered to parse properly, especially when it comes to C source. From the looks of the load order errors, it looks like the author of pg may need to define a `.yardopts` file with the source files ordered in a way that YARD can correctly parse.
