### ISSUE TITLE
Doesn't respect :nodoc: from RDoc

### ISSUE THREAD

**Issue by croaky** [lsegal/yard#11]
Is the answer to just make the methods private? Or is this something YARD can handle?

Example:

http://rdoc.info/rdoc/thoughtbot/shoulda/blob/7d6aa5b6ecceef0bef3399bc328275a3700e06ac/Shoulda/ActiveRecord/Matchers/AllowMassAssignmentOfMatcher.html#protected_attributes-instance_method

**Comment by revolter** [comment]
What if you want to ignore deprecated methods?

**Comment by lsegal** [comment]
@revolter can you explain what you mean by this?

**Comment by revolter** [comment]
I have one deprecated method (because it has a typo in its name) and the new one, and it generates the documentation for both. Is it ok this way, or would it be better not to generate the deprecated method at all?

**Comment by lsegal** [comment]
@revolter you should continue to generate docs for the deprecated method for as long as it's deprecated. Documentation is actually _very_ important for deprecated methods, because that is how you communicate that they have been deprecated, why, and what alternative is available. If you simply remove the method, users browsing your docs will not know that they shouldn't be using said method anymore.

**Comment by spaghetticode** [comment]
This is an old conversation, on a closed issue, but maybe I'm going to get some feedback anyway. 

So, I was considering not documenting a method in my module, and after reading that yard is compatible with rdoc I expected `:nodoc:` to work. No. 

I read the discussion so far, but I'd like to propose another scenario where it makes sense (at least to me) to hide a method from documentation: ruby hooks

```ruby
  module Mod
    def self.included(base)
      base.send :include, AnotherMod
      base.send :prepend, MoreMod
    end
```

Given this is basically all internals, I think it may be a good candidate for hiding. `@private` is not an option for me, as I am documenting also some private methods. 

Is there any way to achieve my goal?

Thanks.
