### ISSUE TITLE
False undocumented methods, mangled parameters.

### ISSUE THREAD

**Issue by woodruffw** [lsegal/yard#1101]
I'm having problems with my yardoc generated documentation in a particular file, which you can find here:

https://github.com/woodruffw/kbsecret/blob/945ee8ebc8d7d44580aaf3585bb744ce1037293a/lib/kbsecret/record/abstract.rb

## Steps to reproduce

```bash
$ git clone https://github.com/woodruffw/kbsecret && cd kbsecret
$ yard
```

You can also see this bug in the [rubydoc.info generated page](http://www.rubydoc.info/gems/kbsecret/0.5.6/KBSecret/Record/Abstract).

## Actual Output

The `load!`, `initialize`, and `initialize_from_hash` methods have their parameter lists mangled:

![](https://sr.ht/SXHy.png)

Furthermore, the actual documentation detail is missing for each (except for `@note` and `@api private` tags):

![](https://sr.ht/75Ej.png)
![](https://sr.ht/EakT.png)
![](https://sr.ht/ImHI.png)

`yard stats --list-undoc` also incorrectly shows these methods as undocumented:

```
Files:          13
Modules:         2 (    0 undocumented)
Classes:        12 (    0 undocumented)
Constants:       4 (    0 undocumented)
Attributes:     10 (    0 undocumented)
Methods:        58 (    4 undocumented)
 95.35% documented

Undocumented Objects:

(in file: lib/kbsecret/record/abstract.rb)
KBSecret::Record::Abstract.load!
KBSecret::Record::Abstract#initialize_from_hash
KBSecret::Record::Abstract#data_fields
KBSecret::Record::Abstract#sensitive?
```

## Expected Output

Expected: correctly presented parameter names, full documentation detail under each method, and each method recognized as documented.

## Environment details:

* OS: Linux (Ubuntu LTS 16.04)
* Ruby version (`ruby -v`): `ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux-gnu]`
* YARD version (`yard -v`): `yard 0.9.9`

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by woodruffw** [comment]
I was able to "fix" this by removing all of the in-method comments in the [`type`](https://github.com/woodruffw/kbsecret/blob/945ee8ebc8d7d44580aaf3585bb744ce1037293a/lib/kbsecret/record/abstract.rb#L78) method, which makes me think that this is a manifestation of #1023.

Removing just the first one didn't work; each aligned comment had to be removed.

**Comment by woodruffw** [comment]
Thank you!

**Comment by lsegal** [comment]
No problem, thanks for reporting this!
