### ISSUE TITLE
Warning: @param tag has unknown parameter name (inside @!method)

### ISSUE THREAD

**Issue by woodruffw** [lsegal/yard#1103]
I'm writing documentation for some dynamically generated methods, and I'm running into these odd warnings and signature generation (for [this file](https://github.com/woodruffw/kbsecret/blob/6a3024d6ffdf33308102658815c66c60f132a5b9/lib/kbsecret/config.rb#L72)):

```
[warn]: @param tag has unknown parameter name: label 
    in file `lib/kbsecret/config.rb' near line 111
[warn]: @param tag has unknown parameter name: label 
    in file `lib/kbsecret/config.rb' near line 111
[warn]: @param tag has unknown parameter name: label 
    in file `lib/kbsecret/config.rb' near line 111
[warn]: @param tag has unknown parameter name: hsh 
    in file `lib/kbsecret/config.rb' near line 111
[warn]: @param tag has unknown parameter name: label 
    in file `lib/kbsecret/config.rb' near line 111
[warn]: @param tag has unknown parameter name: gen 
    in file `lib/kbsecret/config.rb' near line 111
[warn]: @param tag has unknown parameter name: gen 
    in file `lib/kbsecret/config.rb' near line 111
[warn]: @param tag has unknown parameter name: label 
    in file `lib/kbsecret/config.rb' near line 111
[warn]: @param tag has unknown parameter name: hsh 
    in file `lib/kbsecret/config.rb' near line 111
[warn]: @param tag has unknown parameter name: label 
    in file `lib/kbsecret/config.rb' near line 111
```

The generated documentation includes the parameters in the detail, but not in the method signatures themselves.

I think this is related to #842. Please let me know if there's anything I can do to help fix it!

## Steps to reproduce

```bash
$ git clone https://github.com/woodruffw/kbsecret && cd kbsecret
$ yard
```

## Actual Output

Parameters are correctly documented in the method detail, but are not part of the
method signature itself:

![](https://sr.ht/Kzy6.png)

## Expected Output

Parameters should be included in the method signature, e.g. `#session(label) => Hash`,
and no warnings should be raised.

## Environment details:

* OS: Linux (Ubuntu LTS 16.04)
* Ruby version (`ruby -v`): `ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux-gnu]`
* YARD version (`yard -v`): `yard 0.9.9`

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by lsegal** [comment]
These errors are expected. Adding `@param` tags does not add them to the method signature. You must provide the exact method signature in `!@method foo(...)` in the equivalent syntax as you would to a `def foo(...)`.

**Comment by woodruffw** [comment]
Thanks for the clarification! Closing since it's not a bug :smile:
