### ISSUE TITLE
How does `yard server --multi-library` work / where are the docs?

### ISSUE THREAD

**Issue by nrser** [lsegal/yard#1105]
I've got what I would guess is a reasonably common setup - a main Rails project with some gems as submodules in `vendor`.

I'm unable to find documentation on the `--multi-library` option to `yard server` beyond the `yard server --help` output, which just says "Serves documentation for multiple libraries"... which didn't help me very much.

I've found stuff online about `--multi-library` that references a `.yardoc` file, but I couldn't find any documentation on that, just on `.yardopts`... I think I've determined that it's the directory that Yard puts all it's stuff in and it doesn't need to exist before you start the server? Some documentation of this somewhere easy to find would probably help a lot of people.

## Steps to Reproduce

From the research I've done this seemed reasonable to start the server:

```bash
bundle exec \
  yard server \
    --reload \
    --multi-library \
      www-rails ./.yardoc \
      NRSER ./vendor/nrser-ruby/.yardoc
```

## Actual Output

The server starts fine, but while the `www-rails` library seems correct (and does *not* include the `NRSER` library), but the `NRSER` library includes all the stuff from the main Rails project too.

## Expected Output

I would expect there to be some documentation on how to use the `--multi-library` option?

I don't expect the NRSER library to include everything from the main Rails project.

## Environment details:

* OS: Docker Version 17.06.0-ce-mac19 (18663) Moby (Linux 4.9.36-moby SMP x86_64) on OSX Sierra 10.12.5
* Ruby version (`ruby -v`): ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]
* YARD version (`yard -v`): yard 0.9.9

Thanks in advance, Neil.

**Comment by lsegal** [comment]
Closing out this old issue.
