### ISSUE TITLE
[warn]: @param tag has unknown parameter name: move on C method

### ISSUE THREAD

**Issue by pioz** [lsegal/yard#1107]
I have the follow C method in a Ruby C extension
```
/*
 * call-seq: initialize(move) -> IllegalMoveError
 *
 * Create a new instance of {IllegalMoveError}.
 * @param [String] move the illegal move.
 */
VALUE
illegal_move_error_initialize (VALUE class, VALUE move) {
  ...
}
```
When I run the command `rake yard` I get: 
```
pyroblast:chess pioz$ rake yard
[warn]: @param tag has unknown parameter name: move 
    in file `ext/chess.c' near line 38

```
The doc is correct, but how can I avoid this warning? I've try to use `@!method` but nothing change.

## Environment details:

* OS: OSX 10.12.6
* Ruby version (`ruby -v`): ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
* YARD version (`yard -v`): yard 0.9.9

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by lsegal** [comment]
Unfortunately you can't mix RDoc `call-seq` signature syntaxes alongside YARD tags. The solution here is to use full YARD syntax with `@overload`:

```c
/*
 * @overload initialize(move)
 *   Create a new instance.
 *   @param [String] move the illegal move.
 */
VALUE
illegal_move_error_initialize (VALUE class, VALUE move) {
}
```

**Comment by pioz** [comment]
Ok, it seems more a workaround than a solution, but it works!
Thank you very much for your help!
