### ISSUE TITLE
Documenting Class Types in Return Tags

### ISSUE THREAD

**Issue by castwide** [lsegal/yard#1109]
I need to document methods that return a class instead of an instance of a class. Example:

    def string_class
      String
    end

Is there a preferred way to declare a return tag that indicates the String class itself instead of a String object? I could use `@return [Class]` but it would help if I could be more specific. Here are a couple of possibilities that occurred to me:

    # @return [Class<String>]
    # @return [String#class]

In my particular use case, the method returns an anonymous subclass of the specified class.

**Comment by lsegal** [comment]
Using `Class<String>` is best if you know the class. If you don't, `Class` works with documentation stating what you described.

**Comment by castwide** [comment]
Great, that's all I needed to know. Thanks for the quick reply.
