### ISSUE TITLE
How to nest classes inside namespaces in the left without defining the parent Module?

### ISSUE THREAD

**Issue by vizcay** [lsegal/yard#1112]
Let's say I have a lot of classes like Service::DoSomething and Service::DoSomething etc. in a big Rails application. If I don't nest the class into the Service module all appear at the top namespace of the YARD class list (I understand this is by design). But I want the nesting without needing to do:

```ruby
module Service
  class DoSomething
  end
end
```

There is some way to force / configure this? Thanks

**Comment by lsegal** [comment]
I'm not entirely sure what the question is, here. YARD's goal is to list your documentation as it exists in code. If you *do* want the toplevel `Service` module nesting, the best way to do it is to have a real Service module that exists in code.

The other way to do this is to use plugins/templates to customize the look of your generated HTML. A few projects do this for navigation, but not to emulate module nesting.
