### ISSUE TITLE
Yard ignores docs inside `concerning` blocks

### ISSUE THREAD

**Issue by angelim** [lsegal/yard#1113]
When using `concerning` blocks yard **does not** create the corresponding documentation

## Steps to reproduce

```
class Test
  concerning :Actions do
    # @!attribute name
    #   @return [String] name of the action
  end
end
```

## Actual Output
attribute `name` is not documented

## Expected Output

documentation for the attribute `name`

**Comment by r-obert** [comment]
`!@parse` tag may be helpful: http://www.rubydoc.info/gems/yard/file/docs/Tags.md#parse
i don't  know of another way for Yard to know that `concerning` is creating a module 
behind the scenes. 

```ruby
module Test
  # @!parse Test::Actions
  concerning :Actions do
  end
end
```

**Comment by r-obert** [comment]
Sorry, my solution doesn't work. It adds `Test::Actions` but methods within the concerning block are not documented as so. lsegal will know the best answer. if there's no better answer, i think extending `!@scope` or adding a similar directive that can take a class/module may work well here:

```ruby
module Test
    # @!parse module Test::Actions; end
  concerning :Actions do
    # @!scope Test::Actions
    # @return [String] returns ..
    def name
    end
  end
end
```

**Comment by r-obert** [comment]
Oh wow, looks more complicated than that: http://api.rubyonrails.org/classes/Module/Concerning.html#method-i-concerning

Test::Actions will be created, but it's also auto-included into Test. So Yard has to know about the include as well.

**Comment by angelim** [comment]
Thanks for the hard work @r-obert . The ideal output would be to get docs from `Actions` embedded in `Test`. I can't even manage to get `Actions` output in its own doc file after using `parse module...`. I'm not sure this should be a plugin because it's a language feature. IMHO plugins are supposed to deal with external libraries.

**Comment by r-obert** [comment]
'concerning' is added by ActiveSupport, a Rails library, that's not part of the core or standard Ruby libraries. 'concerning' is just an extension added by Rails for creating a Module, so:

```ruby
module Test
  concerning :MyConcern do
  end
end
```

Expands to:

```ruby
module Test
  module MyConcern
    extend AS::Support
  end
  include MyConcern
end
```

Ideally Yard would parse what 'concerning' expands to, in order to provide correct and accurate documentation. Given 'concerning' is ActiveSupport/Rails-specific, and 'concerning' could mean anything else in another library, i'm not sure if adding to Yard is correct.

**Comment by angelim** [comment]
You're totally right. My bad. I've updated the my comment so other people don't get confused.

**Comment by angelim** [comment]
I'll ask Olivier if he's interested in including this behavior in his plugin.
https://github.com/digitalcuisine/yard-activesupport-concern
