### ISSUE TITLE
core/Symbol class description rendered incorrectly 

### ISSUE THREAD

**Issue by r-obert** [lsegal/yard#1114]
The class description is not being parsed correctly on this page:
http://www.rubydoc.info/stdlib/core/Symbol

I didn't test locally with Ruby's source.

**Comment by lsegal** [comment]
github.com/docmeta/rubydoc.info is responsible for managing the rubydoc.info site, so you should report this issue there. 

Note that this may have been resolved in YARD 0.9.9, but also, YARD doesn't guarantee 100% compatibility with Ruby's C source implementation. There may be a need to manually workaround the syntax used in `string.c`.

**Comment by r-obert** [comment]
thanks @lsegal i'll create an issue on the rubydoc.info repository shortly.

**Comment by r-obert** [comment]
Going to close this in favour of the rubydoc.info issue.
