### ISSUE TITLE
yard server --gems private/protected methods

### ISSUE THREAD

**Issue by jsirex** [lsegal/yard#1115]
I'm looking for a way to start the documentation server for locally installed gems with private/protected methods included. But I can't do it.
I tried ~/.yardopts

```bash
╰─○ cat .yardopts 
--private
--protected
```

**Comment by lsegal** [comment]
You can't override settings on a global basis in the YARD server. Gems serve their own documentation using their own .yardopts settings.

A workaround would be to go into each gem directory (`~/.gems/gems/*/`) and add a `.yardopts` file to each one you care about.

**Comment by lsegal** [comment]
I would accept a PR to allow `yard server` to take a set of global default options.

**Comment by jsirex** [comment]
Work around works! 
Thanks.
