### ISSUE TITLE
attr docs persist on `yard server -r` when removed

### ISSUE THREAD

**Issue by Daniel-Worrall** [lsegal/yard#1117]
When running the yard server and removing a previously existing attr (reader/writer/accessor), it remains documented upon refreshing the page.

Additionally, if a reader changed to a writer (or vice-versa), YARD will think the reader is still there and interpret it as accessor. Expected result is for it to say read/write only respectively.

## Steps to reproduce

This is the minimal reproduction for the issue. I've done my best to remove
all extraneous code and unique environment state on my machine before providing
these steps:

0. `lib/yardtest.rb`
```rb
attr_reader :test
```
1. Run the following command: `yard server --reload`
2. Open browser to Top Level Namespace (server/docs/toplevel)
3. Edit the file to a different name or to writer (In our example, we'll just change to `test2`
4. Refresh the browser

## Actual Output

Both objects exist
https://i.imgur.com/aw6pKMR.png

## Expected Output

Expected test to be removed and test2 to remain.

## Environment details:

* OS: Windows 10 Pro 64 Bit
* Ruby version: ruby 2.4.1p111 (2017-03-22 revision 58053) [i386-mingw32]
* YARD version yard: 0.9.9

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by lsegal** [comment]
This is actually expected (though understandably confusing) behavior. The reload feature in the Yard server is only additive, and cannot remove objects. This will happen for all objects, not just attributes.

The intended use case for the reload server is for adding documentation to an existing API, or styling/customizing templates. Making large structural changes to code while running the server is not well supported. 

If you so want to do this, you can work around this limitation by deleting the .yardoc directory everytime a change is made. This will allow Yard to reparse data, though it will run a little slower.

As a side note, if yo lunch are interested in tackling a fix for this, I would be open to accepting a PR. 
Hope that helps.
