### ISSUE TITLE
yard 0.9.9 not rendering Markdown reference links in method summary.

### ISSUE THREAD

**Issue by nrser** [lsegal/yard#1118]
I have a method documented using markdown like:

```ruby
module NRSER
  VERSION = "0.0.21.dev"
  
  module Version
    # The [Gem::Version][] [release][Gem::Version#release] for {NRSER::VERSION}
    # - everything before any `-<alpha-numeric>` prerelease part (like `-dev`).
    # 
    # [Gem::Version]: https://ruby-doc.org/stdlib-2.4.1/libdoc/rubygems/rdoc/Gem/Version.html
    # [Gem::Version#release]: https://ruby-doc.org/stdlib-2.4.1/libdoc/rubygems/rdoc/Gem/Version.html#method-i-release
    #
    # @example
    # 
    #   NRSER::VERSION
    #   # => '0.0.21.dev'
    #   
    #   NRSER::Version.release
    #   # => #<Gem::Version "0.0.21">
    # 
    # @return [Gem::Version]
    # 
    def self.release
      gem_version.release
    end # .release
  end # module Version
  
end
```

`yard` is rendering the Markdown reference links fine in the `Class Method Details` section, but they are rendered incorrectly in the `Class Method Summary` section. The rendered text looks like:

    The [Gem::Version][] [release] for VERSION - everything before any -<alpha-numeric> prerelease part (like -dev).

You can clearly see the issue in the HTML:

```html
<span class="summary_desc">
  <div class="inline">
    <p>
      The [Gem::Version][] [<a href="Gem::Version#release">release]</a> for
      <span class="object_link"><a href="/docs/NRSER#VERSION-constant" title="NRSER::VERSION (constant)">VERSION</a></span> - everything before any
      <code>-&lt;alpha-numeric&gt;</code> prerelease part (like
      <code>-dev</code>).
    </p>
  </div>
</span>
```

## Steps to reproduce

1.  Make sure you got a modern Ruby and Bundler (I have `2.3.4` and `1.15.4`, respectively)
2.  If you trust me:  
    2.  `git clone git@github.com:nrser/nrser-ruby.git`
    3.  `cd nrser-ruby`
    4.  `bundle install --path=./.bundle`
    5.  `bundle exec yard server --reload`
    6.  Open http://localhost:8808/docs/NRSER/Version and take a look for yourself.
3.  Otherwise:
    1.  Make sure you're using `yard 0.9.9` (what I'm using) or a version you know is relevant to this issue.
    2.  Add the above code (or something like it) to a file you're doc'ing.
    3.  Make sure you have `--markup markdown` in your `.yardopts` file.
    4.  Generate the docs and check them out.

## Actual Output

Links in method summary are malformed (see above).

## Expected Output

Links in method summary are correctly formed like those in method details.

## Thoughts

It seems like `yard` is slicing off the beginning of the doc comment but not including the reference link definitions, which are important for the part it's taking to make sense and render correctly.

Including the link URLs inline (instead of as reference links) fixes it of course, but it makes the doc comment pretty much unreadable, which is kind-of against my understanding of the point of markdown (nicely readable in text form and HTML render).

## Thanks!

If you want me to try and take a look at fixing this I'm game, but I would appreciate some pointers from y'all the have a decent concept of the code base.

## Environment details:

* OS: OSX 10.12.6
* Ruby version (`ruby -v`): 2.3.4
* YARD version (`yard -v`): 0.9.9
* Relevant software dependency/versions: None.

**Comment by lsegal** [comment]
I'm not sure this can be supported. A summary line is always going to be the first sentence in your docstring, and there's no way for YARD to know where (or even how) a markup language's link references might live, so it would be difficult to parse them out.

For extra context here: YARD isn't Markdown specific, meaning, it actually doesn't even speak Markdown at all (parsing your Markdown actually happens in a third-party lib), so it would be unlikely to be supported in YARD core. I suppose you could do this with a plugin, but a shorter path would probably be:

1. Use regular Markdown style linking for these exceptions. This shouldn't be too painful, since presumably linking in your summary is a rare exception, and not something you do often-- realistically there is little value to linking to external documentation in a method summary, as the use case for users reading the summary line is primarily for understanding your library, not external ones. Linking to external resources in the first sentence generally only distracts from your docs, at least in my experience.

2. Mark these as plain code blocks and make use of `@see` tags for these kinds of resources, which is a more appropriate location for links to external type documentation to live. In your case, knowing about the details of `Gem::Version` and, more particularly, its `#release` method seem like addenda, not hard requirements to understanding the API. 

Hope that helps!

**Comment by nrser** [comment]
On a technical level... why not just pull the first sentence *after* rendering the entire doc chunk? Is there a reason that wouldn't work?

Yeah, maybe the RegExp or whatever gets slightly more complicated, but it seems like it would have a much better guarantee of correctness, especially since you *don't* control how those markup engines think about source => render - Markdown being one obvious example where you *can't* necessarily pull of a sentence and render it correctly without the rest of the logical block, and other markups could potentially do stuff like this too if they chose, right?

In response to (1), it sucks with the links inline:

```ruby
# The
# [Gem::Version](https://ruby-doc.org/stdlib-2.4.1/libdoc/rubygems/rdoc/Gem/Version.html)
# [release](https://ruby-doc.org/stdlib-2.4.1/libdoc/rubygems/rdoc/Gem/Version.html#method-i-release)
# for {NRSER::VERSION} - everything before any `-<alpha-numeric>` prerelease part (like `-dev`).
```

Much harder to read in source.

In response to (2), yeah, just not linking the text itself and using `@see` is prob the best solution.

On a philosophical level... I do link to external resources *a lot* - ideally every time anything of mine accepts or returns an object that is not defined in that library.

A lot of what I go look at docs for is to see what *type* of object something wants or provides, and it's a lot easier to just click on it than get up on Google and paw through stuff to find that object's API. It also let's you bake library versions into the links when warranted so clicks end up at the exact right API.

I'm most recently coming from using `ESDoc`, which automatically links to Node stdlib types and lets you easily define "external" types and then links them wherever it finds them too. So maybe I'm a little spoiled. But, seriously, I thought it was awesome and made my docs a lot more usable.

**Comment by lsegal** [comment]
> On a technical level... why not just pull the first sentence after rendering the entire doc chunk? Is there a reason that wouldn't work?

The reason this wouldn't work is that markup parsing happens at the rendering layer, while summary parsing happens earlier (in `YARD::Docstring#summary`). Technically, not all template renderers actually even parse markup, like the `text` format, which also doesn't understand Markdown. The HTML templates could be adjusted to avoid using `YARD::Docstring#summary`, but the payoff here is pretty small. There are also some pretty big parsing complexities once you bring HTML into the picture-- YARD doesn't actually have any dependencies on HTML parser libs, and adding one isn't likely to happen for just this use case. Currently the [summary parser implementation](https://github.com/lsegal/yard/blob/master/lib/yard/docstring.rb#L173) is fairly simplistic, and probably wouldn't handle HTML tags.

> easily define "external" types and then links them wherever it finds them too

This could be a feature I wouldn't mind YARD supporting. an `@!external_type [type] name url` directive to define external objects. This is probably a better general solution for what you are trying to do than the above discussion about summary parsing. Take a look at how directives work if you would be interested in tackling this, along with the definition of new ExternalObject type CodeObjects:

* https://github.com/lsegal/yard/blob/master/lib/yard/tags/library.rb#L605
* https://github.com/lsegal/yard/blob/master/lib/yard/tags/directives.rb
* https://github.com/lsegal/yard/tree/master/lib/yard/code_objects

**Comment by nrser** [comment]
Ok, I get that dealing with rendering and HTML would be a pain. Sucks, because it means `yard` is fundamentally dependent on rendering being distributive (some form of `render(a + b) = render(a) + render(b)` for "sentences" `a` and `b`) for correct results, and it's not true for a very popular rendering option. Markdown isn't gonna change, and if `yard` isn't either, well, I guess it is what it is.

For this particular issue, yeah the externals stuff is 100% preferable. It's a really nice feature. `stdlib` linking and `Gemfile` parsing would be awesome.

I want to help, but it seems like it's going to require some decent time and thought to do right, and I'm super tight on time trying to get something out right now, but maybe in the next few months. I'll let you know if/when I'm able to make time for it.

**Comment by nrser** [comment]
Oh, and thanks for all the time and attention on this, much appreciated :)
