### ISSUE TITLE
Error message has misleading info

### ISSUE THREAD

**Issue by MikeNeate** [lsegal/yard#1120]
I'm getting the following error when building my docs. 

```
[error]: Unhandled exception in YARDJS::Handlers::ModuleHandler:
[error]:   in `lib/core.js`:0:

var AWS = {util: require('./util')};

```

The error reports that the issue is at line 0 in lib/core.js. After many hours trying to find what's wrong I'm sure that this reference is not the cause of the problem. Is there a way of getting more information on the error and finding exactly what's causing it?

Many thanks
Mike

**Comment by lsegal** [comment]
If you use `yard --debug`, it will show the full exception stack trace. You may want to look at the [lsegal/yard-js](http://github.com/lsegal/yard-js) project for more info, or the [aws/aws-sdk-js](http://github.com/aws/aws-sdk-js) project to report any doc generation issues.
