### ISSUE TITLE
Appveyor - fails with 2.4 and trunk

### ISSUE THREAD

**Issue by MSP-Greg** [lsegal/yard#1122]
Loren,

There have been some changes to Ripper, and I believe RDoc is now using it (or in the process of converting).  I opened some issues for what I found, but I think there are more...

I added Appveyor to my fork and also added a trunk build, results [here](https://ci.appveyor.com/project/MSP-Greg/yard/build/1.0.2).

* 2.2.6 - Pass

* 2.3.3 - Pass

* 2.4.1 - Two failures, I think these can be fixed with a 'sort' of the lines?

* trunk/head - Eight failures.  Some look like easy fixes, others might be ruby ripper issues.

I hope to work on these, I thought I'd show you the results.  After all, not long before 2.5 is released.  As I recall, Travis ruby head build is often days (or weeks) old.

Aside - I think RedCloth can be installed easily in 2.4 and trunk, need to add a line to install ragel package.

Hope things are well, Greg

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by MSP-Greg** [comment]
The PR for stats fixes 2.4.1, so it should pass, the remaining trunk failures are from Ripper.

I've isolated all the remaining Ripper issues, one may be a breaking change, the others I'll submit a PR with added tests to Ruby showing the breakage.

Hence, trunk should be passing soon.  FYI, I've been involved quite a bit with ruby windows builds.

**Comment by lsegal** [comment]
Closing this in favor of PRs. Thanks for the fixes!
