### ISSUE TITLE
Command not found?

### ISSUE THREAD

**Issue by myfitment** [lsegal/yard#1125]
➜  me git:(master) ✗ gem install yard
--------------------------------------------------------------------------------
As of YARD v0.9.2:

RubyGems "--document=yri,yard" hooks are now supported. You can auto-configure
YARD to automatically build the yri index for installed gems by typing:

    $ yard config --gem-install-yri

See `yard config --help` for more information on RubyGems install hooks.

You can also add the following to your .gemspec to have YARD document your gem
on install:

    spec.metadata["yard.run"] = "yri" # use "yard" to build full HTML docs.

--------------------------------------------------------------------------------
Successfully installed yard-0.9.9
1 gem installed
➜  me git:(master) ✗ yard
zsh: command not found: yard

**Comment by lsegal** [comment]
This seems to be a configuration issue with your system. Can you print `gem env`?

**Comment by lsegal** [comment]
Closing as stale.
