### ISSUE TITLE
Error loading RubyGems plugin -> yard-0.8.7.6/lib/rubygems_plugin.rb": can't modify frozen Hash (RuntimeError)

### ISSUE THREAD

**Issue by joshRpowell** [lsegal/yard#1130]
RubyGems 2.7 released today: http://blog.rubygems.org/2017/11/01/2.7.0-released.html

## Steps to reproduce

This is the minimal reproduction for the issue. I've done my best to remove
all extraneous code and unique environment state on my machine before providing
these steps:

1. `gem update --system`
2. run again to confirm update:  `gem update --system`

## Actual Output

- 1st attempt
```
Updating rubygems-update
Fetching: rubygems-update-2.7.0.gem (100%)
Successfully installed rubygems-update-2.7.0
Installing RubyGems 2.7.0
Error loading RubyGems plugin "~/.rvm/gems/ruby-2.4.2@rails5.1/gems/yard-0.8.7.6/lib/rubygems_plugin.rb": can't modify frozen Hash (RuntimeError)
ERROR:  While executing gem ... (NoMethodError)
    undefined method `files=' for nil:NilClass
```

- 2st attempt
```
Error loading RubyGems plugin "~/.rvm/gems/ruby-2.4.2@rails5.1/gems/yard-0.8.7.6/lib/rubygems_plugin.rb": can't modify frozen Hash (RuntimeError)
Latest version already installed. Done.
```

## Expected Output

No error; usually see updates displayed

## Environment details:

* OS: macOS 10.13.1 (17B48)
* Ruby version (`ruby -v`): ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
* YARD version (`yard -v`): yard 0.8.7.6
* Relevant software dependency/versions:
  * [Any 3rd party libs required to reproduce, omit if none]

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by joshRpowell** [comment]
Looks like its related to this: https://github.com/rrrene/inch/issues/42

They have a dependency lock that's outdated.

**Comment by kvherro** [comment]
This happened to me recently. For me, doing a `--user-install` did the trick:
```
gem install --user-install yard -v 0.9.26`
```
