### ISSUE TITLE
yardoc does not work

### ISSUE THREAD

**Issue by sansae** [lsegal/yard#1132]
## Issue
Running the yardoc command does not work. According to the README file found here: https://github.com/lsegal/yard, "the easiest way to generate docs for your code is to simply type yardoc in your project root". It says that if your files are not in the lib folder, you should specify it. I did that and the docs weren't generated.

## Steps to reproduce
After switching to the root folder where my ruby files are, I ran the following command:
$ yardoc my_ruby_file.rb
(I also tried $ yard doc my_ruby_file.rb)

## Actual Output
```
Files:           1
Modules:         0 (    0 undocumented)
Classes:         0 (    0 undocumented)
Constants:       0 (    0 undocumented)
Attributes:      0 (    0 undocumented)
Methods:         1 (    1 undocumented)
 0.00% documented
```

## Expected Output
This is my first time using yard. I'm assuming that after running that yardoc command on a ruby file that contains methods, the expected output should be documentation in my ruby files that look something like this:
```
# Reverses the contents of a String or IO object.
#
# @param [String, #read] contents the contents to reverse
# @return [String] the contents reversed lexically
def reverse(contents)
  contents = contents.read if contents.respond_to? :read
  contents.reverse
end
```
I have a ruby file that contains one method. I ran yardoc on that .rb file and it showed that result above. yardoc detected a method in the file that I called yardoc on, but it produced no documentation. it should be noted that whenever i run yardoc on any file or root folder, the said file or root folder flashes/blinks in my atom editor. Something is happening, but i'm not getting the expected results.

## Environment details:

* OS: Ubuntu Guest, Version 16.04.3 LTS (installed in virtualbox, version 5.1.28)
* Ruby version (`ruby -v`): 2.3.1
* YARD version (`yard -v`): 0.9.9

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by lsegal** [comment]
Can you show what is in `my_ruby_file.rb`?

Also can you run yard with `--debug`?

**Comment by sansae** [comment]
Hey @lsegal, thank you for such a quick response.

Unfortunately, I can't share the exact code with you. It's actually a coding challenge that I'm doing for an internship. Their rules were, don't share it with anyone without their expressed permission.

Let's just say that this method is a very, very, very simple method that contains a hash. Here's some more background: my program contains 7 files. There is one main file that has no method, but makes a call to a method that is in a file of its own. The method in this file calls another method that is in another file of its own, and so on. Nothing complicated. I thought perhaps that was the issue, until I created a test.rb file and ran yardoc on that. same issue. method detected, but no ruby docs generated.

I ran yardoc --debug in the project root. here are the results:
```
[debug]: Parsing ["{lib,app}/**/*.rb", "ext/**/*.{c,cc,cxx,cpp}"] with `ruby` parser
[debug]: Serializing to .yardoc/objects/root.dat
[debug]: Re-generating object ...
[debug]: Generating asset js/jquery.js
[debug]: Serializing to doc/js/jquery.js
[debug]: Generating asset js/app.js
[debug]: Serializing to doc/js/app.js
[debug]: Generating asset js/full_list.js
[debug]: Serializing to doc/js/full_list.js
[debug]: Generating asset css/style.css
[debug]: Serializing to doc/css/style.css
[debug]: Generating asset css/common.css
[debug]: Serializing to doc/css/common.css
[debug]: Generating asset css/full_list.css
[debug]: Serializing to doc/css/full_list.css
[debug]: Generating asset class_list.html
[debug]: Serializing to doc/class_list.html
[debug]: Generating asset method_list.html
[debug]: Serializing to doc/method_list.html
[debug]: Generating asset file_list.html
[debug]: Serializing to doc/file_list.html
[debug]: Generating asset frames.html
[debug]: Serializing to doc/frames.html
[debug]: Serializing to doc/_index.html
[debug]: Serializing to doc/index.html
[debug]: Serializing to doc/file.README.html
[debug]: Serializing to doc/top-level-namespace.html
Files:           0
Modules:         0 (    0 undocumented)
Classes:         0 (    0 undocumented)
Constants:       0 (    0 undocumented)
Attributes:      0 (    0 undocumented)
Methods:         0 (    0 undocumented)
 100.00% documented
```

**Comment by zverok** [comment]
@sansae Sorry if I am wrong, but I suspect that you misunderstood what YARD does. Are you expecting that it will add _comments with documentation_ to your `my_ruby_file.rb`?

**Comment by sansae** [comment]
hey @lsegal 
I also ran "$ yard --debug" and got the same results

**Comment by sansae** [comment]
Hey @zverok, thanks for the response.

To answer your question, yes and no?

From what I've read, I was expected YARD to act sort of like JSDOC for the atom editor. I have JSDOC installed for atom, which is superneat. When I go to the very top of a method that has a return value and parameters, typing in CTRL + SHIFT + J auto-generates a "template" that helps me document that method. Variables and parameters are automatically created, and all I have to do is type in what that method does and other misc stuff that i want to include.

In short, I was hoping YARD, or more specifically, yardoc, would do that for me if I typed in "$ yardoc my_ruby_program.rb"

From here: https://github.com/lsegal/yard, and under "Generating Documentation", it says this:
"The most common command you will probably use is yard doc, or yardoc. You can type yardoc --help to see the options that YARD provides, but the easiest way to generate docs for your code is to simply type yardoc in your project root. This will assume your files are located in the lib/ directory. If they are located elsewhere, you can specify paths and globs from the commandline via:"

I hope that was clear

**Comment by zverok** [comment]
Yep, it was clear, but it is absolutely different from what YARD does :)

YARD takes your documentation comments (that you wrote yourself, the format is really simple to make any "templating" for it), and generates HTML docs from them. After `yard doc` look at `doc/index.html`, that would be the result of YARD's work.

**Comment by sansae** [comment]
@zverok,
wow... so that's what it does?

I just checked out the index.html file. It turns out this file is actually the README.md file that I created earlier. Other than that though, none of my other files (the ones with methods), show up in the doc folder.

**Comment by sansae** [comment]
So I guess I'll just have to write the docs myself.

I've used the eclipse and atom editors in the past. The former was for Java and the latter has been mainly for javascript (recently being using it for ruby). In my experience with both editors, there was a way to do that auto-generation thing. I thought YARD did the same thing, but you're telling me it doesn't.

Thank you so much for the clarification. I constantly find myself in a ELIA5 moment. If stuff ain't spelled out for me like abc, it'll likely fly over my head.

thanks @zverok

**Comment by zverok** [comment]
Yep, that's how it works. BTW, in generated docs, on the left side, you can see code objects list (if it is just methods, they all will be in "Top Level Namespace"), and can navigate them and review generated docs.

**Comment by lsegal** [comment]
It is indeed expected that you would write the docs. AFAIK IntelliJ's RubyMine has a form of template expansion for docstrings, but that is generally a problem left for IDEs to solve.

**Comment by sansae** [comment]
@zverok,

After I wrote the docs for my method and ran "$ yardoc my_file.rb", I navigated to the top level namespace and saw what you pointed out. Thank you :)
