### ISSUE TITLE
YARD Type Parser site is down

### ISSUE THREAD

**Issue by ms-ati** [lsegal/yard#1136]
## Steps to reproduce

1. Open browser to (https://yardoc.org/types.html)
2. Enter any YARD type syntax and click "Parse"
3. Observe 502 error indicating back-end is entirely down

[x] I have read the [Contributing Guide][contrib].

**Comment by ms-ati** [comment]
@lsegal I hate to bug you, but just wondering is fixing the YARD Type Parser site something that [we](http://engineering.panoramaed.com/) might be able to help you with?

**Comment by lsegal** [comment]
Thanks for opening this. I've resolved the issue with some server configuration and it should be working now!
