### ISSUE TITLE
YARD erroring on README build status badges from travis.ci and appveyor

### ISSUE THREAD

**Issue by predatorian3** [lsegal/yard#1138]
YARD throwing stacktrace when encountering `[![Build Status]]` badges in a README

## Steps to reproduce

Using the `YARD::Rake::YardocTask`
```ruby
YARD::Rake::YardocTask.new do |t|
  t.files = ['lib/**/*.rb', 'README.md', 'Rakefile']
end
```
Generating YARD docs for the following repo: https://github.com/tachyons/botframework-ruby

## Actual Output

```ruby
[warn]: Syntax error in `readme.md`:(3,15): syntax error, unexpected tconstant, expecting keyword_do or '{' or '('
[warn]: ParserSyntaxError: syntax error in `README.md`:(3,15): syntax error, unexpected tCONSTANT, expecting keyword_do or '{' or '('
[warn]: Stack trace:
        C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.10/lib/yard/parser/ruby/ruby_parser.rb:587:in `on_parse_error'

        C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.10/lib/yard/parser/ruby/ruby_parser.rb:56:in `parse'
        C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.10/lib/yard/parser/ruby/ruby_parser.rb:56:in `parse'
        C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.10/lib/yard/parser/ruby/ruby_parser.rb:17:in `parse'
        C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.10/lib/yard/parser/source_parser.rb:442:in `parse'
        C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.10/lib/yard/parser/source_parser.rb:46:in `block in parse'
```

## Expected Output

No stacktrace.

## Environment details:

* OS: Windows 10 CU
* Ruby version (`ruby -v`): ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]
* YARD version (`yard -v`): yard 0.9.10
* Relevant software dependency/versions:
  * https://github.com/tachyons/botframework-ruby

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by lsegal** [comment]
Markdown and other README files should be specified after a separating `-` token as per [documentation and example](http://www.rubydoc.info/gems/yard/YARD/Rake/YardocTask#files-instance_method):

> #files ⇒ Array<String>: The Ruby source files (and any extra documentation files separated by '-') to process.

**Comment by predatorian3** [comment]
Yes, you were right. Its in the documentation. put a `-` between the ruby files and the README and other non-ruby files. Thank you again.
