### ISSUE TITLE
List of Yard plugins

### ISSUE THREAD

**Issue by noraj1337** [lsegal/yard#1139]
As there is no plugin-manager in Yard, is that possible to open the Github wiki or add a page on yardoc.org to list the plugins for Yard.

Until now there is no easy way to know existing plugins for Yard.

If you open the wiki, let me know I'll contribute, if it's a web page let me know too I'll make a PR.

**Comment by lsegal** [comment]
The convention is to name a gem with the `yard-` prefix. Unfortunately you can't search RubyGems for prefixes, but you can do a search for `yard-` generally and it should pick up all YARD related gems, including plugins:

https://rubygems.org/search?utf8=%E2%9C%93&query=yard-

Documentation to describe how to search for this would probably be helpful in the Getting Started Guide-- I'd accept a doc PR for that.

Hope that helps!

**Comment by noraj1337** [comment]
It is also possible to ask for gem beginning with `yard-` or `yard_` in google:

```
site:rubygems.org intitle:"yard-" OR intitle:"yard_"
```

https://www.google.com/search?q=site%3Arubygems.org+intitle%3A%22yard-%22+OR+intitle%3A%22yard_%22

**Comment by lsegal** [comment]
I think this is resolved by #1143. Thanks!
