### ISSUE TITLE
Documenting the context of a yielded block

### ISSUE THREAD

**Issue by castwide** [lsegal/yard#1148]
I'm trying to document the fact that a method will execute its yielded block in a context other than itself. Simple example:

    class MyClass
      def other_object
        @other_object ||= OtherClass.new
      end
      # I want to document the fact that this block will be used in an OtherClass instance
      def set_other_block &block
        @other_block = block
      end
      def run_block
        other_object.instance_eval &@other_block
      end
    end

Right now my solution is to make up a tag called yieldself:

    # ...
    # @yieldself [OtherClass]
    def set_other_block &block
    # ...

Is there a way to do this with the existing tag architecture?

**Comment by lsegal** [comment]
There is currently no builtin tag to describe this semantic. Using a custom `@yieldself` seems like a reasonable thing to do here.

**Comment by castwide** [comment]
Works for me. Thanks.
