### ISSUE TITLE
Regression between 0.9.10 and 0.9.11

### ISSUE THREAD

**Issue by thomthom** [lsegal/yard#1149]
We find that after version 0.9.11 yard fails to generate our documentation where 0.9.10 succeeded.

## Steps to reproduce

I'm still working on narrowing down a minimal example. I'll update as I find something. But wanted to see if I anyone had any ideas on what changed recently.

I wonder if relative paths in the config file is what's throwing off YARD in the latest version:

`.yardopts`:
```
--title "SketchUp Ruby API Documentation"
--no-api
--no-private
--tag par --hide-tag par
-e su-api_plugin.rb
-p su-template

--exclude ../../../common/ruby/runits.cpp

--exclude ../../../layout/ruby/rcommand.cpp
--exclude ../../../layout/ruby/rdictionary.cpp
--exclude ../../../layout/ruby/rlayout.cpp
--exclude ../../../layout/ruby/rpluginstoolbar.cpp
--exclude ../../../layout/ruby/rpreferences.cpp
--exclude ../../../layout/ruby/rui.cpp

../runits.cpp
../rsketchup.cpp
../../../common/ruby/*.cpp
../rentity.cpp
../rdrawingelement.cpp
../rui.cpp
../*.cpp
../observer/rubyentityobserver.cpp
../observer/rubyentitiesobserver.cpp
../observer/*.cpp
../../../../content/sketchup/Tools/sketchup.rb

../../../layout/ruby/rlo.cpp
../../../layout/ruby/rentity.cpp
../../../layout/ruby/*.cpp

-
pages/*.md
../../../layout/ruby/documentation/pages/LayOut.md
```

When I test the path with `irb` from the same directory I'm running `yard` it's able to resolve the file:

```
λ irb
irb(main):001:0> file = '../../../layout/ruby/documentation/pages/LayOut.md'
=> "../../../layout/ruby/documentation/pages/LayOut.md"
irb(main):002:0> File.exist?(file)
=> true
irb(main):003:0>
```

## Actual Output

```sh
λ yardoc --debug
[warn]: Invalid file: ../../../layout/ruby/documentation/pages/LayOut.md
[debug]: Parsing ["../runits.cpp", "../rsketchup.cpp", "../../../common/ruby/*.cpp", "../rentity.cpp", "../rdrawingelement.cpp", "../rui.cpp", "../*.cpp", "../observer/rubyentityobserver.cpp", "../observer/rubyentitiesobserver.cpp", "../observer/*.cpp", "../../../../content/sketchup/Tools/sketchup.rb", "../../../layout/ruby/rlo.cpp", "../../../layout/ruby/rentity.cpp", "../../../layout/ruby/*.cpp"] with `ruby` parser
[debug]: Parsing ../runits.cpp
C:/Ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.12/lib/yard/core_ext/file.rb:67:in `initialize': No such file or directory @ rb_sysopen - runits.cpp (Errno::ENOENT)
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.12/lib/yard/core_ext/file.rb:67:in `open'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.12/lib/yard/core_ext/file.rb:67:in `read_binary'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.12/lib/yard/parser/source_parser.rb:422:in `parse'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.12/lib/yard/parser/source_parser.rb:46:in `block in parse'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.12/lib/yard/logging.rb:82:in `capture'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.12/lib/yard/parser/source_parser.rb:45:in `parse'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.12/lib/yard/parser/source_parser.rb:371:in `parse_in_order'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.12/lib/yard/parser/source_parser.rb:114:in `block in parse'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.12/lib/yard/logging.rb:182:in `enter_level'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.12/lib/yard/parser/source_parser.rb:113:in `parse'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.12/lib/yard.rb:20:in `parse'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.12/lib/yard/cli/yardoc.rb:259:in `block in run'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.12/lib/yard/serializers/yardoc_serializer.rb:56:in `lock_for_writing'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.12/lib/yard/registry_store.rb:197:in `lock_for_writing'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.12/lib/yard/registry.rb:210:in `lock_for_writing'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.12/lib/yard/cli/yardoc.rb:258:in `run'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.12/lib/yard/cli/command.rb:14:in `run'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.12/bin/yardoc:13:in `<top (required)>'
        from C:/Ruby23/bin/yardoc:22:in `load'
        from C:/Ruby23/bin/yardoc:22:in `<main>'
```

## Expected Output

This is expected output (from yard 0.9.9/0.9.10)

```sh
λ yardoc
Files:         134
Modules:         7 (    0 undocumented)
Classes:       134 (    0 undocumented)
Constants:     491 (  185 undocumented)
Attributes:      0 (    0 undocumented)
Methods:      1798 (    0 undocumented)
 92.39% documented
```

## Environment details:

* OS: Windows 10
* Ruby version (`ruby -v`): `ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]`
* YARD version (`yard -v`): `yard 0.9.12`

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by thomthom** [comment]
After narrowing down to what version caused the change I spotted this commit: https://github.com/lsegal/yard/commit/b0217b3e30dc53d057b1682506333335975e62b4

"Disallow relative paths that start with ../"

I see the spec changed to "does not allow relative path above root". Does "root" mean "project root"?

Any ideas on how we can reconfigure the config file? I'm a little confused to why it seems to fail on the `.md` file but none of the source files.

**Comment by lsegal** [comment]
This was an intentional change due to a security issue. YARD has never explicitly supported relative parent paths; this was a bug due to a missing validation check. 

> Does "root" mean "project root"?

Root means multiple things depending on how you're using YARD, it is arguably a little ambiguous. Ideally "root" refers to your project root, yes. However, in practice root means your working directory since YARD isn't able to actually know the structure of your project files on disk. The *general expectation* is that you have your `.yardopts` at the root of your Git repository, and you are running `yard` from that working directory as well.

If you happen to be running it from a directory level into the project, that would be the root, and you will have relative path issues. In your case, you can either move your .yardopts to a different location (ideally the repository root) and run from there, or just run `yard` from your repository root but point to a custom options file with `--yardopts dir/.yardopts`.

**Comment by thomthom** [comment]
I see - so the paths in `.yardopts` is relative to working directory and not the file itself?

That could make migration for us easier. Because we always had a `documentation` directory further up from the project root - in order to keep all documentation related stuff grouped. We have a very large project. Directory structure is different from a normal Ruby application - we embed an Ruby interpreter into our desktop application. Moving our `documentation` directory would not be ideal.

But if it's based on the current working directory I can create a wrapper executable that launch from further down the directory structure - using our current config file and setting the output directory to where it currently is.

I'll play with that and see how well that works. Thanks for the insight to how YARD resolve the file and how it considers what is `root`.

(Btw, in terms of preventing YARD server from reading files it should not - could that not have been enforced by file permissions on the server?)

**Comment by lsegal** [comment]
> I see - so the paths in .yardopts is relative to working directory and not the file itself?

This is indeed the case. The assumption is that `yard` is run in the same directory as the `.yardopts` file, but that is not *always* the case. Relative paths are basically assumed to be relative to the working directory.

> (Btw, in terms of preventing YARD server from reading files it should not - could that not have been enforced by file permissions on the server?)

Yes, that would be good general practice for *extra* protection, but not all world readable files on a system are necessarily expected to be served over the wire. There are many places where potentially private information can be made available through world readable files in an environment (think `/dev`, even leaking information about which binaries are installed on a system could be dangerous).

**Comment by thomthom** [comment]
It appear that also `{include:} directives are also relative to the working directory. Is there any way to control this? (Trying to minimise rippling effect in file changes.)

**Comment by thomthom** [comment]
Would you accept a PR the allow `{include:}` to use the location of the current file that is parsed to be used to resolve relative paths? It could be a fallback when resolving relative to working directory doesn't find a matching file.
