### ISSUE TITLE
default readme file problem

### ISSUE THREAD

**Issue by sobakasu** [lsegal/yard#1151]
Hi, I'm not sure exactly how this is supposed to work, but..
I have multiple readme files in my project in this format:

    README.md
    README.de.md
    README.es.md

When I run yard with no arguments it uses the content from "README.de.md" in the documentation index. I think it's because that file appears first in the directory. 

## Steps to reproduce

1. Add readme files as above to project.
2. Run the following command: `yard doc --no-private`
3. Open browser to main index url

## Actual Output

displays contents of README.de.md

## Expected Output

displays contents of README.md (I guess?)

**Comment by lsegal** [comment]
@sobakasu you can specify the README you want to use in your `.yardopts` in the form (the "-" is significant):

```
- README.md
```

You can also specify that in the command line, see `yard doc help` for information on how to specify extra files. Alternatively, you can use the `--readme` switch too (though that's not the recommended form).

**Comment by sobakasu** [comment]
Hi @lsegal, thanks for that - unfortunately I tried that and it doesn't seem to work for me.
I see in `lib/yard/cli/yardoc.rb` line 297 it is using the first README file found as the index (i'm using yard 0.9.12).

    2.4.1 :001 >         readme = Dir.glob('README{,*[^~]}').first
     => "README.de.md"

**Comment by sobakasu** [comment]
just found I can override it with the `--readme` switch as you mentioned, thanks!
