### ISSUE TITLE
Render: 2 vs 4 white spaces in markdown lists

### ISSUE THREAD

**Issue by noraj1337** [lsegal/yard#1155]
In all my project in using 2 spaces as indentation. For YARD I'm also using some markdown files where I wanted to also use 2 spaces.

The weird thing is, if I am using two white spaces as indentation for a list, the 3rd level is not rendered properly by YARD (but is by all markdown renderers).

![](https://i.imgur.com/yQcEvKV.png)
![](https://i.imgur.com/hYFkzWq.png)

But this works perfectly with 4 white spaces.

![](https://i.imgur.com/I3JYkdK.png)
![](https://i.imgur.com/FP358dt.png)

It seems to occurs only for markdown because I tried the same thing for rdoc and I get the following:

![](https://i.imgur.com/0rR3e4d.png)
![](https://i.imgur.com/Iyl9Zsy.png)

ps : I know it's `2nd` and not `2th` but screenshot are taken.

## Steps to reproduce

Use this markdown to reproduce:

```markdown
+ 1st
  + 2nd
    + 3rd
```

And render with yard, default options, and the dependencies specified in *Environment details*.

## Actual Output

Markdown source

![](https://i.imgur.com/yQcEvKV.png)

Render to

![](https://i.imgur.com/hYFkzWq.png)

## Expected Output

Markdown source

![](https://i.imgur.com/yQcEvKV.png)

Should render to

![](https://i.imgur.com/FP358dt.png)

## Environment details:

* OS: Antergos
* Ruby version (`ruby -v`): ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
* YARD version (`yard -v`): yard 0.9.12
* Relevant gems dependency/versions:
  * github-markup (1.6.2, 1.6.1)
  * redcarpet (3.4.0)

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by lsegal** [comment]
Have you tried another markdown renderer library? This might be a limitation of the library. YARD doesn't do any processing on Markdown files except for `{...}` syntax.

**Comment by noraj1337** [comment]
makrdown:

```markdown
+ 1st
  + 2nd
    + 3rd
```

render:

```html
$ github-markup test.md 
<ul>
<li>1st

<ul>
<li>2nd</li>
<li>3rd</li>
</ul></li>
</ul>
```

I'm ashamed I didn't test this. I'm confused because it is the official https://github.com/github/markup and this behaviour doesn't occur on github.

**Comment by noraj1337** [comment]
related redcarpet issue
- https://github.com/vmg/redcarpet/issues/429
- https://github.com/vmg/redcarpet/issues/615
- https://github.com/vmg/redcarpet/issues/500
