### ISSUE TITLE
Private tag (# @private) no longer working correctly

### ISSUE THREAD

**Issue by JonRowe** [lsegal/yard#1170]
Hi, it seems the private tag (`# @private`) has stopped working for an inherited class on `0.9.13`, we use this on RSpec to help us hide / ignore files that are internal workings not intended for direct manipulation, we also have a lint check enforcing we have 100% of our public API documented, since `0.9.13` this is now failing, see example: https://travis-ci.org/rspec/rspec-core/jobs/385051942 and the file in question: https://github.com/rspec/rspec-core/blob/7b6b9c3f2e2878213f97d6fc9e9eb23c323cfe1c/lib/rspec/core/formatters/json_formatter.rb

## Steps to reproduce

Run ` bin/yard stats --list-undoc` or ` bin/yard stats --list-undoc --no-private` against `rspec-core`, see that file is incorrectly marked as undocumented.

## Actual Output

```
Files:          34
Modules:        18 (    0 undocumented)
Classes:        37 (    1 undocumented)
Constants:       5 (    0 undocumented)
Attributes:     85 (    0 undocumented)
Methods:       259 (    8 undocumented)
 97.77% documented

Undocumented Objects:

(in file: lib/rspec/core/formatters/json_formatter.rb)
RSpec::Core::Formatters::JsonFormatter
RSpec::Core::Formatters::JsonFormatter#close
RSpec::Core::Formatters::JsonFormatter#dump_profile
RSpec::Core::Formatters::JsonFormatter#dump_profile_slowest_example_groups
RSpec::Core::Formatters::JsonFormatter#dump_profile_slowest_examples
RSpec::Core::Formatters::JsonFormatter#dump_summary
RSpec::Core::Formatters::JsonFormatter#message
RSpec::Core::Formatters::JsonFormatter#seed
RSpec::Core::Formatters::JsonFormatter#stop
```

## Expected Output

```
Files:          34
Modules:        18 (    0 undocumented)
Classes:        37 (    0 undocumented)
Constants:       5 (    0 undocumented)
Attributes:     85 (    0 undocumented)
Methods:       259 (    0 undocumented)
100% documented
```

## Environment details:

* OS: OS X 10.13.4, Travis (Ubuntu 14.04 LTD)
* Ruby version(s): 2.1, 2.2.10, 2.3.7, 2.4.4, 2.5.1
* YARD version (`yard -v`): 0.9.13

**Comment by lsegal** [comment]
Looks like a regression in symbol parsing (via #1168) is causing symbols to incorrectly parse and probably leading to the full Ruby file parsing incorrectly too. I will look into this.

**Comment by lsegal** [comment]
The regression was specific to symbols that used Ruby keywords as their symbol content, which was probably only affecting your JSON module. This will be fixed and a hotfix version pushed shortly.
