### ISSUE TITLE
RDoc stop/restart processing commands are not processed by Yard

### ISSUE THREAD

**Issue by unikitty37** [lsegal/yard#1182]
The second example at 
https://ruby.github.io/rdoc/RDoc/Markup.html#class-RDoc::Markup-label-Documenting+Source+Code states that "RDoc stops processing comments if it finds a comment line starting with -- right after the # character (otherwise, it will be treated as a rule if it has three dashes or more). This can be used to separate external from internal comments, or to stop a comment being associated with a method, class, or module. Commenting can be turned back on with a line that starts with ++."

This does not appear to work when 

## Steps to reproduce

This is the minimal reproduction for the issue. I've done my best to remove
all extraneous code and unique environment state on my machine before providing
these steps:

Given the following code in `helpers/ApplicationHelper`:
```
module ApplicationHelper
  ##
  # Extract the age and calculate the date-of-birth.
  #
  #--
  # FIXME: fails if the birthday falls on February 29th
  #++
  #
  # The DOB is returned as a Time object.
  def date_of_birth(age)
    # code here
  end
end
```

1. Run the following command: `yard doc --no-private`
2. Open browser to (URL)...
3. Click on ApplicationHelper link.

## Actual Output

```
└─▷ yard --debug
[debug]: Parsing ["{lib,app}/**/*.rb", "ext/**/*.{c,cc,cxx,cpp}"] with `ruby` parser
[debug]: Parsing app/jobs/application_job.rb
[debug]: Parsing app/models/application_record.rb
[debug]: Parsing app/helpers/application_helper.rb
[debug]: Parsing app/mailers/application_mailer.rb
[debug]: Parsing app/channels/application_cable/channel.rb
[debug]: Parsing app/controllers/application_controller.rb
[debug]: Parsing app/channels/application_cable/connection.rb
[debug]: Serializing to .yardoc/objects/root.dat
[debug]: Re-generating object ...
[debug]: Re-generating object ApplicationHelper...
[debug]: Re-generating object ApplicationCable...
[debug]: Re-generating object ApplicationJob...
[debug]: Re-generating object ApplicationRecord...
[debug]: Re-generating object ApplicationMailer...
[debug]: Re-generating object ApplicationCable::Channel...
[debug]: Re-generating object ApplicationController...
[debug]: Re-generating object ApplicationCable::Connection...
[debug]: Generating asset js/jquery.js
[debug]: Serializing to doc/js/jquery.js
[debug]: Generating asset js/app.js
[debug]: Serializing to doc/js/app.js
[debug]: Generating asset js/full_list.js
[debug]: Serializing to doc/js/full_list.js
[debug]: Generating asset css/style.css
[debug]: Serializing to doc/css/style.css
[debug]: Generating asset css/common.css
[debug]: Serializing to doc/css/common.css
[debug]: Generating asset css/full_list.css
[debug]: Serializing to doc/css/full_list.css
[debug]: Generating asset class_list.html
[debug]: Serializing to doc/class_list.html
[debug]: Generating asset method_list.html
[debug]: Serializing to doc/method_list.html
[debug]: Generating asset file_list.html
[debug]: Serializing to doc/file_list.html
[debug]: Generating asset frames.html
[debug]: Serializing to doc/frames.html
[debug]: Serializing to doc/_index.html
[debug]: Serializing to doc/index.html
[debug]: Serializing to doc/file.README.html
[debug]: Serializing to doc/top-level-namespace.html
[debug]: Serializing to doc/ApplicationHelper.html
[debug]: Serializing to doc/ApplicationCable.html
[debug]: Serializing to doc/ApplicationJob.html
[debug]: Serializing to doc/ApplicationRecord.html
[debug]: Serializing to doc/ApplicationMailer.html
[debug]: Serializing to doc/ApplicationCable/Channel.html
[debug]: Serializing to doc/ApplicationController.html
[debug]: Serializing to doc/ApplicationCable/Connection.html
Files:           7
Modules:         2 (    2 undocumented)
Classes:         6 (    6 undocumented)
Constants:       0 (    0 undocumented)
Attributes:      0 (    0 undocumented)
Methods:         1 (    0 undocumented)
 11.11% documented
```

![screen shot 2018-07-29 at 12 52 02](https://user-images.githubusercontent.com/139183/43366033-51b552aa-932e-11e8-9809-bc6b7977b042.png)

## Expected Output

The `FIXME:` line is not shown

## Environment details:

* OS: Mac OS X 10.12.6 (16G1408)
* Ruby version (`ruby -v`): ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-darwin16]
* YARD version (`yard -v`): yard 0.9.14

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by lsegal** [comment]
Start and stopdoc syntax is not supported by YARD. You can use the `@note` or `@todo` instead. 

Alternatively, if you don't want it to show up in documentation, you can define a custom hidden tag `--hidden-tag fixme` in your yardopts file, or put the fixme comment inside the method body rather than attached to the docstring itself.

Hope that helps!

**Comment by unikitty37** [comment]
Thanks — that example was just from then RDoc documentation. What I’m using is actually a comment to disable a Reek detector for a given function. Hopefully I’ll be able to find a way to have Yard ignore it and Reek still parse it :)

Are there any plans to add start/stopdoc syntax?

**Comment by lsegal** [comment]
There are no plans to support start/stopdoc syntax.

That said, it looks like based on reek documentation, you should be able to put your reek directives anywhere in the line, including after a YARD tag. This is actually how the Reek authors do it themselves:

https://github.com/troessner/reek/blob/master/lib/reek/code_comment.rb#L81

```ruby
# @quality :reek:TooManyInstanceVariables { max_instance_variables: 7 }
```

Using a tag like `@quality` would work if you added `--hidden-tag quality` to your .yardopts file.

**Comment by lsegal** [comment]
Marking this as closed since this is already handled in a supported way by Reek.

**Comment by unikitty37** [comment]
Thanks — but I now have this as my .yardopts:

```
--protected
--private
--hidden-tag quality
```

and I get the following output:
```
└─▷ yard server --reload
>> YARD 0.9.15 documentation server at http://localhost:8808
Puma starting in single mode...
* Version 3.12.0 (ruby 2.4.4-p296), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:8808
Use Ctrl-C to stop
[warn]: Unrecognized/invalid option: --hidden-tag
[warn]: Unknown tag @quality in file `app/helpers/application_helper.rb` near line 12
```

It does ignore the quality tag in the output, but only because it doesn't understand it 😁

What am I doing wrong in the .yardopts? I'd quite like to get this working without the warnings, as the sheer number of them masks other warnings…

**Comment by lsegal** [comment]
You would want to define the tag separately, so, `--tag quality --hidden-tag quality`

Hope that helps!

**Comment by unikitty37** [comment]
Ah, I've found the problem — it seems to want `--hide-tag`, not `--hidden-tag`.

Thanks!
