### ISSUE TITLE
Argument `--one-file` not worked

### ISSUE THREAD

**Issue by tit** [lsegal/yard#1184]
I want generate documentation as a single file.

## Steps to reproduce

1. Create empty `.rb` file.
2. run `yard doc --one-file --dubug empty.rb`

## Actual Output

```
[debug]: Parsing ["empty.rb"] with `ruby` parser
[debug]: Parsing empty.rb
[debug]: Serializing to .yardoc/objects/root.dat
[debug]: Re-generating object ...
```

```
/Users/tit/.rvm/gems/ruby-2.4.1/gems/yard-0.9.14/templates/default/onefile/html/setup.rb:44:in `block in parse_top_comments_from_file': can't modify frozen String (RuntimeError)
```

Show `setup.rb`

```ruby
# frozen_string_literal: true
...
data = ""
...
data << (token.text[/\A#\s{0,1}(.*)/, 1] || "\n")
```

## Expected Output

```
Files:           0
Modules:         0 (    0 undocumented)
Classes:         0 (    0 undocumented)
Constants:       0 (    0 undocumented)
Attributes:      0 (    0 undocumented)
Methods:         0 (    0 undocumented)
 100.00% documented
```

## Environment details:

* OS: ProductName: Mac OS X, ProductVersion: 10.14, BuildVersion: 18A377a
* Ruby version (`ruby -v`): ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]
* YARD version (`yard -v`): yard 0.9.14
* Relevant software dependency/versions:
  * rvm 1.29.4 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]

I have read the [Contributing Guide][contrib] (not really).

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by lsegal** [comment]
This is fixed in the above commit and will be part of the next release. Thanks for reporting!
