### ISSUE TITLE
Yard's own documentation is not well-formed

### ISSUE THREAD

**Issue by skalee** [lsegal/yard#1195]
The `@param` tag should be followed with description. Following line causes warnings to be printed:
https://github.com/lsegal/yard/blob/5deb08c329c0609429c2b8670ff139eb7a446635/lib/yard/docstring.rb#L380

Introduced in 5deb08c329c0609429c2b8670ff139eb7a446635 (#1185).

**Comment by lsegal** [comment]
Fixed by fa8d268938223559a810cd62273eba5a0b966be2
