### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by thomthom** [lsegal/yard#1203]
Any chance we could see a new release?

We got tooling that rely on the fix to `Docstring#to_raw`. Currently have to instruct people to install from source instead of using RubyGems. Would be nice to be able to go back to just using gems.

**Comment by lsegal** [comment]
v0.9.18 was released today. This should address any of the previous issues. Apologies for taking so long on this!

**Comment by thomthom** [comment]
No worries. I understand the hardship of maintaining open source projects.

I found that it was possible to refer to a git commit via Bundler - so that unblocked me.
