### ISSUE TITLE
declaring a generated class with @!parse does not list it in namespace

### ISSUE THREAD

**Issue by sdaubert** [lsegal/yard#1209]
In my project, I have a class generator. I defined constant from it and add `@!parse` directive to specify to yard this is a class. But in generated doc, this class is:
* listed as a subclass of generator (which is expected),
* listed as a constant in its namespace, but not as a class in its namespace.

## Steps to reproduce
This is a tiny project to demonstrate the issue:

```ruby
# This is the Namespace
module Namespace
  # Generator class
  class Generator
    def self.create
      Class.new(self)
    end
  end

  # @!parse
  #   # MyClass is a class.
  #   class MyClass < Generator; end
  MyClass = Generator.create
end
```

Then run these steps:

1. Run the following command: `yard doc`
2. Open browser to doc/index.html
3. Click on Class List link.

## Actual Output

1. MyClass is not listed in left pane
2. Click on Namespace link: MyClass is listed in constants.
3. Click on Generator link: MyClass is listed as a direct known subclass.
4. Click on MyClass link: MyClass has a dedicated page, presented it as a subclass of Generator.

## Expected Output

Steps 3 and 4 in previous sections seems good to me but steps 1 and 2 don't:

* MyClass should be listed in left pane of Class List,
* MyClass should not appear as a constant but as a class defined in namespace on Namespace module page.

## Environment details:

* OS: Debian buster
* Ruby version (`ruby -v`): ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux-gnu]
* YARD version (`yard -v`): yard 0.9.16

**Comment by lsegal** [comment]
Thanks for reporting. This is fixed in the above commit and will be in the next release.
