### ISSUE TITLE
Documenting stdlib requires explicit `lib` and `ext` arguments

### ISSUE THREAD

**Issue by castwide** [lsegal/yard#1213]
Based on the instructions at https://gnuu.org/2010/10/13/local-copies-of-documentation/, it should be possible to generate default documentation for the Ruby stdlib using the default source arguments, but doing so ignores .rb files in the `ext` directory.

## Steps to reproduce

This is the minimal reproduction for the issue. I've done my best to remove
all extraneous code and unique environment state on my machine before providing
these steps:

1. Run the following command from a Ruby source directory: `yardoc -b .yardoc-stdlib -n`
2. Run `yri -b .yardoc-stdlib Pathname#join`

## Actual Output

No documentation for `Pathname#join'

## Expected Output

The documentation from the source code

## Environment details

Tested with the source for Ruby 2.5.3.

## Solution

The command appears to work as intended if you pass the directories explicitly:

1. `yardoc -b .yardoc-stdlib -n ext lib`
2. `yri -b .yardoc-stdlib Pathname#join`

I don't know if this should be considered a bug--e.g., if the default source paths should include `ext/**/*.rb`--but I thought it deserved mentioning.

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by lsegal** [comment]
Seems totally reasonable to include .rb files as part of the `ext/**` glob. The above commit resolves this and will be in the next release. Thanks for reporting!
