### ISSUE TITLE
[Question] syntax highlight for yard comments in visual studio code

### ISSUE THREAD

**Issue by noraj** [lsegal/yard#1217]
This is not a bug but a question to yard community.

Did one of you found a way to have color syntax highlight for yard comments in visual studio code (vscode)?

Else it is hard to read the documentation in the source code.

![image](https://user-images.githubusercontent.com/16578570/51505871-7213da80-1de9-11e9-8981-48027dbbab5e.png)

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by shoesCodeFor** [comment]
Hi @noraj I noticed that it might be the theme you are using in VS Code.  I am using Night Owl and I can see the comments pretty clearly/ . 
![screen shot 2019-02-28 at 3 10 39 pm](https://user-images.githubusercontent.com/15178737/53602120-10265d80-3b6b-11e9-9417-6bb320d39ae9.png)

**Comment by noraj** [comment]
@shoesCodeFor I think you didn't understand. Your example is all green because your theme put comments in green, my example is all grey because my theme put comments in grey.
I didn't say it was not easy to read because of the color but because there is no syntax highlight of teh yard documentation as VSCode is seeing it as a simple comment.

**Comment by shoesCodeFor** [comment]
@noraj you are right I misunderstood.  I think the functionality you are requesting would be a VS Code plugin like Document This.  My mistake :)

**Comment by tcd** [comment]
I think I can do this.
I'll get on it.

**Comment by tcd** [comment]
![I can fix that](https://raw.githubusercontent.com/dunstontc/assets/master/gifs/i-can-fix-that.gif)

**Comment by dunstontc** [comment]
![I can fix that](https://raw.githubusercontent.com/dunstontc/assets/master/gifs/i-can-fix-that.gif)
Will post updates to this issue.

**Comment by tcd** [comment]
So the most popular Ruby support plugin for VS Code identifies [most Yard components](https://github.com/rubyide/vscode-ruby/blob/master/syntaxes/ruby.cson.json#L2648) save for leading comments.
Here are examples of highlighting applied to all identified elements. 

<img width="1680" alt="yard-hl-1" src="https://user-images.githubusercontent.com/51792731/67030317-c6c45780-f0d4-11e9-9428-2007d4d422ea.png">

<img width="1680" alt="yard-hl-2" src="https://user-images.githubusercontent.com/51792731/67030318-c6c45780-f0d4-11e9-9c21-fec33b86c817.png">

Can I get thoughts/input?

**Comment by noraj** [comment]
@tcd Yeah something like the first screenshot would be awesome.

**Comment by tcd** [comment]
@noraj Just pushed the [changes](https://github.com/dunstontc/dark-plus-syntax/blob/master/CHANGELOG.md#00156-november-18-2019).

**Comment by tcd** [comment]
@noraj I actually rolled the changes back... they were a bit distracting.
But if you want the highlighting from those screenshots, you can put this in your `settings.json`:

(first screenshot)
```
"editor.tokenColorCustomizations":
   "textMateRules": [
      {
          "scope": [
              "comment.line.keyword.punctuation.yard.ruby",
              "comment.line.keyword.yard.ruby",
              "comment.line.parameter.yard.ruby",
              "comment.line.type.yard.ruby",
              "comment.line.string.yard.ruby",
              "comment.line.punctuation.yard.ruby",
           ],
           "settings": {"foreground": "#608b4e"},
      },
   ]
}
```

(second screenshot)
```
"editor.tokenColorCustomizations":
   "textMateRules": [
      {
         "scope": [
             "comment.line.keyword.punctuation.yard.ruby",
             "comment.line.keyword.yard.ruby",
             "comment.line.parameter.yard.ruby",
             "comment.line.type.yard.ruby",
             "comment.line.string.yard.ruby",
          ],
          "settings": {"foreground": "#608b4e"},
      },
      {
          "scope": "comment.line.type.yard.ruby",
          "settings": {"foreground": "#4ec9b0"},
      },
      {
          "scope": "comment.line.parameter.yard.ruby",
          "settings": {"foreground": "#9cdcfe"},
      },
      {
          "scope": "comment.line.punctuation.yard.ruby",
          "settings": {"foreground": "#505050"},
      },
   ]
}
```

Or you can change the foreground colors to anything you'd like.

**Comment by noraj** [comment]
@tcd I installed `dark-plus-syntax` and add the following to my settings but I still have default comments.

```json
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": [
                    "comment.line.keyword.punctuation.yard.ruby",
                    "comment.line.keyword.yard.ruby",
                    "comment.line.parameter.yard.ruby",
                    "comment.line.type.yard.ruby",
                    "comment.line.string.yard.ruby",
                ],
                "settings": {
                    "foreground": "#608b4e"
                },
            },
            {
                "scope": "comment.line.type.yard.ruby",
                "settings": {
                    "foreground": "#4ec9b0"
                },
            },
            {
                "scope": "comment.line.parameter.yard.ruby",
                "settings": {
                    "foreground": "#9cdcfe"
                },
            },
            {
                "scope": "comment.line.punctuation.yard.ruby",
                "settings": {
                    "foreground": "#505050"
                },
            },
        ]
    }
```

Anyway I won't keep this theme, I love one dark pro too much. Yard syntax should be added in a dedicated syntax highlighter plugin not in a theme.

**Comment by tcd** [comment]
@noraj that's fair, I too like one dark pro. 
Regarding the groups, though, they're added by [this plugin](https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby), not my theme. (Which I pointed out back in [this comment](https://github.com/lsegal/yard/issues/1217#issuecomment-543266578)😉).  Themes typically don't define groups, they just assign colors to them.

**Comment by noraj** [comment]
@tcd Thanks I try this plugin immediately. And if not too complicated i'll try to create a Yard syntax plugin.

**Comment by lsegal** [comment]
Marking this as closed since this seems unrelated to YARD but there is some great work in here, would love to see it published to the marketplace 👏🏻👏🏻
