### ISSUE TITLE
Is there a way to find methods that are documented but contain undocumented parameters?

### ISSUE THREAD

**Issue by mensfeld** [lsegal/yard#1221]
I would love to be able to track down methods that are documented but that don't have one (or more) of the args documented:

```ruby
# Sums up two elements
# @param a [Integer] a nice number
def sum(a, b)
a + b
end
```

**Comment by lsegal** [comment]
@mensfeld 

You can run the following list query to get all methods that don't match the param tag count:

```sh
yard list --query "type == :method && !is_alias? && parameters.size != @@param.size"
```

This will list every method, including undocumented ones, so you could also narrow down only by methods with docs:

```sh
yard list --query "type == :method && !is_alias? && parameters.size != @@param.size && !docstring.blank?"
```

Or even just by documented methods with existing `@param` tags:

```sh
yard list --query "type == :method && !is_alias? && parameters.size != @@param.size && @@param.size > 0"
```

FYI: `@@param` in the above query is shorthand for `tags(:param)` if that makes it easier to understand.

Hope that helps!

**Comment by mensfeld** [comment]
Wow. That was quick and helpful! Now I have somethings to fix in couple repos:

![zrzut ekranu z 2019-02-01 18-23-40](https://user-images.githubusercontent.com/392754/52138809-8ad48980-264e-11e9-9f17-0f89813ea76f.png)

Thank you!
