### ISSUE TITLE
[Question] Option to get the line of the undocumented element for yard stats

### ISSUE THREAD

**Issue by mensfeld** [lsegal/yard#1224]
When I run `yard stats --list-undoc` I get the list of undocumented elements I have in my project. However, it does not provide me with the line to which it refers, which makes things a bit more complicated in terms of automated checking and converting into a UI output.

Example:

```
(in file: lib/whateva.rb)
Whateva#browser
Whateva#detect
Whateva#device
```

would there be an option to return also the line number, similar to how it is done for warnings:

```
    in file `app/services/something_else.rb' near line 13
[warn]: @param tag has unknown parameter name: options 
```

**Comment by lsegal** [comment]
I would accept a PR to add this information.

**Comment by mensfeld** [comment]
Ok. I can take a look at this next week!

**Comment by mensfeld** [comment]
Great news! After reviewing the yardoc code, I confirmed, that the `--compact` does the job!
