### ISSUE TITLE
[Question] Is there a way to extract only docs content

### ISSUE THREAD

**Issue by mensfeld** [lsegal/yard#1225]
First of all, sorry for spamming with so many questions. I'm building some tools around yard and to be honest - it is overwhelming (in a good way!).

What I'm looking for now is a programmatic way to extract yard messages for attributes but skipping examples.

For example, given something like that:

```ruby
This is a message with
Couple lines
@param a [Integer] great number
@param b [Integer] better number!
@example
  call(1, 2) #=> 3
def call(a, b)
  a + b
end
```

I would like to be able to extract messages and line numbers but without corresponding examples:

```ruby
results = `magical-yard-command`
p results
[
  ['This is a message with', 1],
  ['Couple lines', 2],
  ['great number', 3],
  [' better number!', 4],
]
```

or something similar.

Thanks in advance!

**Comment by lsegal** [comment]
@mensfeld unfortunately YARD doesn't store line numbers alongside comments after the parsing stage, though you can occasionally reconstruct the lines by counting newlines alongside the raw docstring, which you can get with [YARD::Docstring#all](https://www.rubydoc.info/gems/yard/YARD/Docstring#all-instance_method). If you did decide to do it this way, you would have to reparse the tags themselves.

```ruby
irb(main):003:0> YARD::Registry.at('Foo#call').docstring.all
=> "This is a message with\nCouple lines\n@param a [Integer] great number\n...
```

Another way to do this would be to build a custom [DocstringParser](https://www.rubydoc.info/gems/yard/YARD/DocstringParser) that parses tags but extracts line information alongside the data itself. You can do this by subclassing or copying the implementation directly.

Hope that helps!

**Comment by mensfeld** [comment]
Thank you. This is sufficient enough! Looking forward to other answers (not that I rush you ;) ).
