### ISSUE TITLE
`yard server` omits charset from Content-Type header, breaks UTF-8 display

### ISSUE THREAD

**Issue by nrser** [lsegal/yard#1236]
Documents are getting served on my local machine with a `Content-Type: text/html` header, without any `charset`. This seems to cause major browsers (Chrome `73.0.3683.86`, Firefox `66.0.2`, Safari `12.0.3`) to use a default encoding (`windows-1252` in my case), which may break display of many Unicode characters.

Changing the header to `Content-Type: text/html; charset=utf-8` resolves the issue across the board.

The relevant code is here:

https://github.com/lsegal/yard/blob/1f7307c85c5d24e9dc35618f1eff80f4976776ff/lib/yard/server/commands/base.rb#L92

Is the Content-Type supposed to be being sent down the wire as just `text/html`?

I understand that `UTF-8` probably isn't the right encoding for everyone all the time, but unless there's something screwy going wrong then it seems like having no encoding in the header can definitely cause issues in a pretty common setup (macOS / English / any of the major browsers).  

## Steps to reproduce

1.  Put together a minimal file like:
    
    ```ruby
    # encoding: UTF-8

    # Hey there! 你好！
    module MyModule; end
    ```
    
2.  Run the following command: `yard server`
3.  Open browser to <http://localhost:8808/docs/MyModule>
4.  If you **do** see the characters displayed correctly, maybe check that your browser(s) are updated and that they aren't defaulting to UTF-8 on their own (default installations in English on MacOS do not seem to use UTF-8 by default). Firefox in particular dropped a warning about the content type, as you can see in the screen shots below...

## Actual Output

![Screen Shot 2019-03-31 at 9 40 50 PM](https://user-images.githubusercontent.com/207603/55289801-d6f93b80-53fd-11e9-8fae-33c1e29c370a.png)

![Screen Shot 2019-03-31 at 9 23 08 PM](https://user-images.githubusercontent.com/207603/55289811-e1b3d080-53fd-11e9-8b15-e5ae5672229e.png)

![Screen Shot 2019-03-31 at 9 14 48 PM](https://user-images.githubusercontent.com/207603/55289814-e7111b00-53fd-11e9-8a35-d6b1e4d84e2a.png)

Check out that response header, as well as the output from `document.characterSet`:

![Screen Shot 2019-03-31 at 9 44 19 PM](https://user-images.githubusercontent.com/207603/55289839-45d69480-53fe-11e9-9a48-18121f17fe5f.png)

You can also see that the `charset` is proper in the `html/head/meta` element, but that is being ignored in all three browsers (Chrome, Firefox, Safari):

![Screen Shot 2019-03-31 at 9 44 40 PM](https://user-images.githubusercontent.com/207603/55289857-82a28b80-53fe-11e9-8e69-135d18afdda3.png)

## Expected Output

After hacking the header to `Content-Type: text/html; charset=utf-8` things work fine:

![Screen Shot 2019-03-31 at 9 48 22 PM](https://user-images.githubusercontent.com/207603/55289901-e927a980-53fe-11e9-8da0-12aeb83cbfdb.png)

## Environment details:

* OS: macOS `10.13.6` (English)
* Ruby version: `2.3.7`
* YARD version: `0.9.18`
* Chrome version: `73.0.3683.86`
* Firefox version: `66.0.2`
* Safari  version:`12.0.3`

**Comment by lsegal** [comment]
Content-types should be defined in the HTML documents served by the server, not the header itself, since the server doesn't know what's in the documents it is serving. YARD already does this via `<meta charset=...>`. If we need to make adjustments, we should probably make it in the HTML output itself.

**Comment by nrser** [comment]
@lsegal Yeah... the content-type *is* being set in the HTML document. Check this screen grab from above:

https://user-images.githubusercontent.com/207603/55289857-82a28b80-53fe-11e9-8e69-135d18afdda3.png

You can see it clearly, as well as the console line showing that it's not being used.

Granted, it's using `<meta name="Content-Type" .../>` instead of `<meta charset=... />`, but that is what YARD is serving up, and should work fine from what I've read.

In fact, it's been hard to find information on this specific circumstance - when there is a `Content-Type` header that does not include a `charset`, but there is a `<meta>` in the doc that does define the character set - but what I have found does seem to indicate that browsers *should* be ok with it:

> Note: The charset parameter [in the Content-Type header] may not be present. This is okay if your document itself indicates its character encoding.
> 
> <https://www.w3.org/International/questions/qa-headers-charset.en#webbased>

So... I feel like something else must be going wrong here, but I'm really not sure what...

**Comment by nrser** [comment]
Whop, I think I see it.. and it's not YARD, it's the `yard-cucumber` plugin overwriting the HTML headers, and doing them wrong... it should be `<meta http-equiv="Content-Type" ... />`, not `<meta name="Content-Type" ... />`.

...and that fixes it. Sorry to waste your time. I had not noticed/known that `name` was the wrong attribute name. I'll go bother those people...

**Comment by lsegal** [comment]
Ah yes, `name` vs `http-equiv` has burned me before. This may have actually just come from code that was in YARD (and written by me) a really long time ago. cc @burtlo for https://github.com/burtlo/yard-cucumber/blob/master/lib/docserver/default/layout/html/headers.erb#L1

**Comment by lsegal** [comment]
@nrser FYI you can workaround this by providing your own `headers.erb` file with the patched meta tag in a templates directory (`yard-templates/default/layout/html/headers.erb`) and adding `--template-path yard-templates` to your .yardopts to override the file.

**Comment by nrser** [comment]
I'm actually already running my own fork of `yard-cucumber`. Not the first thing I've wanted to change ;)
