### ISSUE TITLE
Missing period(.) auto-completion for `@return` tag

### ISSUE THREAD

**Issue by ybiquitous** [lsegal/yard#1245]
Hi,
I found a bit strange behavior about the period(.) auto-completion for a method doc only with `@return` tag, so I report the issue.

## Steps to reproduce

This reproduction doesn't use the command-line, but I think it describes the situation clearly, sorry. 😅 
The following example is one from the [capybara](https://github.com/teamcapybara/capybara) gem.

1. See <https://www.rubydoc.info/gems/capybara/3.21.0/Capybara/Session#current_host-instance_method>. The "Returns Host of the current page" method description generated by YARD automatically has no period(.). Here is the screenshot ⬇️ 
    <img width="317" alt="image" src="https://user-images.githubusercontent.com/473530/58389022-476cb380-8061-11e9-9ce6-a1e04dc43dae.png">
2. But in the method summary section, period(.) is completed automatically. Here is the screenshot ⬇️ 
    <img width="239" alt="image" src="https://user-images.githubusercontent.com/473530/58389060-a3373c80-8061-11e9-98c2-3190516d9bd8.png">
3. `@return [String] Host of the current page` is just written in the source code ⬇️ 
  https://github.com/teamcapybara/capybara/blob/3.21.0/lib/capybara/session.rb#L214-L218

## Actual Output

N/A

## Expected Output

I expect to complete periods automatically also in the body of methods.

## Environment details:

I'm not sure, but because it's on the latest <https://www.rubydoc.info>, I think the latest YARD version is used.

Thanks.

---

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by lsegal** [comment]
Fixed in master, will be out with the next YARD release.

**Comment by ybiquitous** [comment]
Thank you! 😄
