### ISSUE TITLE
[Suggestion] README Rake section about YardocTask

### ISSUE THREAD

**Issue by esotericpig** [lsegal/yard#1253]
I think the README should be updated to clarify the below issues for the Rake section about YardocTask (*Usage...2. Rake Task*).

**Options**
Just like Issue #1043, I stupidly tried this:
`task.options = ['--protected','--template-path my_templates']`

And then figured out that you have to specify "my_templates" separately:
`task.options = ['--protected','--template-path','my_templates']`

**Require**
Just like Issue #499, I first tried doing this:
`require 'yard/rake/yardoc_task' # NameError: uninitialized constant YARD::CLI`

And then realized you have to do this:
`require 'yard'`

To prevent further Issues being created from new users, I think it'd be a good idea to update the README if possible.

Thank you.

**Comment by skalee** [comment]
> Require
> Just like Issue #499, I first tried doing this:
> require 'yard/rake/yardoc_task' # NameError: uninitialized constant YARD::CLI
> 
> And then realized you have to do this:
> require 'yard'
> 
> To prevent further Issues being created from new users, I think it'd be a good idea to update the README if possible.

This particular issue has been fixed in #1244 (not merged to master yet).

**Comment by lsegal** [comment]
This has been merged and should be resolved in the next release.
