### ISSUE TITLE
[Suggestion] Don't include examples.txt in the releases

### ISSUE THREAD

**Issue by mensfeld** [lsegal/yard#1258]
Is there any particular reason to include the examples.txt in the yard releases?

It makes diffing a bit harder and makes the gem release a bit bigger:

https://diff.coditsu.io/diffs/fb7ec2d9-3950-4fd6-bc0c-235674c984ff#d2h-119238

**Comment by lsegal** [comment]
Thanks for reporting this. There's no particular reason, this file is being incorrectly included in the gem bundle.

**Comment by lsegal** [comment]
The next release of YARD will have this file excluded.
