### ISSUE TITLE
Default values on named parameters aren't detected by YARD

### ISSUE THREAD

**Issue by connorshea** [lsegal/yard#1262]
Default values aren't detected by YARD when they're on named parameters (`key: value`), only when they're 'normal' parameters (`key = value`).

## Steps to reproduce

```ruby
class Test
  # This method does something.
  # @param bar [String] Lorem ipsum
  # @param qux [String] Lorem ipsum
  # @return [String]
  def foo(bar = 'baz', qux: 'quux')
    'bar'
  end
end
```

1. Create the file above.
2. Run the following command: `yard doc`
3. Open the resulting generated HTML
4. Note that the parameter `bar` has a 'defaults to:' while `qux` does not.

## Actual Output

<img width="463" alt="Screen Shot 2019-07-06 at 7 54 16 PM" src="https://user-images.githubusercontent.com/2977353/60762996-3c298200-a028-11e9-80c1-b8cd4dba37b9.png">

Only `bar` has `defaults to:`, `qux` does not.

## Expected Output

I expected both parameters for the `foo` method to have default values in the parameter list.

## Environment details:

* OS: macOS Mojave (10.14.5)
* Ruby version (`ruby -v`): Ruby 2.6.2
* YARD version (`yard -v`): 0.9.20

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by lsegal** [comment]
Thanks for reporting-- this should be resolved in the next release.

**Comment by connorshea** [comment]
thanks!
