### ISSUE TITLE
Syntax highlighting only works for Ruby.

### ISSUE THREAD

**Issue by topherfangio** [lsegal/yard#1278]
I'm using GitHub flavored Markdown in my Yard documentation, but it appears to only recognize Ruby code no matter what I specify.

![Screen Shot 2019-09-27 at 3 48 33 PM](https://user-images.githubusercontent.com/54370/65801408-abea6d00-e13e-11e9-95d4-398624b3d6bd.png)

Here is the generated markup:

![Screen Shot 2019-09-27 at 3 50 04 PM](https://user-images.githubusercontent.com/54370/65801423-b6a50200-e13e-11e9-8150-9a48f933e6c6.png)

Notice that only the Ruby appears to have the tokens properly parsed.

Based on the [WhatsNew.md](https://rubydoc.info/gems/yard/file/docs/WhatsNew.md#Github_Flavoured_Markdown_now_works_out-of-box__0_7_4_) file, I thought that I didn't even need to do anything to get GHFM working, but it flat out doesn't work for any of them unless I install `redcarpet` and update my `.yardopts` file to look like the below (which I pulled from https://gist.github.com/nesquena/1406718).

```
-m markdown -M redcarpet --no-private --protected app/**/*.rb - README.md
```

Am I missing something or doing something wrong? 

## Steps to reproduce

1. Run `rails new` and CD into the directory.
2. Add `gem 'yard'` and `gem 'redcarpet'` to the `Gemfile` and run `bundle`
3. Alter `app/models/application_record.rb` to add the comment (below) at the top.
4. Run `yard -m markdown -M redcarpet --no-private --protected app/**/*.rb - README.md`
5. Run `yard server` and open http://localhost:8808 and navigate to the ApplicationRecord documentation.

```ruby
#
# Here is a quick test.
#
# ```ruby
# class Something
# end
# ```
#
# ```haml
# .ui.test
#   %h1 Hello
#   - This is a line
#   = This is a rendered line
# 
#   - component(:boom) do |boom|
#     - boom.woot
# ```
#
```

## Actual Output

Note that the `haml` section has no highlighting (or even token parsing). Only the `ruby` section is properly rendered.

## Expected Output

The `haml` section should have highlighting.

## Environment details:

* OS: mac OS Mojave 10.14.6
* Ruby version (`ruby -v`): `ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]`
* YARD version (`yard -v`): `yard 0.9.20`
* Relevant software dependency/versions:
  * `Rails 5.2.3`

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by lsegal** [comment]
You are right that only Ruby code is highlighted. Only syntax highlighting for Ruby is supported by default with YARD. If you need extra highlighting for separate languages, you can use a plugin like `yard-coderay` or `yard-pygments` ([see here](https://rubygems.org/search?utf8=%E2%9C%93&query=yard+highlight)) to get a larger array of syntax highlighting support. 

The GHFM note in WhatsNew is only about the support for recognizing GHFM _syntax_ and generating the correct semantic structures-- it was not intended to denote support for syntax highlighting. Sorry about the confusion there.

**Comment by topherfangio** [comment]
Ah, awesome, thank you! This worked great!
