### ISSUE TITLE
[Question] split long line without newline

### ISSUE THREAD

**Issue by noraj** [lsegal/yard#1286]
In an example tag `@example` I want to put a method and the output result but the output string is 128 bytes long.

This means the 80 char line length cop of rubocop is complaining but if I split the string on 3 lines newlines are happened no matter what I try to use.

Right now I dirtily wrapped the long line yard comment block with:

```
  # rubocop: disable Metrics/LineLength

<yard comments>
<code>

  # rubocop: enable Metrics/LineLength
```

Is there a way to split long lines on yard comments without newlines?

**Comment by lsegal** [comment]
@noraj can you provide a full example that reproduces this behavior? YARD `@example` tags can sit on multiple lines.

**Comment by noraj** [comment]
## Case 1 - No split

```ruby
class TestYard
  # @example
  #   testFunc('yard') # => "90bdcaa7ceb467d94a67489766a7d02d4135bca2f0bd398db2ec557f42e9b0b5de1413cb5563a36a76b9ed8db9460e990ab7b20794d261e6d582aab0933d5e7e"
  def testFunc(str)
    Digest::SHA2.new(512).hexdigest str
  end
end
```

Line far too long:

![image](https://user-images.githubusercontent.com/16578570/68162939-8af51300-ff59-11e9-8f4f-f11f2f9fe4e8.png)

But display nicely in yard

![image](https://user-images.githubusercontent.com/16578570/68162973-a06a3d00-ff59-11e9-9cea-ef4040e310cb.png)

## Case 2 - Split same level

```ruby
class TestYard
  # @example
  #   testFunc('yard') # => "90bdcaa7ceb467d94a67489766a7d02d4135bca2f0bd398db2e
  #   c557f42e9b0b5de1413cb5563a36a76b9ed8db9460e990ab7b20794d261e6d582aab0933d5
  #   e7e"
  def testFunc(str)
    Digest::SHA2.new(512).hexdigest str
  end
end
```

Line ok

![image](https://user-images.githubusercontent.com/16578570/68163101-0787f180-ff5a-11e9-8b0a-df315409cf1e.png)

but display in yard nok

![image](https://user-images.githubusercontent.com/16578570/68163181-44ec7f00-ff5a-11e9-9312-8e3d1018b414.png)

## Case 3 - Split with identation

```ruby
class TestYard
  # @example
  #   testFunc('yard') # => "90bdcaa7ceb467d94a67489766a7d02d4135bca2f0bd398db2e
  #     c557f42e9b0b5de1413cb5563a36a76b9ed8db9460e990ab7b20794d261e6d582aab0933
  #     d5e7e"
  def testFunc(str)
    Digest::SHA2.new(512).hexdigest str
  end
end
```

Line also ok

![image](https://user-images.githubusercontent.com/16578570/68163311-8715c080-ff5a-11e9-80c2-b200bcc1f66a.png)

But nok in yard too:

![image](https://user-images.githubusercontent.com/16578570/68163343-9c8aea80-ff5a-11e9-9393-4d3fe05c482a.png)

## Other

I also tried with `\` at the end of the line.

**Comment by lsegal** [comment]
YARD doesn't perform any type of translation on the comment source data, it is provided as is to the underlying renderer (markdown or RDoc). Indented code blocks are generally provided as pre-formatted blocks of unmodified text, so there's not much for YARD to do here.

You have a few options:

1) Don't list the entire string in your example if it's long. Depending on the example, it may not be important to provide the full string to your users. Something like this could work:

```ruby
# @example
#   testFunc('yard') # => "90bdcaa7cedfbc7d3ae332e..."
```

2) Use another Ruby-compatible format to display the string, i.e. heredoc or multiline strings:

```ruby
# @example
#   testFunc('yard')
#   # => "PARTA" +
#   #    "PARTB" + 
#   #    ...
```

Or 

```ruby
# @example
#   testFunc('yard')
#   # => <<EOF
#   # ..............
#   # ..............
#   # EOF
```

3) Ignore the Rubocop warning as you are doing now, or disable/adjust the warning to handle your files more appropriately. 

Hope that helps.

**Comment by noraj** [comment]
Thx @lsegal .

(2) is not an option as I won't change the result value.
(3) was the workaround I was temporary using.
(1) is totally a good option :+1: it's that I don't need to paste it all
