### ISSUE TITLE
Tags Overview markup is broken

### ISSUE THREAD

**Issue by pirj** [lsegal/yard#1300]
## Steps to reproduce

Open https://rubydoc.info/gems/yard/file/docs/Tags.md#abstract

## Actual Output

Starting with `@abstract` HTML tags start to sneak in making the doc hard to read:

![image](https://user-images.githubusercontent.com/6916/71783110-168b2e80-2ff3-11ea-9a59-1844239601f8.png)

## Expected Output

Has no HTML tags:
![image](https://user-images.githubusercontent.com/6916/71783100-eb084400-2ff2-11ea-9c74-14e6106f17bd.png)

## Environment details:

* OS: macOS 10.14, Firefox/Chrome

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by pirj** [comment]
Fixed in https://github.com/lsegal/yard/commit/4a8a1c70cee358c8ccd96ba7926aa11e278c8197
Thanks @lsegal ! ⚡️

**Comment by lsegal** [comment]
Thanks for reporting! This was also released in v0.9.23 updated rubydoc.info as well.
