### ISSUE TITLE
Extract type information

### ISSUE THREAD

**Issue by ericazhang17** [lsegal/yard#1302]
Hi there! Re issue #1076, I am wondering if it is possible to render the tag information so that it for each method, there can be a list of information like ClassName, MethodName, "(Param1Type, Param2Type, ...) ->  ReturnType" ? 

Right now using  p obj.tags(:param) or  p obj.tags(:return), I am able to get a list of objects [#<YARD::Tags::Tag:0x007fea390943b0 @tag_name="param", @text="an `Object` to compare this {Country} with.", @name="c", @types=["Object"], @object=#<yardoc method TZInfo::Country#eql?>>] but I can't seem to combine the two type information together. Thank you!

**Comment by lsegal** [comment]
@ericazhang17 I'm not sure I'm following this. To combine the two objects you would simply extract the `.types` attribute out of each of the two tags. It looks like you have all the data printed in your example, you just need to use the values in the way you want. Perhaps you can explain a bit about what you're trying to do?
