### ISSUE TITLE
@!scope doesn't work as expected

### ISSUE THREAD

**Issue by nikitabobko** [lsegal/yard#1303]
For such code:
```ruby
class Foo
  # @!scope class
  # @!method foo
  #   @return [String]
end
```

Run: `yardoc` and open generated documentation page in browser.
Expected: class `Foo` has **class** method called `foo`
Actual: `foo` is **instance** method

[Documentation](https://rubydoc.info/gems/yard/file/docs/Tags.md#scope) claims that `@!scope` "Modifies the current parsing scope (class or instance)"

`yardoc --version` prints:
yard 0.9.19

**Comment by lsegal** [comment]
The correct syntax is:

```ruby
class Foo
  # @!method foo
  #   @!scope class
  #   @return [String]
end
```

Note the indented scope directive. If you use indentation for the contents of the method directive, the directive will only use the indented block to generate its docstring contents, i.e., it will ignore any other toplevel tags / directives like `@!scope`. It will also ignore any plaintext documentation:

```ruby
class Foo
  # Some normal documentation for foo that will be ignored!
  # @!method foo
  #   @return [String]
end
```

A sidenote here: an easier way to specify this method would be to simply use `self.foo` as the method signature, which YARD can parse/understand:

```ruby
class Foo
  # @!method self.foo
  #   @return [String]
end
```

Hope that helps!

**Comment by nikitabobko** [comment]
Thanks! It solves the problem
