### ISSUE TITLE
organize yard menu (contain classes in folders like modules)

### ISSUE THREAD

**Issue by aseroff** [lsegal/yard#1306]
I'm trying to organize the left menu in my documentation. It appears that classes in modules will be nested into a folder, but classes in classes do not. I did notice the generated files are organized into directories (eg `docs/:namespace/Controller`), but these directories are not reflected in the organization of the menu. I'd be fine with using these namespaces, but ideally I'd quite enjoy a tag for customizing the placement of a class in the menu.

I've been browsing existing issues and googling for a solution, but for whatever reason I haven't found anything actionable. 

See also: https://stackoverflow.com/questions/55387583/grouping-classes-in-rails-app-documentation-with-yard

Please let me know if there's any other info I can provide about this request.

**Comment by MSP-Greg** [comment]
@aseroff 

The standard Class List in YARD is namespace based, and nothing is based on folder/file layout.

> but classes in classes do not

You might be mistaken, but I'm not sure what you mean by 'classes in classes'.

Anyway, you might check the file that AWS uses for creating their [Class List](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html):

https://github.com/aws/aws-sdk-ruby/blob/master/doc-src/templates/default/fulldoc/html/setup.rb

I've done similar things for the File List.

There are so many ways one might want to organize lists, it's difficult to come up with generic means of controlling it.

Loren may have more suggestions.

**Comment by aseroff** [comment]
Thanks for pointing me to the AWS docs, very helpful. I'll take a look at how they accomplished their custom menu folders and see if I can replicate it.

**Comment by aseroff** [comment]
Hello to anyone who might be seeing this in the future! I wrote a gist that boiled down my key takeaways from customizing YARD for my Rails application, and included a codesample that accomplishes what I sought out to do in customizing the side menu organization.

https://gist.github.com/aseroff/1535c132e01300680592a48d4c636106
