### ISSUE TITLE
Tag for thread safety?

### ISSUE THREAD

**Issue by ioquatix** [lsegal/yard#1311]
I'm interested in exploring options for thread safety and re-entrancy.

There are at least several tags that might make sense:

```
# @reentrant [note]
```

It would also be useful to document whether a method might call `Fiber.yield`. This is transitive, so a method which calls another method which can call `Fiber.yield` also has the same property.

```
# @reentrant yield
```

I don't really have a full proposal yet, but if you think this is something within the scope of yard, I will try to put together a PR.

**Comment by ioquatix** [comment]
Here is an example:

```
	# Force the process-level variant to be the specified value.
	# 
	# @reentrant Parallel modifications to `ENV` are undefined.
	# 
	# @example
	# 	Variant.force!(:testing)
	#
	def self.force!(value, environment = ENV, **overrides)
		# Clear any specific variants:
		environment.delete_if{|key, value| key.end_with?(SUFFIX)}
		
		# Set the specified variant:
		environment[KEY] = value.to_s
		
		overrides.each do |name, value|
			key = name.upcase.to_s + SUFFIX
			
			environment[key] = value.to_s
		end
		
		return environment
	end
```

**Comment by lsegal** [comment]
YARD allows for user defined tags without any code modifications at all, you can do this on the command line or via `.yardopts` via the following config line:

```sh
yard doc --tag reentrant:"Thread-safety Note"
```

Produces:

![image](https://user-images.githubusercontent.com/686/75828291-5acf4c80-5d60-11ea-9a6e-f3530c701b8d.png)

There are other ways to provide tags with types or names provided in `yard doc --help`.

I would suggest starting there. If they become extremely useful and heavily adopted, you could kick off a conversation about including them in the default library, but I would start that after it garners popularity by convention.

**Comment by ioquatix** [comment]
Did I make a mistake by using back tics as in `ENV`?

**Comment by lsegal** [comment]
No that has to do with markdown formatting which by default YARD does not use. `+ENV+` would be the RDoc way to specify that, or you could provide `-m markdown` to switch YARD to use Markdown formatting by default.
