### ISSUE TITLE
Avoid use of obsolete teletype HTML tag

### ISSUE THREAD

**Issue by floehopper** [lsegal/yard#1316]
There are [a number of places in YARD][1] which generate teletype (`<tt>`) HTML tags.

However, [the MDN web docs][2] say:

> **Obsolete**
> This feature is obsolete. Although it may still work in some browsers, its use is discouraged since it could be removed at any time. Try to avoid using it.

## Steps to reproduce

1. Visit https://www.rubydoc.info/gems/mocha/1.11.2/Mocha/Expectation#at_least-instance_method
2. Inspect the HTML that makes up the method signature (see HTML snippet below).
3. See that an HTML `<tt>` tag is used to wrap the return value of type `Expectation`.

## Actual Output

```html
<h3 class="signature first" id="at_least-instance_method">
  <a class="permalink" href="/gems/mocha/1.11.2/Mocha%2FExpectation:at_least">
    permalink
  </a>
  #<strong>at_least</strong>(minimum_number_of_times)
  ⇒ <tt>
    <span class="object_link">
      <a href="/gems/mocha/1.11.2/Mocha/Expectation" title="Mocha::Expectation (class)">
        Expectation
      </a>
    </span>
  </tt>
</h3>
```

## Expected Output

I think it would be preferable to use `<code>` tags instead of the `<tt>` tags:

```html
<h3 class="signature first" id="at_least-instance_method">
  <a class="permalink" href="/gems/mocha/1.11.2/Mocha%2FExpectation:at_least">
    permalink
  </a>
  #<strong>at_least</strong>(minimum_number_of_times)
  ⇒ <code>
    <span class="object_link">
      <a href="/gems/mocha/1.11.2/Mocha/Expectation" title="Mocha::Expectation (class)">
        Expectation
      </a>
    </span>
  </code>
</h3>
```

I'd be happy to create a pull request if you think this is a worthwhile change.

## Environment details:

* OS: MacOS v10.15.1
* Ruby version (`ruby -v`): `ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]`
* YARD version (`yard -v`): `yard 0.9.24`

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

[1]: https://github.com/lsegal/yard/search?l=HTML%2BERB&q=tt
[2]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tt

**Comment by lsegal** [comment]
Not sure why we would need to change this given that we manually style the css, so the "obsolete" point is moot. 

It's also worth noting that YARD doesn't generate most of the tt's; most are generated by tools like rdoc markup, and `<tt>` is the [official syntax to inline code](https://docs.ruby-lang.org/en/2.1.0/RDoc/Markup.html#class-RDoc::Markup-label-Bold-2C+Italic-2C+Typewriter+Text) in rdoc markup syntax. The only reason we use `<tt>` in a few places is to keep styling consistent with the above; we can change our few usages but tt's will likely continue to need styling and continue to show up on most doc pages.

**Comment by floehopper** [comment]
Fair enough - just noticed it in passing. Closing.
