### ISSUE TITLE
NoMethodError: undefined method `scope' for ...

### ISSUE THREAD

**Issue by mullermp** [lsegal/yard#1317]
In our documentation generation (for AWS SDK For Ruby), we're seeing these types of errors:

```
[error]: NoMethodError: undefined method `scope' for #<yardoc constant Aws::Waiters::Errors::UnexpectedError::MSG>
[error]: Stack trace:
	/Users/mamuller/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/yard-0.9.24/lib/yard/code_objects/base.rb:378:in `method_missing'
	/Users/mamuller/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/yard-0.9.24/templates/default/module/setup.rb:154:in `block (2 levels) in scopes'
	/Users/mamuller/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/yard-0.9.24/templates/default/module/setup.rb:154:in `select'
	/Users/mamuller/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/yard-0.9.24/templates/default/module/setup.rb:154:in `block in scopes'
	/Users/mamuller/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/yard-0.9.24/templates/default/module/setup.rb:153:in `each'
	/Users/mamuller/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/yard-0.9.24/templates/default/module/setup.rb:153:in `scopes'
```

We see these with GEM_VERSION: https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-s3/lib/aws-sdk-s3.rb#L69 as well as some anonymous constant objects (`#<YARD::CodeObjects::ConstantObject:0x00007f9d80e93de0>`)

I am hoping for some guidance for how to fix these. I couldn't find much on the internet and from looking at the `setup.rb` code. This line (https://github.com/lsegal/yard/blob/master/templates/default/module/setup.rb#L145) looks fishy but other than that I'm not sure.

## Steps to reproduce

Run `yardoc` on the AWS SDK For Ruby master branch.

## Environment details:

* OS: Mac OS
* Ruby version (`ruby -v`): 2.6.5
* YARD version (`yard -v`): 0.9.24

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by lsegal** [comment]
Pretty sure the problem is coming from custom templates in the aws-sdk-ruby repository, it looks like the overridden module template makes use of  `scopes` without a guard:

https://github.com/aws/aws-sdk-ruby/blob/b84cbbc75c983e5af1f8214c92214937d18a78b1/doc-src/templates/default/module/setup.rb#L15

Removing the `--template-path doc-src/templates` argument in `.yardopts` fixes the errors on my end.

**Comment by mullermp** [comment]
Ah! I was looking at the correct file but the wrong repo. :) Thanks for pointing me in the right direction. This code looks very similar to what's already provided... I'll carry forward that guarding check. Though it's possible that this overridden code isn't even necessary..

**Comment by mullermp** [comment]
This is part of an effort to fix up lots of yard errors.. https://github.com/aws/aws-sdk-ruby/pull/2275
