### ISSUE TITLE
Windows line endings commited - see lib/yard/handlers/c/base.rb

### ISSUE THREAD

**Issue by MSP-Greg** [lsegal/yard#1328]
Loren,

Happened to be working today, and saw https://github.com/lsegal/yard/commit/d531143681330669e594b3efd697cb134952860f, and the diff looked a little odd.  There's a EOL issue, ie CRLF vs LF.

Maybe add `.gitattributes`?
```
# Auto detect text files and perform LF normalization
* text eol=lf
```

**Comment by lsegal** [comment]
If you want to open a PR to fix this that would be great. I don't see this as an "issue" though.

**Comment by lsegal** [comment]
This should be improved with the above PR
