### ISSUE TITLE
[Question] How do I document the structure of a hash in a return value?

### ISSUE THREAD

**Issue by es50678** [lsegal/yard#1357]
How would I fully document a function like this?
```
def call_some_service()
  if error
    return { errors: { message: "some_message" } }
  end

  
    {
      trace_id: 123443
      trace_meta: { requested_at: 11111111 }
      trace_type: "SOME_TYPE" 
    }
end
```

I've tried 

```
  # Does stuff
  # @return [Hash]
  #   * :trace_id [String]
```

It works, just ends up looking kinda ugly and I wonder if theres a better way to do it.

**Comment by gam3** [comment]
My first choice would be to not return `Hash`s at all.  But return Objects that can be further documented.

```ruby
class ReturnGood
   # @return Integer
   def trace_id()
   end
   # @return Hash
   def trace_meta()
   end
   # @return String
   def trace_type()
   end
end
class ReturnBad
   # @return String
   def error_message
   end
end
# Does stuff
# @return [ReturnGood|ReturnBad]
def call_some_service()
end
```

My second choice would be to use examples:

```ruby
# Does stuff
# @return [Hash]
#       see examples
#
# @example Return success
#    {
#      trace_id: 123443
#      trace_meta: { requested_at: 11111111 }
#      trace_type: "SOME_TYPE"
#    }
# @example Return error
#    {
#      error: "SOME_ERROR"
#    }
def call_some_service()
end
```
My third suggestion is to add a template and a tag.

The script then becomes:
```ruby
# Does some stuff
# @myreturn
#     {
#          trace_id: [Number],
#          trace_meta: { requested_at: [Number] },
#          trace_type: [String],
#     }
# @myreturn
#     {
#          error: { message: [String] }
#     }
def call_some_service_3()
end
```
The tag is added with:
```ruby
#./myreturn.rb
YARD::Tags::Library.define_tag("Returns",
```
then the template need 2 files:
```ruby
# default/tags/html/setup.rb
def init
  tags = Tags::Library.visible_tags - [:abstract, :deprecated, :note, :todo]
  create_tag_methods(tags - [ :myreturn ])
  sections :index, tags.map {|t| t.to_s.tr('.', '_').to_sym }
  sections.any(:overload).push(T('docstring'))
end
```
and the template file
```erb
<% if object.has_tag?(:myreturn) %>
  <div class="examples">
    <p class="tag_title">Returns:</p>
    <% object.tags(:myreturn).each do |tag| %>
      <% if !tag.name.nil? %>
      <% unless tag.name.empty? %>
        <p class="example_title"><%= htmlify_line(tag.name) %></p>
      <% end %>
      <% end %>
      <pre class="example code"><code><%= html_syntax_highlight(tag.text) %></code></pre>
    <% end %>
  </div>
<% end %>
```

**Comment by lsegal** [comment]
Fully agree with @gam3. The best thing you can do is not return bare hashes if you can avoid it. Any kind of method in which the returned hash keys have specific meaning is always better off represented as an object. The nice thing is that you can easily use `Struct` to convert hash returns into nice objects:

```ruby
# @!attribute trace_id
#   @return [Fixnum]
# @!attribute trace_meta
#   @return [TraceMeta]
# @!attribute trace_type
#   @return [String]
class Trace < Struct(:trace_id, :trace_meta, :trace_type); end

# @!attribute requested_at
#   @return [Fixnum]
class TraceMeta < Struct(:requested_at); end

class APIError < Struct(:message); end

# @return [Trace] on success returns a trace from server
# @return [{:errors => APIError}] on failure returns a standard API Error
def call_some_service
  return { errors: APIError(message: 'error') } if error

  Trace(
    trace_id: 1,
    trace_meta: TraceMeta(requested_at: 111),
    trace_type: 'SOME_TYPE'
  )
end
```

Generates:

![image](https://user-images.githubusercontent.com/686/97096258-54a71c80-161e-11eb-8f2b-0ca809f06b36.png)

![image](https://user-images.githubusercontent.com/686/97096259-5bce2a80-161e-11eb-9dd2-c5ad97db8f85.png)

If you absolutely must return hashes, you can see the docs used for `#call_some_service` as an example of how you can declare this. YARD isn't too strict about what goes in the type specifier, meaning you _can_ use hash syntax to declare your type. Of course, the more keys you got, the harder it will be to parse.

Another formatting would be to return a bare `Hash` and use markup to define the return keys:

```ruby
# @return [Trace] on success returns a trace from server
#   * `:trace_id` [Fixnum] - the trace id
#   * `:trace_meta` [Hash] - metadata about the trace
#     * `:requested_at` [DateTime] - when the trace was requested
#   * `:trace_type` [String] - the trace type
# @return [Hash] on failure returns a standard API Error
#   * `:errors` [Hash] - the errors object
#     * `:message` [String] - the error message
def call_some_service
  return { errors: { message: 'error' } } if error

  {
    trace_id: 1,
    trace_meta: TraceMeta(requested_at: 111),
    trace_type: 'SOME_TYPE'
  }
end
```

![image](https://user-images.githubusercontent.com/686/97096297-021a3000-161f-11eb-8b1a-0706f43db55a.png)

It is now of course completely up to you to define the formatting, which can be cumbersome, and YARD will not have any context for the keys you use (which means any tooling that uses YARD will not either).

**Comment by es50678** [comment]
Thank you both so much! Very helpful answers. Closing this but I hope others find it and use your suggestions.

**Comment by marlinpierce** [comment]
I agree with the software design advice.  There is a noob mistake of returning multiple values in a hash which especially should be avoided.

However, if you are documenting method which calls a web service that returns JSON and you want to document the keys returned, then there is a legitimate use case for documenting keys of returned hashes.
