### ISSUE TITLE
Ideas on how to label an inherited method

### ISSUE THREAD

**Issue by jspawar** [lsegal/yard#1394]
Not really an issue or a bug, but was hoping to start some sort of discussion and assumed this would be the best way to do so? If not of course, feel free to let me know and can close this + move it somewhere else.

Was looking to see if folks had any ideas on how to document/label a specific case. For some background context, I (among many others) am using Solargraph in development which in turn often relies on YARD for assistance in determining types of things. Don't know if that's entirely relevant to the actual question(s), but probably worth sharing.

Situation I'm in: I have multiple different classes which inherit/extend from some module/mixin as such:

```ruby
class MyDocument
  include Mongoid::Document
  ...
```

This class most often instantiates objects via inherited class methods such as say `create!` or `find`. I can annotate the class with something like say `@!parse extend Mongoid::Findable` so that `find` is recognized. The output doc correctlys treats the return type as `Mongoid::Document` since that's what the doc for `Mongoid::Findable` says `find` returns; however, I'm wondering if I could somehow coerce it into saying it returns an instance of `MyDocument` instead?

I'm fairly new to YARD; however, it looks like perhaps the `@!method` directive would be useful. Problem I see there is that I'm not sure how I would handle dynamic methods such as `create!` which validly accept varying keyword args.

Thanks :)

**Comment by jspawar** [comment]
Er seems I've scared folks off, so perhaps I can rephrase to something simpler and perhaps actually a known-answered yes-no question:

Is there any way to dynamically reference the type of the class that is being annotated, i.e. can I do something like:

```ruby
class MyDocument
  # a function
  #
  # @return [Self] an instance of type 'MyDocument'
  def a_function; end
end
```

Basically wondering if I could do something to solve my particular problem like:

```ruby
class MyDocument1
  # @!parse extend MongoidDocumentClassMethods
  ...
end

class MyDocumentN
  # @!parse extend MongoidDocumentClassMethods
  ...
end

class MongoidDocumentClassMethods
  # Creates and persists new document
  #
  # @return [Self] an instance representing the persisted document
  def create!(**args); end
  ...
end
```

**Comment by lsegal** [comment]
> Is there any way to dynamically reference the type of the class that is being annotated, i.e. can I do something like:

`self` is the "recommended convention" for referencing the method object's class in this case. The question is what are you looking to accomplish with the type annotation? Usually the type specifier of self is a no-op when it comes to HTML generation, since linking to the same document isn't usually that meaningful.

If the issue is about integration with solargraph, then this should probably be something reported to that project, i.e., a request to support the self keyword in type annotations.

**Comment by jspawar** [comment]
Thank you for clarifying @lsegal. This is indeed for integration with Solargraph, so will certainly discuss `self` support with them.
