### ISSUE TITLE
`@!scope class` behaviour not following docs example for "set of methods" scope

### ISSUE THREAD

**Issue by qortex** [lsegal/yard#1411]
Docs [here](https://www.rubydoc.info/gems/yard/file/docs/Tags.md) states that this should mark `method1` & `method2` as class methods:
```ruby
# @!scope class

# Documentation for method1
def method1; end

# Documentation for method2
def method2; end
```

In my experience, this doesn't work and `@!scope class` must be repeated on all methods definitions

## Steps to reproduce

Repro:

```ruby
class Test
  def test_instance; end

  # @!scope class

  # method1 doc
  def method1; end

  # method2 doc
  def method2; end
end

class Test2
  def test_instance; end

  # @!scope class

  def method1; end

  def method2; end
end

class Test3
  def test_instance; end

  # method1 doc
  # @!scope class
  def method1; end

  # method2 doc
  # @!scope class
  def method2; end
end
```

## Actual Output

![image](https://user-images.githubusercontent.com/37897072/139021513-77b164d4-ad2e-4ee7-b0ee-dfb7913a5a27.png)

![image](https://user-images.githubusercontent.com/37897072/139021584-aff4cc29-90ed-460e-8180-e9cf8e91e1da.png)

![image](https://user-images.githubusercontent.com/37897072/139021646-34d62be6-c6cc-4c4e-8787-9ea1ec693cbe.png)

## Expected Output

I would expect `Test` & `Test2` to behave the same, with `Test2` methods having no doc.

I would expect `Test` & `Test2` to have `method1` & `method2` as class methods.

I would expect `Test` & `Test3` to have the same doc.

## Environment details:

- OS: Fedora 34
- Ruby version (`ruby -v`): ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]
- YARD version (`yard -v`): yard 0.9.26

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/main/CONTRIBUTING.md

**Comment by lsegal** [comment]
Thanks for the report! This is fixed in the above commit and will be in the next release.
