### ISSUE TITLE
Cannot resolve link to `<code>`

### ISSUE THREAD

**Issue by dgdavid** [lsegal/yard#1422]
YARD complains about resolving links containing [`<code>` tags that comes from backticks](https://daringfireball.net/projects/markdown/syntax#code) in a markdown file when using Ruby 3

> [warn]: In file `TEST.md':4: **Cannot resolve link to  \<code\>code\</code\>**\<a from text:
>	...{\<code\>code\</code\>\<a href="https://daringfireball.net/projects/markdown/syntax#code">}...

## Steps to reproduce

* Create a markdown file that contains a link using backticks. E.g., 
  
  ```markdown
  # Testing links using `code`

  Use a [`code`](https://daringfireball.net/projects/markdown/syntax#code) inside the link and 
  see what happens when running yardoc.
   ```
* Try to generate the documentation running the command `yardoc -o documentation - TEST.md`

## Actual Output

> ➜ ruby --version
>     ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux-gnu]
> ➜ ~/.gem/ruby/3.0.0/bin/yardoc --version
>     yard 0.9.27 
> 
> ➜ ~/.gem/ruby/3.0.0/bin/yardoc --debug -o documentation - TEST.md

```
[debug]: Parsing ["{lib,app}/**/*.rb", "ext/**/*.{c,cc,cxx,cpp,rb}"] with `ruby` parser
[debug]: Serializing to .yardoc/objects/root.dat
[debug]: Re-generating object ...
[debug]: Generating asset js/jquery.js
[debug]: Serializing to documentation/js/jquery.js
[debug]: Generating asset js/app.js
[debug]: Serializing to documentation/js/app.js
[debug]: Generating asset js/full_list.js
[debug]: Serializing to documentation/js/full_list.js
[debug]: Generating asset css/style.css
[debug]: Serializing to documentation/css/style.css
[debug]: Generating asset css/common.css
[debug]: Serializing to documentation/css/common.css
[debug]: Generating asset css/full_list.css
[debug]: Serializing to documentation/css/full_list.css
[debug]: Generating asset class_list.html
[debug]: Serializing to documentation/class_list.html
[debug]: Generating asset method_list.html
[debug]: Serializing to documentation/method_list.html
[debug]: Generating asset file_list.html
[debug]: Serializing to documentation/file_list.html
[debug]: Generating asset frames.html
[debug]: Serializing to documentation/frames.html
[debug]: Serializing to documentation/index.html
[debug]: Serializing to documentation/_index.html
[warn]: In file `TEST.md':4: Cannot resolve link to <code>code</code><a from text:
	...{<code>code</code><a href="https://daringfireball.net/projects/markdown/syntax#code">}...
[debug]: Serializing to documentation/file.TEST.html
[debug]: Serializing to documentation/top-level-namespace.html
Files:           0
Modules:         0 (    0 undocumented)
Classes:         0 (    0 undocumented)
Constants:       0 (    0 undocumented)
Attributes:      0 (    0 undocumented)
Methods:         0 (    0 undocumented)
 100.00% documented
```

## Expected Output

> ➜ ruby --version
>     ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-linux]
> ➜ /home/dei/.gem/ruby/2.7.0/bin/yardoc --version
>     yard 0.9.27 
> 
> ➜ ~/.gem/ruby/2.7.0/bin/yardoc --debug -o documentation - TEST.md

```
[debug]: Parsing ["{lib,app}/**/*.rb", "ext/**/*.{c,cc,cxx,cpp,rb}"] with `ruby` parser
[debug]: Serializing to .yardoc/objects/root.dat
[debug]: Re-generating object ...
[debug]: Generating asset js/jquery.js
[debug]: Serializing to documentation/js/jquery.js
[debug]: Generating asset js/app.js
[debug]: Serializing to documentation/js/app.js
[debug]: Generating asset js/full_list.js
[debug]: Serializing to documentation/js/full_list.js
[debug]: Generating asset css/style.css
[debug]: Serializing to documentation/css/style.css
[debug]: Generating asset css/common.css
[debug]: Serializing to documentation/css/common.css
[debug]: Generating asset css/full_list.css
[debug]: Serializing to documentation/css/full_list.css
[debug]: Generating asset class_list.html
[debug]: Serializing to documentation/class_list.html
[debug]: Generating asset method_list.html
[debug]: Serializing to documentation/method_list.html
[debug]: Generating asset file_list.html
[debug]: Serializing to documentation/file_list.html
[debug]: Generating asset frames.html
[debug]: Serializing to documentation/frames.html
[debug]: Serializing to documentation/index.html
[debug]: Serializing to documentation/_index.html
[debug]: Serializing to documentation/file.TEST.html
[debug]: Serializing to documentation/top-level-namespace.html
Files:           0
Modules:         0 (    0 undocumented)
Classes:         0 (    0 undocumented)
Constants:       0 (    0 undocumented)
Attributes:      0 (    0 undocumented)
Methods:         0 (    0 undocumented)
 100.00% documented
```

## Environment details:

OS: openSUSE Tumbleweed. For Ruby and YARD versions, please see _actual_ and _expected_ output sections.

---

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/main/CONTRIBUTING.md

**Comment by dgdavid** [comment]
Note: using Ruby 3.1 the result is exactly the same than the _Actual output_ above.

> > ➜ ruby --version
>     ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-linux]
> ➜ ~/.gem/ruby/3.1.0/bin/yardoc --version
>     yard 0.9.27

**Comment by lsegal** [comment]
This might be related to #1410

**Comment by dgdavid** [comment]
Thanks!

I came there yesterday and I even tested using [`--markup-provider commonmarker`](https://github.com/lsegal/yard/pull/1388) and it worked… but it requires adding more dependencies. 

That's why I opened the issue, to see if there is a better solution without adding dependencies.

**Comment by lslezak** [comment]
> This might be related to #1410

Yes, it might be related to curly braces.

The `RDoc::Markup#convert` called from [templates/helpers/markup/rdoc_markup.rb:54](https://github.com/lsegal/yard/blob/main/lib/yard/templates/helpers/markup/rdoc_markup.rb#L54) returns in Ruby 3.1:
```
{<code>code</code><a href=\"http://example.com\">}</a>
```
while in Ruby 2.7.5 it returns just:
```
<a href=\"http://example.com\">code</a>
```
when using simple input:

    [`code`](http://example.com)

**Comment by lsegal** [comment]
> Thanks!
> 
> I came there yesterday and I even tested using [`--markup-provider commonmarker`](https://github.com/lsegal/yard/pull/1388) and it worked… but it requires adding more dependencies.
> 
> That's why I opened the issue, to see if there is a better solution without adding dependencies.

I believe the fix would have to come from fixing RDoc to generate clean markup. It's unclear _exactly_ what the issue is in this case, but at the very least it should attempt to be compatible with all other markdown library implementations, none of which have this issue.

It might be worth noting that you can easily workaround this by avoiding the backtick syntax inside links, which generally isn't recommended anyway; styling a link should be the product of your generated templates, not your markup, and you should focus on generating clean semantic links. A method or class name is not, on its own, "code", so the idea of doing something like 

```
[`MyClass`](link here)
```

Is not recommended behavior. Note that YARD does not style any `{MyClass}` object style links with fixed-width style fonts for this same reason, thus doing so on regular links would actually be out of place for the standard YARD template.

**Comment by dgdavid** [comment]
> 
> It might be worth noting that you can easily workaround this by avoiding the backtick syntax inside links, which generally isn't recommended anyway; styling a link should be the product of your generated templates, not your markup, and you should focus on generating clean semantic links. A method or class name is not, on its own, "code", so the idea of doing something like
> 
> ```
> [`MyClass`](link here)
> ```
> 
> Is not recommended behavior. Note that YARD does not style any `{MyClass}` object style links with fixed-width style fonts for this same reason, thus doing so on regular links would actually be out of place for the standard YARD template.

Good point! I'll try to not use `backticks` in links from now on. 

Nevertheless, think in more realistic use than my above example, such as a user trying to highlight? a specific word in a Github issue title. It actually works, see https://github.com/yast/yast-docker/issues and https://github.com/yast/yast-docker/issues/31. 

I'm not saying that it is right, since somehow you convinced me that it is not :wink: but maybe there are some valid use cases where a link can contain a `piece of code`. Don't know.

Thank you a ton for your insights here :smiley:
