### ISSUE TITLE
Flatened lists on markdown yri

### ISSUE THREAD

**Issue by 3ynm** [lsegal/yard#1423]
## Steps to reproduce

1. Create a `test.rb` file.

```ruby
# Bla bla.
#
# - a
# - b
# - c
module TestModule; end
```

2. Build docs

```
yard --markup markdown test.rb
```

3. Look on yri
```
yri TestModule
```

## Actual Output

```
----------------------------------------------------- Module: TestModule

    Bla bla.

    - a - b - c



------------------------------------------------------------------------
```

## Expected Output

```
----------------------------------------------------- Module: TestModule

    Bla bla.

    - a
    - b
    - c



------------------------------------------------------------------------
```

## Environment details:

- OS: ArchLinux
- Ruby version (`ruby -v`): ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
- YARD version (`yard -v`): yard 0.9.27

**Comment by lsegal** [comment]
YARD passes all markup to the markdown (or markup) processing library on your system. This is likely a configuration issue. Note that YARD does not use markdown processing by default in .rb documentation, this must be set with `-m markdown`.

If this still doesn't work you may want to look at your markdown library.

**Comment by hacktivista** [comment]
I observe the same behavior with RDoc

![image](https://user-images.githubusercontent.com/5282749/193306106-1221382f-8309-48b8-a88e-3d095c46d8eb.png)

**Comment by lsegal** [comment]
Marking this as closed since it is a third-party / configuration issue.
