### ISSUE TITLE
Additional files included when generating docs.

### ISSUE THREAD

**Issue by jacob-carlborg** [lsegal/yard#1429]
If I generate documentation and specify a single file, other files are included anyway.

## Steps to reproduce

1. Run the following commands:
```
cat << EOF >> foo.rb
# Foobar
# * asd
class Foo
end
EOF

cat << EOF >> README.md
# Foo
EOF

yard doc --no-save  foo.rb
```
2. Open the generated `doc/index.html` in the browser

## Actual Output

The content of the `README.md` file is included in the output.

## Expected Output

I expect the content of the `foo.rb` file, **without** the content of the `README.md` file.

If this is the default behavior, it would at least be nice with a flag to tell Yard to not include additional files.

## Environment details:

- OS: macOS 12.0.1
- Ruby version (`ruby -v`): ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]
- YARD version (`yard -v`): yard 0.9.27

**Comment by lsegal** [comment]
> If this is the default behavior, it would at least be nice with a flag to tell Yard to not include additional files

This is the default behavior. YARD will always include a README file in generated output if one exists. This applies to all default templates. This issue has been discussed a few times, but most recently in #837, which has some information on how you could "workaround" the issue. tl;dr the expectation is to provide some form of README, though you might want to point to a different file from the standard README.md via `--readme`, which is documented in `yard doc --help`.

**Comment by jacob-carlborg** [comment]
I'm using a custom template anyway so I can remove it from the template. But I think the behavior is a bit unintuitive.
