### ISSUE TITLE
How can I document a C++ extension?

### ISSUE THREAD

**Issue by Speak2Erase** [lsegal/yard#1436]
I've seen a couple issues asking a similar question, namely #1281, but none of them really have a clear and concise answer.
To be clear, I am not looking to document the actual C++ code itself, I'd just like to document the ruby functions it exposes, such as the arguments, return values, etc.
I'm not sure the best way about this short of using dummy files, which is a fairly brutish way of doing things.

**Comment by lsegal** [comment]
The answers in #1281 are basically one of two options:

1. Document your API using CRuby methodologies in your C/C++ files, or,
2. Document your API in Ruby code that is either a wrapper around the C/C++ implementation or simply unused header style files that define the API in said Ruby code.

You have to pick one or the other, there's no other path. You seem to understand that both options exist, but you will have to choose: either choose the "conventional" but worse documented path of writing your documentation alongside your CRuby modules, or choose the more obtuse but much better supported path of documenting plain old Ruby code.

I believe the issue you listed has more than enough references, discussion, and instruction to go off of for either method; if I was to explain it here it would probably become fairly repetitive. I recommend reading through the thread for the correct links and resources. If you have specific questions, they are probably better had in that issue.

**Comment by Speak2Erase** [comment]
Alright, thank you for the quick response.
