### ISSUE TITLE
[Feature request / Enhancement] Support for subsections/booklets - to read the documentation like a book. Make documentation great again!

### ISSUE THREAD

**Issue by rubyFeedback** [lsegal/yard#1450]
Sorry for the catchy title but otherwise nobody reads this. :P

I have written quite some documentation for some of my larger projects
such as:

https://www.rubydoc.info/gems/bioroebe/0.11.24

Real people even read it. About two months ago a japanese aspiring
PhD read it and he said it took him a long time to read it all. :P

I actually never imagined anyone would bother to want to read it.
I write things down so I don't forget, and that I can refer to it
as the main specification. So if code misbehaves, usually it is
due to the code, if the documentation is correct.

Now ... for very long documents, yard is a bit cumbersome since
it is all a single page.

Some projects have very long .md files and that is ok.

But would it be possible to have an ADDITIONAL way to showcase
documentation? Something more like a booklet-form where you
read individual chapters or booklet-thingies on a few topics.
Perhaps even with a search-able interface to jump to chapters
and what not.

I think quite some users may appreciate this if designed well.

I am not proposing every detail here as this may take quite
some time away, so I am actually more interested in whether
yard may be open for additional ways to DISPLAY its content.

I remember the old iframes approach and ruby has come a
long way from that, but if you look at python, there is some 
online way to look at documentation of python eggs (or
whatever the name was). And these are visually very
pleasing to read, more so than yard, IMO.

This is not a complaint about yard per se, mind you - I think
yard is doing a good, solid job. But I'd like to have the 
option for more fine-tuned control in a book-like fashion if that
is possible.

IF it already is then perhaps the links to it could be
stronger so that we can find it more easily, including demo-pages
to showcase the results.

At any rate thank you for reading and perhaps considering, or
if possible comment as a pro/con view about it.

**Comment by lsegal** [comment]
YARD has a "guide" template and YARD itself actually has a special [`.yardopts_guide` options file](https://github.com/lsegal/yard/blob/main/.yardopts_guide) for generating in this form:

```sh
cd path/to/yard
yard --yardopts .yardopts_guide
```

![image](https://user-images.githubusercontent.com/686/188285230-665e0d9f-63f0-492b-80f6-7d95799083dd.png)

The longer answer is you would use the `guide` template with extra files as defined normally: `yard -t guide -- FILE1.md FILE2.md FILE3.md ...`

This template could probably be better advertised! It would be even nicer to set some conventional .yardopts filename format that [rubydoc.info](https://github.com/docmeta/rubydoc.info) could parse and link to as alternate documentation.

Hope this helps!

**Comment by lsegal** [comment]
PS: this format requires zero code and could be used in a source tree that had nothing but markdown files as a basic "readthedocs" style generation tool for plain old prose:

```sh
cd path/to/anymarkupdir
yard -t guide -- *.md
```

Of course the _order_ of files will matter for indexing, so you would likely want to list out all your files directly, unless you were diligent about lexically sorting the filenames (i.e. `01_intro.md`, `02_installing.md`, etc)

**Comment by lsegal** [comment]
Closing since this is in many ways already fairly supported. If there are specific needs, please open a new issue or pull request.
