### ISSUE TITLE
Documentation at rubydoc.info - some gems do not have documentation

### ISSUE THREAD

**Issue by rubyFeedback** [lsegal/yard#1476]
Not sure if I file this at the wrong place, but I assume yard may be related to the generated documentation.

Some of my gems don't have documentation. For instance:

"Sorry, but we couldn't find the page /gems/roebe/0.5.143 in the roebe gem. Are you sure that class, method, or file exists?"

So that recent upload does not. But the gems before that do have the documentation, at rubygems.org. So I am confused.

Another gem never has documentation anymore (called games_paradise) but a year ago it had. To me this is super-confusing. Sometimes it seems as if it takes time to generate the documentation and at a later time the documentation may suddenly be there; at other times it seems to never have any documentation.

I am not sure who or what is to blame here, perhaps rubygems. Or a combination of this.

Would it be possible for yard to provide more accurate guidelines, documentation as well as have a look at the responsible code, so we can more clearly identify where the problem is? If rubygems.org is to be blamed then this is fine - then this can be filed at their issue tracker. But I wanted to make sure I understand what causes this issue. The ideal way for me would actually be to autogenerate the documentation **before** I do a gem upload - that way nobody else has to render anything and I can do this locally, via scripts, to autogenerate the documentation before doing the gem upload hopefully. That should avoid one extra step that others may have to do - I am fine with that step. I am using lots of ruby scripts to automate things anyway.

Right now the unfortunate situation is that some of my gems have no documentation, so users can not really use it without that documentation. Hopefully I was able to explain the problem domain at hand. Thank you for reading - any pointers would be helpful!

**Comment by lsegal** [comment]
rubydoc.info has a `Help` link and [Knowledgebase](https://rubydoc.tenderapp.com/) on site for such support. Please search for similar issues or post there.

Note that this type of error is not usually an issue with your gem's documentation.
