### ISSUE TITLE
Change webrick version spec from `~> 1.7.0` to `~> 1.7`

### ISSUE THREAD

**Issue by DannyBen** [lsegal/yard#1483]
I believe this line (which exists in the published gem):

https://github.com/lsegal/yard/blob/e21c9323bba88c841a917d0531281b90f27f2378/yard.gemspec#L24

Should be loosened to:

```ruby
s.add_runtime_dependency 'webrick', '~> 1.7'
```

This will allow webrick 1.x, which is unlikely to break compatibility, and 1.7.x is already outdated.

I would have opened a pull request, but I do not see this runtime dependency in [the main branch's gemspec](https://github.com/lsegal/yard/blob/main/yard.gemspec).

**Comment by rgarver** [comment]
@DannyBen I just did a little digging and it looks like in the most recent code the webrick dependency has been removed. I think this will be solved once a new version is cut.

**Comment by rgarver** [comment]
I'll add this commit reference for others to connect the dots: 

https://github.com/lsegal/yard/commit/995cd765f0354ebfd8f20b93a31eca21feb91ebe#diff-2a7cc5899379938cbfa22112e7e0a28978a2bef7e21100004806d34b9115c8b5

**Comment by DannyBen** [comment]
Excellent thanks.

I will close this issue then.
