### ISSUE TITLE
Undocumented "phantom" method

### ISSUE THREAD

**Issue by istrasci** [lsegal/yard#1500]
`yard stats --list-undoc` is showing a method is undocumented, but that method doesn't exist.

## Steps to reproduce

Not sure how reproducible this is, but here's my setup:

I have a Rails model named `DocumentData` that has a column/property `:data_content`.  I have 2 scopes defined on specific values of it, a length validation on it, and several logic methods concerning it.

```ruby
# app/models/document_data.rb
class DocumentData < ApplicationRecord
  scope :blank_data, -> { where(data_content: nil) }
  scope :non_blank_data, -> { where.not(data_content: nil) }

  validates :data_content, length: { maximum: 2000 }

  # other model stuff
end
```

## Actual Output

```bash
$ yard stats --list-undoc

...other files...

(in file: app/models/document_data.rb)
DocumentData#data_content
```

## Expected Output

I expected that file not to be in the output of undocumented files.

## Environment details:

- OS: Ubuntu 20.04.6 LTS (Focal Fossa)
- Ruby version (`ruby -v`): 3.2.2
- YARD version (`yard -v`): 0.9.34
- Relevant software dependency/versions:
  - Rails version: 7.0.4.3

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/main/CONTRIBUTING.md

**Comment by lsegal** [comment]
I cannot reproduce this with the information provided.

Please report the results of `yard stats --debug` and the listing of `.yardopts` if present / any plugins that may be used here. tl;dr it seems like you may be using a YARD plugin that is parsing this method, `yard-rails` perhaps?

**Comment by istrasci** [comment]
It looks like an issue with [yard-activerecord](https://github.com/theodorton/yard-activerecord).  I'll close this.
