### ISSUE TITLE
Global search - how it works?

### ISSUE THREAD

**Issue by edenisn** [lsegal/yard#1530]
Hi! I dont understand how global search works. Entered any text information into search element on the page, but get nothing. Can you pls explain what should I do to make it works? Thanks!
<img width="1994" alt="Снимок экрана 2024-01-20 в 13 56 15" src="https://github.com/lsegal/yard/assets/791349/3dd5459c-97d2-467d-b98e-91f5c9ca551e">

**Comment by lsegal** [comment]
YARD search is not full text search, it only looks up the names of source objects (modules, classes, methods, etc). "Some data" is unlikely the name of one of those.

Hope that helps.

**Comment by edenisn** [comment]
Thanks for the fast answer
