### ISSUE TITLE
difference in behavior, MacOS vs Linux/CI

### ISSUE THREAD

**Issue by jjb** [lsegal/yard#1543]
I have these in my readme.md:

locally (MacOS) my build has no errors

on CI (linux ubuntu)

```
Generating doc/file.README.html⢿ Generating doc/file.README.html.[warn]: In file `README.md':275: Cannot resolve link to the from text:
	...{the <code>foo-</code> bar}...
```

the offending code is:

```markdown
[the `foo-` bar](https://example.com/Path#fragment)
```

the yard and ruby versions are the same in both places

what could cause the difference in behavior?

**Comment by jjb** [comment]
MacOS has a case-insensitive file system, I wonder if that's somehow the cause 😆

**Comment by lsegal** [comment]
This looks related to #1410

**Comment by jjb** [comment]
thanks! added some docs here https://github.com/lsegal/yard/pull/1544
