### ISSUE TITLE
How to document methods included from separate files?

### ISSUE THREAD

**Issue by akunszt** [lsegal/yard#1592]
## Steps to reproduce

I have something like this in my code.
```ruby
class MyClass

    def method
        @functions = Module.new
        @functions.module_eval( File.read( "otherfile.rb" ) )
    end

end
```
And in the otherfile.rb.
```ruby
def other_method
end
```
I have multiple files and methods. The main reason I do this is to avoid any naming collisions. This is just the gist, it is more complicated.

My issue is that I want to document all the methods under `MyClass::X` or `Anything::Y` but YARD generates the documentation under the "Top Level Namespace".

I tried to add `#@!parse module Anything::Y` to the beginning and `#@!parse and` at the end of the file but it didn't work. I assume that @!parse has to see the full code.

Is there a way to achieve this? Did I miss something in the documentation?

## Actual Output

Methods are put under the Top Level Namespace.

## Expected Output

Methods are put under the specified namespace.

## Environment details:

- OS: Gentoo Linux
- Ruby version (`ruby -v`): ruby 3.2.4 (2024-04-23 revision af471c0e01) [x86_64-linux]
- YARD version (`yard -v`): yard 0.9.37

**Comment by chriscz** [comment]
Have you tried doing `# @!parse include Anything::Y`, this seems more like what you want. When using `@!parse` it's as if the code is literally written where the directive is. 

```
class MyClass
  # @!parse include Anything::Y
  def method
      @functions = Module.new
      @functions.module_eval( File.read( "otherfile.rb" ) )
  end
end
```

To quote the docs:

> Parses a block of code as if it were present in the source file at that location. This directive is useful if a class has dynamic meta-programmed behaviour that cannot be recognized by YARD.

https://rubydoc.info/gems/yard/file/docs/Tags.md#parse

**Comment by chriscz** [comment]
I might be misunderstanding what exactly you want here as your explanation isn't completely clear to me.

Do you want the documentation on `@functions`?

**Comment by akunszt** [comment]
First of all thanks for your time!

Let me explain a bit more. I have a very-very simple language parser which supports to fetch functions from different sources. I have a class let's call it `MyLang::Function` which reads files from different locations and loads the methods found in them into an unnamed Module object, so the methods cannot cause any naming collision with the "engine"/parser.
The `MyLang::Function` knows where to look, how to fetch file content and later how to call those functions.

My colleagues are writing only methods in those files without declaring any classes or modules. They can see it as top level functions but during runtime those will be methods of a Module.

This makes them easier to concentrate only the relevant parts and when I refactor the engine side they don't even notice.

So for your questions.
1. Yes, I would like to document the methods in that module but as the module does not have a "name" then the methods are listed under the "Top level namespace". It is not a very intuitive place to look for (and we have other top level functions from different sources). This is why I would like to "embrace" those functions in a module in the documentation, but only in the documentation.
2. The filename - and location - can vary. Now we have few dozens files already.

If I failed to explain my use case properly - sorry, as you can see English it not my mother tongue - then I can put together a small test code.
