### ISSUE TITLE
No Index page

### ISSUE THREAD

**Issue by trans** [lsegal/yard#316]
Using YARD on new project and discovered I could not navigate to the index page. To see this go to:

http://rubyworks.github.com/erbside/docs/api/Erbside.html

And click on 'Index' up in the upper left corner.

(Ruby 1.8.7 and Yard 0.6.7)

**Comment by sfcgeorge** [comment]
I've had the same issue and it is indeed Github Pages's fault not liking `_index.html`. But would it not make more sense to rename it `contents.html` anyway? I used a horrible bash sed script to rename throughout.
