### ISSUE TITLE
Recognize Github Flavored Markdown

### ISSUE THREAD

**Issue by bytesource** [lsegal/yard#404]
In my README files I use features from Github Flavored Markdown, such as code highlighting and awareness for underscores inside a word, but  YARD does not recognize them.

Adding [github-markup](https://github.com/github/markup) as a markup provider to .yardopts

`-M github-markup`

resulted in an error:

```

[error]: Invalid markup type 'markdown' or markup provider (github-markup) is not registered.

yard-0.7.3/lib/yard/templates/helpers/html_helper.rb:70:in `html_markup_markdown': undefined method `new' for nil:NilClass (NoMethodError)
[...]

```

Is there a way to make YARD parse Github Flavored Markdown? If not, I would suggest this as a new feature, especially because services like RubyDoc.info fetch their data from Github repos.

Stefan

**Comment by burningTyger** [comment]
Yikes, this is not up to date, is it?
