### ISSUE TITLE
Please add something like RDoc's :method: and :singleton-method:

### ISSUE THREAD

**Issue by benedikt** [lsegal/yard#460]
I'd really like to switch the documentation of benedikt/mongoid-tree from RDoc to YARD, but I'm missing the ability to add documentation for implicitly generated methods.

RDoc has the `:method:` and `:singleton-method:` directives to add documentation for those methods. (http://rdoc.rubyforge.org/RDoc/Parser/Ruby.html) It would be great to have something similar in YARD.

I'm aware of the `@method` directive, but it only works when preceding a DSL macro which isn't feasible for my use case.

... or am I missing something?

Thanks! :-)

**Comment by thomthom** [comment]
Is there something similar for C code? Adding `Document-method:` doesn't appear to work without an `rb_define_method`.
