### ISSUE TITLE
`!!!lang` code blocks should set the lang in <pre>'s class.

### ISSUE THREAD

**Issue by dominikh** [lsegal/yard#478]
Right now, there is no way to tell which language a code block contains after it has been processed by YARD. This makes it hard to postprocess the output.

Methods in `YARD::Templates::Helpers::HtmlHelper`  that might needs adjustment:
- #html_syntax_highlight
- #htmlify

**Comment by franklinyu** [comment]
What is this about? Is this about hinting about the syntax of a code block in RDoc? So

```rdoc
!!!bash

    apt-get update
```

in RDoc is equivalent to

    ```bash
    apt-get update
    ```

in Markdown?

**Comment by lsegal** [comment]
@franklinyu Indeed, except the bang needs to be indented at the same level as your markup:

```
    !!!bash
    apt-get update
```
