### ISSUE TITLE
Support nested options?

### ISSUE THREAD

**Issue by skipchris** [lsegal/yard#622]
It would be awesome if @option tags supported nested hashes. I'm writing a wrapper for an API which *requires* nested options to be submitted to some endpoints. The nicest way I can express this in ruby is something like:

    ApiClient.update_a_resource(options)

Where in some cases, options can contain more nested hashes, all of which are required by the API I'm wrapping, so could really do with clear documentation.

To document this 'properly' with YARD, I'd have to refactor to something like

    ApiClient.update_a_resource(options, nested_options)

... then provide @param tags for both params, @option tags for both of their contents, then glue them together inside of update_a_resource - not nice!

Seems like someone else is having the same issue here, and has proposed a nice syntax to support this:
https://groups.google.com/forum/?fromgroups=#!topic/yardoc/vjVodQXyYqw

Apologies if I'm missing a standard/obvious way of doing this, but Google hasn't thrown anything up...

**Comment by lsegal** [comment]
Closing but would work on this as a PR. Please do ping me if you decide to take it on so I can provide guidance.
