### ISSUE TITLE
Meta-programming module inclusion

### ISSUE THREAD

**Issue by trans** [lsegal/yard#661]
Is there any way to inform yard that a meta-programming method includes a module? Simplified example:

```ruby
    class Tool
      def self.toolchain(mod)
        include mod
      end
    end

    class Foo < Too
      # @include Bar  <-- how?
      toolchain Bar
    end
```

While I'm asking, is there any way to do the same for a constant definition? I.e. I have a method that creates a constant so how do I inform YARD that this constant exists?

**Comment by lsegal** [comment]
The above macro example should now work without incorrectly creating a `Tool#Bar` method. The change disables method creation in the DSL handler if directives are used in the expanded macro text. In other words, if you use *any* directives, you *must* also use `@!method` or `@!attribute` to create the method object explicitly (if you want a method created for the expansion). YARD will no longer automatically do this. Note that if you do not use any directives in the macro expanded text, YARD will continue to take that expanded text and use that as a docstring on an implicitly created method. This is for legacy support-- ideally you should *always* explicitly create your object using a `@!method` directive-- even in a macro.
