### ISSUE TITLE
How to avoid documenting certain comment?

### ISSUE THREAD

**Issue by AntonSynytsia** [lsegal/yard#689]
Is there a tag or some other thing that can elude the comment from being documented?

In rdoc you can undocumented/document comment, or section of comments by adding #-- or #++.

Is there a way to do it yardoc?

**Comment by rlue** [comment]
Is this two-newlines rule still the case? I have the following:

```ruby
  # Attribute assignment methods -----------------------------------------------


  def set_url
    ...
```

but I'm still getting this:

![screen shot 2017-11-06 at 2 27 33 pm](https://user-images.githubusercontent.com/12194123/32428034-b9af9f56-c2fe-11e7-978f-31b5e28713b7.png)

I've made sure to delete and regenerate the `doc/` directory, and am using `yard server -r`.

---

(I use these full-width comments to demarcate different sections of the code.)

**Comment by lsegal** [comment]
@rlue yard server doesn't use the `doc` directory, it uses the `.yardoc` database in the root of your project. You should clear that if you've made structural changes to your code when using the reload switch.

**Comment by rlue** [comment]
Well, shut my mouth. Thanks for the insanely speedy reply.

**Comment by lsegal** [comment]
Glad you got it working!
