### ISSUE TITLE
`@see` with `{}` generates broken output

### ISSUE THREAD

**Issue by ddfreyne** [lsegal/yard#699]
I know `@see` is not meant to be used with `{}`, but then either the output should be OK or a warning/error should be emitted.

### Steps to reproduce

Save this code to `file.rb`, run `yardoc file.rb` and open `doc/Bar.html`:

```ruby
module Foo
  def x
  end
end

module Bar
  # @see {Foo#x}
  def xx
  end
end
```

### Actual output

> See Also:
> * Bar.{Foo{Foo#x}

Note that the list item is not even a link.

### Expected output

> See Also:
> * [Foo#x](doc/Foo.html#x)

**Comment by lsegal** [comment]
Not much we can do about the weird `Bar.{Foo{...}}` formatting, because that's actually behaving as expected. Added a warning to let people know not to do this.
