### ISSUE TITLE
API for printing custom statistics for DSLs after yardoc run

### ISSUE THREAD

**Issue by nitinmohan87** [lsegal/yard#710]
YARD has a very good API for creating plugins for Ruby DSLs. As far as I can tell, the statistics printed after the `yardoc` run cannot be modified to print information about custom objects in a DSL. For example, yard-spec plugin could print additional documentation information about spec tests as below
```
Files:           9
Modules:         2 (    1 undocumented)
Classes:         5 (    2 undocumented)
Constants:       1 (    1 undocumented)
Methods:        32 (    0 undocumented)
Spec Tests:    60 (    5 undocumented)
 90.00% documented
```

Being a [yard-chef](https://github.com/rightscale/yard-chef) plugin developer, it would be more helpful for the users if I could show statistics about `cookbooks`, `recipes`, `resources`, etc. rather than the default statistics that `yardoc` prints.
It would nice to have a `YARD::CLI::Stats` API to print custom statistics information when writing plugins for DSLs.

**Comment by lsegal** [comment]
Closing out old issues. This already seems to be available. If the API is not what you need, consider making a pull request to improve the API. See the contributing guide for more details on how to do this if you're still interested.
