### ISSUE TITLE
Webpage, README - please consider adding a subsection in the main guide for .gemspec files specifically

### ISSUE THREAD

**Issue by shevegen** [lsegal/yard#713]
Hi,

On IRC lsegal linked to the main starting guide at

http://rubydoc.info/gems/yard/file/docs/GettingStarted.md

The docu is very good, but I needed mainly something else, and this is how yard relates to .gemspec files specifically.

I.e. when I write a new .gemspec file, gemspec offers things like:

 s.extra_rdoc_files = %w( foobar.rdoc )

I would like to have something like this for yard too, so the main reason I tried to inquire was to find out how or whether yard could be used for .gemspec files. And if so, if there would be a minimal example for this?

Perhaps the GettingStarted.md file could provide this information, or a link towards being able to find more information? That would be very helpful.

I do not use rdoc for my project, so I am trying to look for alternatives. I have mostly very small gems, and the rdoc formatting is just not fitting to how I work with projects. The resulting autogenerated documentation is right now unusuable for anyone else, thus I am trying to look for alternatives.

Thanks.

**Comment by lsegal** [comment]
I'm closing this out since this question rarely comes up.

If you do believe someone might benefit from this info, please throw together a doc fix as a PR and I'll gladly take a look!
