### ISSUE TITLE
yri cannot find core methods even with yard-doc-core installed

### ISSUE THREAD

**Issue by postmodern** [lsegal/yard#718]
The `yri` utility is unable to find core methods, even with yard-doc-core 1.9.1 installed.

### Steps to Reproduce

1. `gem install yard yard-doc-core`
2. `yri Array`

### Expected Result

The same information as http://rubydoc.org/stdlib/core/Array

### Actual Result

    -------------------------------------------------- Class: Array < Object
    
    ------------------------------------------------------------------------
    
    Direct Known Subclasses:
    ------------------------
    
        MaRuKu::AttributeList,
        MaRuKu::In::Markdown::BlockLevelParser::BlockContext
    
    Instance methods:
    -----------------
    
        inspect_more

**Comment by lsegal** [comment]
Unfortunately `yard-doc-core` is woefully out of date and no longer maintained. I'd be willing to accept new maintainers for the gem, but I just don't have time to keep it updated, especially with faster Ruby release cycles. 

Marking this as WontFix but with great sadness!
