### ISSUE TITLE
@!attribute (see AnotherClass#foobar) does nothing

### ISSUE THREAD

**Issue by niels** [lsegal/yard#726]
Using `(see …)` to pull in documentation from elsewhere only seems to work for `@!method`, not `@!attribute`.

##### Given
```ruby
# @!attribute foo_attribute
#   Documentation for Foo#foo_attribute
# @!method foo_method
#   Documentation for Foo#foo_method
class Foo
end

# @!attribute bar_attribute_foo_attribute
#   (see Foo#foo_attribute)
# @!method bar_method_foo_attribute
#   (see Foo#foo_attribute)
# @!method bar_method_foo_method
#   (see Foo#foo_method)
# @!attribute bar_attribute_foo_method
#   (see Foo#foo_method)
class Bar
end
```

##### Expected
Everything defined in `Bar` should pull in the descriptions from `Foo` – or at least `Bar#bar_attribute_foo_attribute` and `Bar#bar_method_foo_method` should as they consistently are defined as attributes resp. methods in both classes.

##### Actual
Only the `@!method` definitions in `Bar` pull in corresponding descriptions from `Foo`:

![screenshot3](https://f.cloud.github.com/assets/16709/1839375/ec4a520e-7478-11e3-9ab6-345d85f5fd24.jpg)

**Comment by douglaswth** [comment]
@lsegal it seems like it's not working for `@!method` either.

**Comment by douglaswth** [comment]
As well as for `@option` when used on a normal method.

**Comment by lsegal** [comment]
I'm not sure that reftags are supported in directives. As for the `@option` tag, do you have an example that reproduces this?

**Comment by douglaswth** [comment]
Sure, I have the following in the `Instance` class which is creating docs perfectly:

```ruby
    # @!method run_executable(parameters = {})
    #
    # Run a recipe or RightScript on the instance.
    #
    # @param parameters [Hash] parameters for the executable
    #
    # @option parameters [Boolean] :ignore_lock whether to ignore instance lock
    # @option parameters [String] :recipe_name the name of the recipe from the instance's ServerTemplate to execute
    # @option parameters [RightScript] :right_script the RightScript to execute
    # @option parameters [String, Regexp] :right_script_name the name of the RightScript from the instance's
    #   ServerTemplate to execute
    #
    # @return [Task] the task to check on the status of the running executable
    #
```

I then tried the following on a method in another class and it only picks up the `@param` and `@return` info:

```ruby
    # Run a recipe or RightScript on the current instance of the server.
    #
    # @param (see Instance#run_executable)
    # @option (see Instance#run_executable)
    # @return (see Instance#run_executable)
    #
    # @see Instance#run_executable
    #
```

**Comment by lsegal** [comment]
My guess is the method defined in the other class doesn't have the same option parameter name (`parameters`), which is required. This works for me:

```ruby
class Instance
  # @!method run_executable(parameters = {})
  #
  # Run a recipe or RightScript on the instance.
  #
  # @param parameters [Hash] parameters for the executable
  #
  # @option parameters [Boolean] :ignore_lock whether to ignore instance lock
  # @option parameters [String] :recipe_name the name of the recipe from the instance's ServerTemplate to execute
  # @option parameters [RightScript] :right_script the RightScript to execute
  # @option parameters [String, Regexp] :right_script_name the name of the RightScript from the instance's
  #   ServerTemplate to execute
  #
  # @return [Task] the task to check on the status of the running executable
  #
end

class Bar
  # Run a recipe or RightScript on the current instance of the server.
  #
  # @param (see Instance#run_executable)
  # @option (see Instance#run_executable)
  # @return (see Instance#run_executable)
  #
  # @see Instance#run_executable
  #
  def run(parameters = {}); end
end
```

**Comment by douglaswth** [comment]
@lsegal Ah, that was it for doing it with the normal method.

**Comment by lsegal** [comment]
The `@!attribute` reftag syntax should now be supported. The issue was that the `(see ....)` portion was being parsed by the tag parser as a type specification instead of a docstring reference (since parentheses can be used for type specifiers). The change limits where type specifiers can start from-- specifically, they must start on the opening line of the tag in order to be detected. While this is technically a breaking change, I could not find any usage of type specifiers in various code searches that used this syntax, so it should be fairly safe.
