### ISSUE TITLE
Add `@!class` and `@!module` directives

### ISSUE THREAD

**Issue by matheusmoreira** [lsegal/yard#737]
Currently, when I try to generate documentation for the following code:

```
# Documentation for the X class.
class X < Class.new
  const_set :Y, superclass
end

X.superclass  # => X::Y
```

YARD gives me the following warning:

```
[warn]: in YARD::Handlers::Ruby::ClassHandler: Undocumentable superclass (class was added without superclass)
[warn]:         in file 'lib/x.rb':1:

        1: class X < Class.new
```

It is nice to have tags that would allow us to manually specify data that YARD can't figure out on its own. The `@!method` directive is incredibly useful in this regard. However, that feature set is not complete: it is missing `@!class` and `@!module` directives.

Many situations could benefit from such directives. Perhaps a class will be dynamically created at runtime via DSL and YARD has no way of knowing in advance. In that case, the `@!class` directive could be used to manually supply documentation for the classes in a way that doesn't rely on conventional Ruby code or the parsing of a `class` keyword.

These directives could help people adapt YARD to dynamic scenarios such as the one displayed above (it makes sense in context). More examples are possible: a module only receives its name when it is bound to a constant. The class might not have a name at the point in time where it is created and documented:

```
# @!class Y < Z
#   Documentation for the Y class.
y = Class.new Z

# later...

X.const_set :Y, y
```

If combined with macros, this functionality would enable us to better capture DSLs and dynamic runtime behavior in our documentation. A DSL that generates a class at runtime could supply documentation that can be attached to the new class.

```
# @!macro [attach] make_class
#   @!class $1 < $2
#
#     $3
def make_class(name, superclass = Object, documentation = nil)
  const_set name, Class.new superclass
end

make_class :NewClass, Super::Class, 'Documentation for the NewClass.'
```

**Comment by ms-ati** [comment]
Did this ever happen? Would really like this for documenting Value classes from the `values` gem!

**Comment by lsegal** [comment]
@ms-ati a PR was never opened for this AFAIK. The workaround provided above is still the way to go; if you're interested in working on the PR I would look at it.

**Comment by Hubro** [comment]
> Did this ever happen? Would really like this for documenting Value classes from the `values` gem!

Same here, I Googled this issue when trying to document a class generated using `Values.new`. Currently I have about 100 lines of the ugliest and least maintainable documentation I've ever written. A `@!class` directive would be extremely welcome.

**Comment by matheusmoreira** [comment]
@Hubro, years ago I forked `yard` and tried to add the features in order to send a pull request. I wasn't familiar with the `yard` source code and couldn't figure out how to make it work.

**Comment by ms-ati** [comment]
@hubro if you are interested in developing a yard plugin specifically for Value classes, which generates documentation for both constructors and all the Value methods automatically, I’d be motivated to partner with you on that — please let me know?

**Comment by Hubro** [comment]
> @Hubro if you are interested in developing a yard plugin specifically for Value classes, which generates documentation for both constructors and all the Value methods automatically, I’d be motivated to partner with you on that — please let me know?

I just realized I can avoid using `@!parse` by defining the class twice:

```ruby
Person = Value.new(:name, :age)

# This is the documentation for Person
# 
# @!attribute [r] name
#   @return [String]
# 
# @!attribute [r] age
#   @return [Integer]
# 
class Person
end
```

This removes the urgency of this feature for me.

Although I think it should be pretty trivial for someone with knowledge of YARD to find which ever block of code handles documentation for `Struct.new` and expand it to also cover `Values.new`.
