### ISSUE TITLE
Comparison operators in the summary description are being ignored (in some cases)

### ISSUE THREAD

**Issue by kyrylo** [lsegal/yard#757]
| YARD version        | Ruby version |
| ------------- |-------|
| 0.8.4      | 2.1.1 |

#### The bugged docstring

```ruby
# Creates the HTML element <source> with an optional +<figcaption>+ and a * b > c < d
```

#### The output

![](http://img-fotki.yandex.ru/get/9819/98991937.14/0_a2e39_8777a2a_orig)

**Comment by kyrylo** [comment]
👏

**Comment by lsegal** [comment]
It took me a while to get to this but there doesn't seem to be a good reason to strip HTML out of a docstring summary at the low level. If raw HTML is used in the summary string, it should be escaped with proper markup formatting anyway, so there's no rendering issue here.
