### ISSUE TITLE
attr_reader <name> overrides attached @!attribute [r] <name>

### ISSUE THREAD

**Issue by limhoff-r7** [lsegal/yard#768]
If I document `attr_accessor :bar` like so:

```ruby
class Foo
  # @!attribute bar
  #   This foo's bar.
  #
  #   @return [Bar]
  attr_accessor :bar
end
```

Then the generated documentation is

![screen shot 2014-04-24 at 9 40 28 am](https://cloud.githubusercontent.com/assets/2230482/2790659/703ae3fc-cbbe-11e3-83c3-c5aa2000bdc3.png)

which is what I would expect: the `@!attribute` directive overrides the default docs for `attr_accessor`, but if I try the same thing with `attr_reader :bar` for a read-only variable:

```ruby
class Foo
  # @!attribute [r] bar
  #   This foo's bar.
  #
  #   @return [Bar]
  attr_reader :bar
end
```

The the generated documentation is

![screen shot 2014-04-24 at 9 43 26 am](https://cloud.githubusercontent.com/assets/2230482/2790709/d79bdb5a-cbbe-11e3-81d1-ea242d4f4747.png)

which isn't using the `@!attribute` directive, but the default docs for an `attr_reader`.

I did figure out it was an ordering thing, because if I put the `attr_reader` before the `@!attribute`, it works

```ruby
class Foo
  attr_reader :bar

  # @!attribute [r] bar
  #   This foo's bar.
  #
  #   @return [Bar]  
end
```

generates

![screen shot 2014-04-24 at 9 45 35 am](https://cloud.githubusercontent.com/assets/2230482/2790733/216c8fea-cbbf-11e3-8b89-06e96a7bb030.png)

which is what I expected the 2nd source to generate.

I've been able to generate this issue on 0.8.7.3 and 0.8.7.4.  I've been not using 0.8.7.4 because in it, the reader is not being documented with the return type from the `@return` in the `@!attribute` attached to `attr_accessor`.  I'm not sure if that bug has been reported yet.  If not I can open a separate issue for it.  Considering that both are related to docs attached to attr_reader (this one with an explicit attr_reader and the 0.8.7.4 bug with an implicit reader) it may be that something in wonky with reader handling.

**Comment by lsegal** [comment]
I mislabeled this as a bug a while back having not read the actual issue properly. This is actually expected behavior, related to #787. You should not define a directive on an `attr_*` comment block. Directives are specifically meant for scenarios where there is no `attr_*` call to add docstrings to.
