### ISSUE TITLE
Arbitrary javascript can be inserted into doc comments

### ISSUE THREAD

**Issue by jvennix-r7** [lsegal/yard#775]
It is unclear if this is a supported feature or just a byproduct of markdown generation. Either way, if I `cd` into someone else's project and run `yard`, then view the docs, I would not expect arbitrary javascript to be running in my browser. The impact is worsened by the fact that most people view their docs at a file:// URL, so on some browsers/plugins the javascript can read/steal local files. At a minimum it would be nice if yard supported a `--sanitize` flag that stripped `<script>` tags and `on*=` event handlers.

##### Reproduce:
Add `<script>alert(1)</script>` to a method documentation string, then view the docs for that class.

**Comment by lsegal** [comment]
I would accept a `--safe-html` as a PR. Marking this as closed (see [CONTRIBUTING.md](https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md) for why this was closed).
