### ISSUE TITLE
"asciidoc" support lacks required CSS

### ISSUE THREAD

**Issue by xb** [lsegal/yard#788]
Consider this line https://github.com/asciidoctor/asciidoctor/blame/d54440eb5e5651d7c3f0d9400cea210a5b475415/README.adoc#L54

The line reads
```
NOTE: With few exceptions, Asciidoctor is compliant with the original AsciiDoc processor.	Asciidoctor has well over 1,000 tests to ensure compatibility with the AsciiDoc
```

# Expected result:

That line is rendered with a cute little "note" image, as shown in http://powerman.name/doc/asciidoc .

# Actual result:

The line is rendered in http://rubydoc.org/gems/asciidoctor/file/README.adoc without the lcute little "note" image.

**Comment by lsegal** [comment]
Closing out old issues.

I don't have much time to invest into customizing styles/semantics for asciidoctor, but if someone wanted to take this on, a PR could be looked at. Then again, this might be a better candidate for a plugin, if we're really looking at rewriting asciidoc's semantic output-- I don't believe something that complex would belong in YARD core.
