### ISSUE TITLE
Add {LICENSE,COPYING}.* and {ChangeLog,CHANGELOG}.* to Files by default

### ISSUE THREAD

**Issue by postmodern** [lsegal/yard#805]
As with the convention of adding `README.*` to additional Files, so should `{LICENSE,COPYING}.*` and the ChangeLog files. Including the `LICENSE` file(s) is just common sense. Including the ChangeLog is incredibly useful, as you can link to specific releases and use YARD links in the ChangeLog entries.

99% of my ruby projects contain these files and [ore](https://github.com/ruby-ore/ore/blob/master/data/ore/templates/yard/.document.erb) adds them to `.document` by default. It would be DRY if YARD recognized these common files.

**Comment by lsegal** [comment]
Marking this as WontFix. Adding these globs introduces complexity that has historically caused other compatibility issues when similar patches were accepted. I'm also unconvinced that a LICENSE and COPYING should necessarily be generated by default alongside API documentation, and I don't see a clear convention for a ChangeLog filename. YARD currently sticks to path/filename conventions used by RubyGems or RDoc (the latter for historical reasons), I don't think we should be creating new file structure conventions for Ruby projects. If RubyGems were to add some standardized ChangeLog/CHANGELOG filename convention, I would be willing to re-visit this.

Given how projects can opt-in with a `.yardopts` file, that is a reasonable path forward.
