### ISSUE TITLE
{include:file:...} not embedding file in yri output

### ISSUE THREAD

**Issue by rampion** [lsegal/yard#817]
At the top of my source file, I've got:

```ruby
# {include:file:README.md}
module MyAwesomeMod
  #...
```

The `{include:file:README.md}` seems to work when I look at the HTML output of `yardoc`, but it doesn't embed the `README.md` file when I use `yri`:

    % yri MyAwesomeMod
    ---------------------------------------------------- Module: MyAwesomeMod
     
         {include:file:README.md} 
    
     ...

**Comment by lsegal** [comment]
This is now supported.
