### ISSUE TITLE
@!attribute causes Undocumented objects for writers

### ISSUE THREAD

**Issue by limhoff-r7** [lsegal/yard#819]
With yard 0.8.7.6, https://github.com/rapid7/metasploit-cache/commit/c8205c2faf37a19af6ec62bd5516a5cfbe28638c shows the setters declared with `@!attribute` as undocumented

# Reproduction steps

1. `git clone git@github.com:rapid7/metasploit-cache.git`
2. `git checkout c8205c2faf37a19af6ec62bd5516a5cfbe28638c`
3. `bundle install`
4. `rake yard`

## Actual
```
Undocumented Objects:
Metasploit::Cache::Architecture#endianness=                        (lib/metasploit/cache/architecture.rb:324)
```

## Expected 
`Metasploit::Cache::Architecture#endianness=` should count as documented by [the `@!attribute [rw] endianness`](https://github.com/rapid7/metasploit-cache/blob/feature/MSP-11141/extract-cache-from-metasploit-model/lib/metasploit/model/architecture.rb#L324)

**Comment by Bounga** [comment]
I do have the exact same problem. The only solution is to duplicate the documentation for the `=` version let's say:

    @!attribute name
    @!attribute name=

So the [rw] version (which is the default) is a bit useless for now. It's annoying since in fact the attribute *is* documented.

**Comment by lsegal** [comment]
The `@!attribute` directive is not meant for scenarios where `attr_*` is declared verbatim in Ruby source. See #787 for a more complete discussion. This seems like expected behavior to me.

**Comment by Bounga** [comment]
In #787 you say that:

> The @!attribute macro is meant for dynamic attributes that don't have explicit declarations in source code.

This is the exact problem I'm having since I'm trying to document ActiveRecord attributes which are auto-generated (columns in database table).

**Comment by lsegal** [comment]
@Bounga I am responding to the OP's report. If you have a different scenario please open a new issue with information to reproduce. In this issue the `attr_*` call is provided in the source.

**Comment by Bounga** [comment]
@lsegal Ok my bad so I'll open a new issue.
