### ISSUE TITLE
Support for arbitrary lists (@list)

### ISSUE THREAD

**Issue by anthonator** [lsegal/yard#828]
It would be nice to be able to create an arbitrary list similar to the style of ```@param```. It's possible to kind of fake it but first class support would be great.

**Comment by lsegal** [comment]
Can you provide more details about this? i.e., an example of what you want this to look like, and what this accomplishes?

**Comment by anthonator** [comment]
I was thinking something like the following:
```
@list Groceries
@item Apples
@item Celery
@item Reese's Cups
```
and render like:

**Groceries:**
&nbsp;&nbsp;&nbsp;&nbsp; &#9642; Apples
&nbsp;&nbsp;&nbsp;&nbsp; &#9642; Celery
&nbsp;&nbsp;&nbsp;&nbsp; &#9642; Reese's Cups

**Comment by anthonator** [comment]
I think this just provides additional flexibility. There are instances where I just want to communicate flow or process order or something where a list is appropriate.

Will also need to come up with a way to delineate ordered vs unordered list.

**Comment by rrrene** [comment]
I always thought that in these circumstances (frequent need of advanced text formatting) it would be o.k. to (a) choose markdown as your main text-processor (which YARD support IIRC) or to (b) simply use HTML.

I would suggest MD for frequent need of lists, tables, etc. and HTML for the case where you have **one** module where you want to show some table for comparision or list of outcomes or something like that in the docs.

As always: YMMV. :+1:

**Comment by lsegal** [comment]
Agreed with @rrrene. YARD is not a markup format. If the request here is to add generic list formatting markup, that's probably not going to happen. If you're looking to just do generic formatting, use markdown or rdoc formatting tools that are already available to format lists. Tags are meant to provide *semantic* meaning, in this case `@list` provides no real semantics.

**Comment by anthonator** [comment]
I'm currently using Markdown but formatting is off and adding a bunch of HTML entities to get the style that YARD already has. Since YARD already has lists in a format that works I was hoping to get more of the same just a little more generic.

**Comment by lsegal** [comment]
@anthonator why is the formatting off? Can you explain what you are trying to accomplish in more detail so we all understand what this feature would actually provide? Simply asking for a `@list` tag wouldn't even guarantee that it would be formatted the way you want, if the formatting is what you're specifically looking for.

**Comment by lsegal** [comment]
Closing since there are no plans to add markup-specific tags to YARD. Tags are meant for semantic declarations only-- the presentation format of a specific tag is never guaranteed. Real markup should be used for those scenarios.
