### ISSUE TITLE
Support attached @macro to a DSL method in a gem

### ISSUE THREAD

**Issue by stanio** [lsegal/yard#829]
If a `@macro` is declared on a DSL method in `foo.rb`:
```ruby
class Foo

  class << self

    # @macro [attach] foo_field
    #   @!attribute [r] $1
    #     @return [$2] $3
    def field(*args)
      # ...
    end

  end

end
```
Having `bar.rb`:
```ruby
require 'foo'

class Bar < Foo

  field :abc, type: Integer, description: 'Jackdaws love my big sphinx of quartz'
  field :xyz, type: String, description: 'The quick brown fox jumps over the lazy dog'

end
```
`yard doc` (actually `yard doc foo.rb *.rb` to ensure macro has been parsed first) - documentation is generated as expected.

Moving `foo.rb` to a gem library (as often DSL is packaged as) - the `@macro` is no longer applied to the documentation of `bar.rb`.

**Comment by lsegal** [comment]
This is actually fairly complicated to do. Right now YARD has no concept of "gems", or even external library code. You could do this yourself by loading the YARD index for the gem and copying the macro objects from the [YARD::Registry](http://www.rubydoc.info/gems/yard/YARD/Registry), but a lot of infrastructure would have to be put in place before you could get this out of the box in YARD.

**Comment by stanio** [comment]
I'm a Ruby newbie and don't have knowledge of much of the internals, but I've seen it elsewhere and I was thinking if it could find the source file of the method like:
```ruby
Foo.method(:field).source_location
```
then process that source as if it was included in the project.

**Comment by lsegal** [comment]
Marking this as WontFix. There are no plans to support this in YARD's roadmap. I would still accept PRs to support this though, but you might be better off writing a plugin first, if you're interested, given the complexity of the code involved. If this works as a plugin, merging it in would be an easier discussion.
