### ISSUE TITLE
yard server, when used in conjunction with a plugin (yard-sinatra) breaks during deserialization

### ISSUE THREAD

**Issue by zenithwolf1000** [lsegal/yard#830]
With Yard v0.8.7.6, if specifying a plugin (yard-sinatra), the documentation seems to be generated appropriately, but yard server breaks due to missing require

### Steps to Reproduce
1. Use `'yard-sinatra'`gem with Yard
2. Run `yardoc --plugin yard-sinatra` to generate documentation on a given Sinatra project
3. Run `yard server --debug`

#### Expected Outcome
Server works as expected

#### Actual Outcome
The following error is encountered:

```
[debug]: Deserializing /Users/spatankar/Work/API-Ruby/.yardoc/objects/root.dat...
[error]: ArgumentError: undefined class/module YARD::CodeObjects::RouteObject
[error]: Stack trace:
	.../gems/yard-0.8.7.6/lib/yard/serializers/yardoc_serializer.rb:77:in `load'
	.../gems/yard-0.8.7.6/lib/yard/serializers/yardoc_serializer.rb:77:in `deserialize'
	.../gems/yard-0.8.7.6/lib/yard/registry_store.rb:282:in `load_root'
	.../gems/yard-0.8.7.6/lib/yard/registry_store.rb:240:in `load_yardoc'
	.../gems/yard-0.8.7.6/lib/yard/registry_store.rb:128:in `load'
	.../gems/yard-0.8.7.6/lib/yard/registry.rb:121:in `load_yardoc'
```

It seems yard cannot resolve what's in the `./.yardoc/objects/root.dat` file, which is apparently serialized.

### Bandaid Solution
To make this work in my project, I just added a `require 'yard-sinatra'` statement at the top of the `/lib/yard/serializers/yardoc_serializer.rb` file

**Comment by lsegal** [comment]
This is expected behavior. Your plugin adds files to the YARD registry that make it unloadable without the plugin. If you specify your plugin in your `.yardopts` file, it should load correctly. You can also load the plugin when running `yard server` itself:

```
$ yard server --plugin sinatra
```

**Comment by zenithwolf1000** [comment]
Thank you sir.

The following worked perfectly (of course, alongside yardoc --plugin 'yard-server'
```
$ yard server --plugin sinatra
```

Thank you, and closing this issue as the behavior is expected.
