### ISSUE TITLE
@param example is confusing

### ISSUE THREAD

**Issue by kwinters** [lsegal/yard#833]
See lib/yard/tags/library.rb @param section.

"Documents a single method parameter with a given name, type and optional description."

But the example is "@param [String] the URL of the page to download" which omits the required(?) name of the param.

So I suggest adding an example that includes the param name. If the name is supposed to be optional, please also update the docs to say so or remove the example that omits it.

**Comment by lsegal** [comment]
It's not optional, it's just a typo :)

**Comment by GuyPaddock** [comment]
There are actually a lot of places where the order of @param is wrong. See the README, for example. Should I open a new issue about that?

**Comment by lsegal** [comment]
@GuyPaddock neither form is wrong since both are valid and supported. If you want to make a *pull request* to consolidate the syntax of examples I'd be okay with it, but an issue won't be looked at without an accompanying PR.
