### ISSUE TITLE
Method list not updated for included mixins 

### ISSUE THREAD

**Issue by deuberger** [lsegal/yard#841]
If I specify --embed-mixins or do something like:

```
#@!parse include MyMixin
```
The mixin methods are documented directly on the class page as if they were written inline, but they don't show up in the the method list for the classes where it's included. I suppose one could argue that as being correct behavior, but I find it a little confusing/misleading.

I'm using yard 0.8.7.4.

**Comment by lsegal** [comment]
The only concern would be that adding embedded methods to the method list would cause a huge method list explosion for certain projects that might rely on it heavily, like Rails, for instance. 

The other point is that just like regular inheritance, the methods don't actually exist on that object, they exist in the parent in the inheritance tree. We don't duplicate methods inherited from regular superclasses, so I'm not sure why YARD wouldn't behave the same for mixins.

The template logic for embedding mixins is simply a presentation layer convenience, it shouldn't affect the overall structure of where code lives.

**Comment by deuberger** [comment]
Hmm, I see your point. I guess we can close this then.
