### ISSUE TITLE
@param tag has unknown parameter name with @!method even though parameter used in generated docs

### ISSUE THREAD

**Issue by limhoff-r7** [lsegal/yard#842]
When upgrading from 0.8.7.4 to 0.8.7.6, I now get the following (category) of warning:

```
[warn]: @param tag has unknown parameter name: module_instances 
    in file `app/models/metasploit/cache/module/class.rb' near line 147
```

from

```ruby
  # @!method self.with_module_instances(module_instances)
  #   {Metasploit::Cache::Module::Class Metasploit::Cache::Module::Classes} associated with the `module_instances`.
  #   Allows converting queries using {Metasploit::Cache::Module::Instance} scopes to
  #   {Metasploit::Cache::Module::Class} scopes.
  #
  #   @param module_instances [ActiveRecord::Relation<Metasploit::Cache::Module::Class>]
  #   @return [ActiveRecord::Relation<Metasploit::Cache::Module::Class>]
  scope :with_module_instances,
        ->(module_instances){
          module_class_ids = module_instances.joins(:module_class).select(Metasploit::Cache::Module::Class.arel_table[:id])
          where(id: module_class_ids)
        }
```

However, the `module_instances` parameter is used to generate the docs correctly:

![screen shot 2015-03-05 at 3 09 17 pm](https://cloud.githubusercontent.com/assets/2230482/6514651/a3cd7328-c349-11e4-89ec-52a7e14e131a.png)

# Reproduction Steps
- [ ] `mkdir -p ~git/rapid7`
- [ ] `cd ~git/rapid7`
- [ ] `git clone git@github.com:rapid7/metasploit-cache.git`
- [ ] `git checkout ef03db15cebc669ff287439d1fabb1df06947aba`
- [ ] `bundle`
- [ ] `rake yard`
- [ ] `open doc/Metasploit/Cache/Module/Class.html`
- [ ] Scroll down to `with_module_instances`

## Actual
- [ ] `[warn]: @param tag has unknown parameter name: module_instances`
- [ ] `module_instances` parameter has correct type even though warning says it was unknown.

## Expected
- [ ] No `[warn]`
- [ ] `module_instances` parameter has correct type

**Comment by limhoff-r7** [comment]
I forced downgrading to YARD 0.8.7.5 and the `[warn]` are still there.  I can't go back to 0.8.7.4 because it doesn't handle required keyword arguments from Ruby 2.1.

**Comment by lsegal** [comment]
I'm confused about the last statement regarding downgrading. Note that this is just a warning-- it looks like everything generates okay-- so you could just ignore the warning without having to change versions.

Thanks for reporting though! It looks like there's just a messup in the warning logic here: 

https://github.com/lsegal/yard/blob/master/lib/yard/docstring_parser.rb#L296-L315

**Comment by limhoff-r7** [comment]
I like to not have to ignore warnings for YARD, so like running `-Werror` for a c compiler, since warnings are giving for important things like unresolvable links.

**Comment by lsegal** [comment]
I can't seem to reproduce this in v0.9.0 anymore. Not sure if this was resolved between releases or if something else is required to reproduce. I'm going to mark this as closed, but feel free to re-open if you are still seeing this. It would help to provide a more minimal test case for this, though.
