### ISSUE TITLE
alias_native for Opal Ruby?

### ISSUE THREAD

**Issue by ylluminate** [lsegal/yard#849]
We have been working on fleshing out some Ruby wrappers for JavaScript libraries to be used via Opal Ruby (Ruby ->  JS transpiler).

The `alias_method` is similar to `alias_native` in Opal, which facilitates the quick utilization of native JS methods in Ruby.

We'd like to use `yard` to document these wrappers since the documentation varies when you shift over into using JS libs in Ruby (rightfully so)  Any thoughts on how to properly implement `alias_native` support in `yard` so that it picks these up when generating documentation?

**Comment by lsegal** [comment]
@ylluminate I would take a look at the existing [alias handler](https://github.com/lsegal/yard/blob/master/lib/yard/handlers/ruby/alias_handler.rb) and copying the functionality from that handler into your own plugin +/- any different behaviors that `alias_native` might have.

**Comment by lsegal** [comment]
Marking as WontFix. There are no plans to support non-standard Ruby extensions in the core YARD implementation.
