### ISSUE TITLE
Release gem version of "frameless" branch

### ISSUE THREAD

**Issue by apepper** [lsegal/yard#850]
www.rubydoc.info uses `yard` in the `frameless` branch versions, since fall of 2014: https://github.com/lsegal/rubydoc.info/blame/master/Gemfile#L20 .

When are you planing to release an official version of `frameless`? E.g. as version `0.9.0.0`?

I'm asking, since it's annoying, that I can't use an official gem version of `yard` to see the same styling as www.rubydoc.info.

**Comment by lsegal** [comment]
@apepper I was actually just thinking about this the other day. There's no timeline right now-- the delay has to do with the fact that changing the template (even in this subtle way) is a fairly large undertaking and we want to make sure we're not regressing any functionality by forcing the official gem to convert. We've been using rubydoc.info as a testing ground for the new template, and that's helped us get a lot of good feedback, but we still have some outlying issues that haven't yet been addressed and there's more work to be done / testing to make sure things don't break for users who use/customize YARD in various ways.

That said, you should be able to use yard off of the frameless branch just fine. It may not be an "official" release, but practically speaking it should be easy to install from git, especially with new Gemfile support in [RubyGems 2.2.0+](http://blog.rubygems.org/2013/12/26/2.2.0-released.html).

**Comment by lsegal** [comment]
This is out!
