### ISSUE TITLE
Support for mruby

### ISSUE THREAD

**Issue by pbosetti** [lsegal/yard#851]
Current version does not support mruby C syntax. I think that the best solution would be to add to the C handlers the necessary MATCH cases for matching mruby C API functions equivalent to the ruby ones, especially given that the extension of the files to be parsed is the same .c, and that would probably raise some issue when implemented as a plugin (but maybe I'm wrong, I only dedicated half a work day in reading YARD source code).

Any plan to do that? is this the most viable/appropriate way (in this case I could fork and prepare a PR)?

Thanks,
Paolo

**Comment by lsegal** [comment]
There are no plans to support mruby .c files from YARD's core codebase. The language is young, the C API may change, and there is a huge maintenance burden in tracking that. This would be best implemented as a plugin focused on adding mruby support.

**Comment by sagmor** [comment]
@pbosetti just started to work on this as a YARD plugin at [yard-mruby](https://github.com/sagmor/yard-mruby).

It's still pretty early but you might want to take a look at it.

**Comment by lsegal** [comment]
Closing out old issues.

Very cool, @sagmor! Let me know how this goes. In the future, this is something that could be merged into YARD once mruby becomes stable enough.

**Comment by sagmor** [comment]
@lsegal Sure, It's working great so far.
It has a couple rough corners pending but the hardest part is done 😛  and it's being used on the official [mruby api docs](http://mruby.org/docs/api/) if you want to take a look at it.
