### ISSUE TITLE
Serving documents with yard server gives different result than opening html manually

### ISSUE THREAD

**Issue by snowe2010** [lsegal/yard#857]
I'm attempting to fix problems with the yard-cucumber gem as it is not being maintained anymore. When I generate documentation using `yardoc` and open the `file.README.html` file manually, I'm able to click on the menu tabs at the top right and they drop down successfully. However, if I try to run the `yard server` (even with -t and --docroot commands) when I click on the menu buttons it goes to a page with a list of the items instead of the search dropdown. 

I've tracked down the issue being that the generated doc files have this in the header,

```
<script type="text/javascript" charset="utf-8">
  hasFrames = window.top.frames.main ? true : false;
  relpath = '';
  framesUrl = "frames.html#!_index.html";
</script>
```

while the files that yard server runs do not have that in the header. I cannot for the life of me figure out why.

![yard-cucumber](https://cloud.githubusercontent.com/assets/1534535/7257850/c7f29dbe-e815-11e4-9952-4bd44d4b4475.gif)

**Comment by lsegal** [comment]
Has this since been resolved? Note that v0.9.0 includes template changes that may affect how this works.

**Comment by lsegal** [comment]
I'm going to mark this as closed since there have been a couple of changes in templates and yard-cucumber may need updates to work correctly if it still does not. Feel free to re-open if there are other problems.

**Comment by snowe2010** [comment]
I am not sure if this resolves it, I haven't worked with ruby in almost a year now, and definitely haven't worked on this project in a long time. Just treat it as resolved until someone else finds a problem :D
