### ISSUE TITLE
@!attribute is not documenting dynamic setters when the type specifier is [rw]

### ISSUE THREAD

**Issue by stjeanp** [lsegal/yard#862]
I'm working on a fog module and using the @!attribute directive to document the models' and collections' attributes. The getters and setters are dynamically created by fog.

When I generate the docs with the '--list-undoc' flag, I get numerous undocumented setters, and they all appear to be the ones with a type specifier of [rw]. The ones that have a type specifier of [w] do not seem to be showing up in the undocumented methods data. Here's a snippet of the document generation output:

(in file: lib/fog/vzcloud/models/compute/vnic_metrics.rb)
Fog::Compute::VZCloud::VnicMetrics#granularity=
Fog::Compute::VZCloud::VnicMetrics#number=

And in that file, here's the directives in question:

        # @!attribute [rw] granularity
        #   The granularity of these metrics, can be either H for hourly or D for daily
        #   @return [String] the granularity
        attribute :granularity, :type => :string

        # @!attribute [rw] number
        #   The number of the Vnic these metrics are for
        #   @return [Integer] the Vnic's number
        attribute :number, :type => :integer

**Comment by lsegal** [comment]
@stjeanp YARD attaches documentation to the reader, so the attributes are getting documented, just not on the generated writer object. This is expected behavior, and you can safely ignore this undocumented attribute.

**Comment by stjeanp** [comment]
Interesting... Thanks for explaining that.

I haven't had time to crawl through the code, but I'm wondering if there's a way to tweak it so that the code thinks the writer is documented so that the warnings are suppressed and the stats accurately reflect the actual documentation state...

**Comment by lsegal** [comment]
It would be incorrect to convince YARD that the object is documented. The reality is that the metric used for calculating coverage of generated HTML is not exactly that of the actual objects themselves in the registry. Specifically, the `yard stats` command as well as the stats that come out of running yard, should never be used as accurate representations of documentation coverage-- at best they are estimates. I've stated this a number of times and stand by this.

What you actually want is to use the registry to programmatically query for undocumented methods using your own custom heuristics. `Registry.all.select {|o| o.docstring.blank? }` will get you the list of undoc'd objects, which you can then prune down further using your own rules. Appending your own `--query` conditions would be valid too (like `--query 'o.name !~ /=$/'`).

**Comment by stjeanp** [comment]
Makes sense and thanks for the tips. I'm going to go ahead and close this and start messing around with that.

I appreciate you taking the time to work through this with me.
