### ISSUE TITLE
Rewrite local markdown links to markdown files

### ISSUE THREAD

**Issue by mvz** [lsegal/yard#863]
I'm trying to get the documentation as generated by YARD in order for [reek](https://github.com/troessner/reek). In the README.md and elsewhere we are using Markdown formatted links to other markdown files in the same repository. This works out very nicely when viewing the files on GitHub, but all the links are broken when the documentation is generated by `yardoc`, because it generates files with a different extension and relative path.

An alternative is to use the `{file: ...}` syntax, but that isn't part of standard markdown so leaves ugly bits when rendered, e.g., on GitHub.

It would be very nice if YARD could detect local markdown links to other files it is including in the documentation and rewrite them accordingly.

**Comment by lsegal** [comment]
YARD doesn't post-process markup, but you can do one of the following:

1. Process the generated .html files yourself (grep/sed),
2. Write a YARD plugin to modify the output, or,
3. Switch to another markdown provider (`-M`) that may allow you to inject URL rewriting behavior.

**Comment by mvz** [comment]
I investigated a bit more, and it seems using `yard server` keeps the links working.

**Comment by mvz** [comment]
@lsegal thanks, I'll look into those options.

**Comment by mvz** [comment]
>  it seems using yard server keeps the links working.

Nope, they're broken in a different way.

**Comment by lsegal** [comment]
>> it seems using yard server keeps the links working.
> Nope, they're broken in a different way.

Well, it's not expected to work. your hard-coded links are probably assuming a lot of things about (a) the structure of the generated URLs, and (b) the extensions/filenames generated by the templates YARD uses. Neither of these things are reliable assumptions and will change across your tools/views (GitHub vs YARD HTML vs YARD server vs RDoc vs etc.), and may even change across versions of these tools. For one, YARD doesn't retain your path structure for extra files; it stores all files in a flat namespace. Similarly, the presence of a .html extension varies in different modes, for obvious reasons.

**Comment by mvz** [comment]
Hi @lsegal, I went with your option 2 and made a small plugin just for our specific case. See https://github.com/troessner/reek/blob/87b0e75091552c59fcf20105016ba6ce97a57b06/docs/yard_plugin.rb

Thanks!
