### ISSUE TITLE
Feedback on best practices for doc'ing attributes?

### ISSUE THREAD

**Issue by dogweather** [lsegal/yard#866]
My classes consist mostly of `attr_accessor` and `validates` calls (using ActiveModel::Validations.) I've been testing a couple different strategies for documenting them. Any comments? Am I doing this the best I can?

**Style 1:** [Conventional, all at the top](https://github.com/eaternet/adapters-ruby/blob/53184b4050d9c0425da5b9753ada25e7f4aa8191/lib/eaternet/lives_1_0/business.rb). It's what people expect, but some tools like `inch` don't do well with it.

**Style 2:** [Docs where the attributes are defined](https://github.com/eaternet/adapters-ruby/blob/53184b4050d9c0425da5b9753ada25e7f4aa8191/lib/eaternet/lives_1_0/inspection.rb), and the code is broken up per-attribute, not per class method.

(I wrote [a blog post](http://robb.weblaws.org/2015/05/17/self-validating-plain-old-ruby-objects-with-activemodel-validations/) about this style of coding, fwiw.)

**Comment by lsegal** [comment]
You should use **Style 3**. It's exactly like Style 2 except you should *not* be using `@!attribute` directives when documenting `attr_accessor` statements. The advantage of this format is that it would be cross-compatible with every other documentation tool out there, and much more per convention.

Style 1 is not convention. Rather, it should not be.

**Comment by dogweather** [comment]
I think I get it. As the docs read,

> The most common is the attr_accessor method, which of course has built-in support in YARD.

E.g., the docs for an accessor should look like:

```ruby
      #   Date of the inspection.
      #   @return [Date]
      attr_accessor :date
      validates :date,
                type: Date,
                presence: true
```

**Comment by lsegal** [comment]
Yep. Or just `@return [Date] the date of inspection `.

**Comment by dogweather** [comment]
Beautiful, yes: yard automatically picks up everything from `attr_accessor`.
