### ISSUE TITLE
Unhandled exception in YARD::Handlers::Ruby::CommentHandler

### ISSUE THREAD

**Issue by DanRathbun** [lsegal/yard#867]
[Backstory] I want to have all the basic Ruby methods show in my API docs from BasicObject, Object, Kernel, & standard mixins (Comparable, Enumerable, etc.).. so I I have stub rb files (empty methods.)

Having some issues documenting core methods with the more obscure symbolic names.

But the BasicObject negation method takes the cake. I got some mediocre errors when I tried:
```ruby
def !()
end
```
and
```
define_method(:!) {} 
```
So, I decided to try the **`@!method`** directive (which appears on line 14 of the file.)
Here is a snippet from the file: 
```ruby
  class BasicObject

    # @!method !()
    # Negation of an object's boolean nature.
    #  The Ruby interpreter will call this method upon the object (or result of expression,) immediately following the **!** operator.
    #
    # @example
    #   no_key  = !dictionary.has_key?(:name)
    #   invalid = !model.valid?
    #   has_chars = !some_string.empty?
    #
    #  To explicitly call this method, you must use dot notation, or +send+ with the symbol +`:!`+ as an argument.
    #
    # @example
    #   no_key  = dictionary.has_key?(:name).!
    #   invalid = model.valid?.send(:!)
    #   has_chars = some_string.empty?.__send__(:!)
    #
    # @return [Boolean] true if itself evaluates to false or nil, otherwise false.


    # Not equal to. Test if two objects are not-equal.
    # @param other [Object] the other object to compare.
    # @return [Boolean] true if two objects are not-equal, otherwise false.
    def !=(other)
    end

  end
```

This is what spit out from YARD:
```
[error]: Unhandled exception in YARD::Handlers::Ruby::CommentHandler:
[error]:   in `ruby/2.0/!init_ruby_20.rb`:14:

        14:

[error]: ArgumentError: invalid empty object name
[error]: Stack trace:
        C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/yard-0.8.7.6/lib/yard/code_objec
ts/base.rb:168:in `new'
        C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/yard-0.8.7.6/lib/yard/tags/direc
tives.rb:401:in `create_object'
        C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/yard-0.8.7.6/lib/yard/tags/direc
tives.rb:359:in `after_parse'
        C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/yard-0.8.7.6/lib/yard/docstring_
parser.rb:264:in `block in call_directives_after_parse'
        C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/yard-0.8.7.6/lib/yard/docstring_
parser.rb:263:in `each'
        C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/yard-0.8.7.6/lib/yard/docstring_
parser.rb:263:in `call_directives_after_parse'
#... followed by a bunch of warnings about tag errors, unknown param names, etc.
# (just stuff that needs fixing.)
```
The negation method did not list on the doc page.

Ruby v2.0.0-p247
YARD-0.8.7.6

**Comment by DanRathbun** [comment]
I did not yet try to escape the **`!`** (bang) like:
```
# @!method \!()
```

.. the Yard guide says it works in docstrings.

**Comment by DanRathbun** [comment]
Tried the following instead of the **`@!method`** directive:
```ruby
    def @!()
    end
```
and this is the output:
```ruby
[warn]: Syntax error in `ruby/2.0/!init_ruby_20.rb`:(30,8): syntax error, unexpe
cted end-of-input
[warn]: ParserSyntaxError: syntax error in `ruby/2.0/!init_ruby_20.rb`:(30,8): s
yntax error, unexpected end-of-input
[warn]: Stack trace:
        C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/yard-0.8.7.6/lib/yard/parser/rub
y/ruby_parser.rb:545:in `on_parse_error'
        C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/yard-0.8.7.6/lib/yard/parser/rub
y/ruby_parser.rb:50:in `parse'
        C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/yard-0.8.7.6/lib/yard/parser/rub
y/ruby_parser.rb:50:in `parse'
        C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/yard-0.8.7.6/lib/yard/parser/rub
y/ruby_parser.rb:15:in `parse'
        C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/yard-0.8.7.6/lib/yard/parser/sou
rce_parser.rb:439:in `parse'
        C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/yard-0.8.7.6/lib/yard/parser/sou
rce_parser.rb:44:in `block in parse'
```
still no joy.

**Comment by lsegal** [comment]
> Tried the following instead of the @!method directive:

The SyntaxError you're seeing is coming from a real syntax error in Ruby. In other word, that's not legal Ruby code:

```sh
$ ruby test.rb
test.rb:1: `@!' is not allowed as an instance variable name
test.rb:1: syntax error, unexpected end-of-input
def @!()
     ^
```

I'm not entirely sure what a "mediocre error" is (a stack trace would help) but YARD should support any valid method without using directives, and in my tests it does. This worked for me:

```ruby
class Bar
  # docstring here
  def !()
  end
end
```

**Comment by lsegal** [comment]
The above commit resolves the specific issue with usage in a directive, but you shouldn't need directives since you can define the method directly.

**Comment by DanRathbun** [comment]
@lsegal wrote:
>  I'm not entirely sure what a "mediocre error" is (a stack trace would help)...

It was a different error, in a different YARD class.

BUT.. after a fresh reboot today, the error went away. So it must have been memory corruption from an earlier error.

So the lone "bang" method rendered correctly today, (even in Ruby 2.0.)

[*Offtopic* - I since installed the latest 2.1 and 2.2, just to run YARD under. I only have the specific patchlevel of 2.0 installed for testing & development, as SketchUp 2014 & 2015 come with that version/patchlevel specially tweaked "out of the box". (Which cannot be changed.) But I can use any Ruby version to generate the docs.]
