### ISSUE TITLE
Support ActiveSupport::Concern `included` as instance level documentation

### ISSUE THREAD

**Issue by phallguy** [lsegal/yard#869]
When documenting mixins that use ActiveSupport::Concern we have to move the documentation block to the top of the class instead of keeping paired with the definitions when defining attributes in the `included` block.

For example:

```
# Handles identifying and managing user interests.
module Interests
  extend ActiveSupport::Concern

    # @!attribute interests
    # @return [ActiveRecord::Relation] the user's identified interests.

  included do
    has_and_belongs_to_many :interests
  end
end
```

It would be great if we could keep the comments near the definition, but still have the docs generated properly. 

```
# Handles identifying and managing user interests.
module Interests
  extend ActiveSupport::Concern

  included do
    # @!attribute interests
    # @return [ActiveRecord::Relation] the user's identified interests.
    has_and_belongs_to_many :interests
  end
end
```

**Comment by lsegal** [comment]
A plugin could make this work fairly easily. If this were ever in YARD I'd rather make it more generic to inspect *any* class-level block by default. The only problem is that semantically this is not always realistic.

**Comment by phallguy** [comment]
Yep that makes sense - yard is pretty agnostic. I'd be happy with a plugin. Is there any way we could use something like the `@group` tag to just tell yard that everything in the block belongs at the instance level?

Though I suppose the biggest issue is actually having yard parse the contents of a block for documentation.

**Comment by olance** [comment]
Hey, I'd be happy to have a go at writing a plugin but I'm very new to YARD... do you have any idea as to how to do this @lsegal ?

**Comment by olance** [comment]
Well I actually do have something working! It was awesomely simple :)
Will be pushing  a plugin soon!

**Comment by olance** [comment]
There you go: https://github.com/digitalcuisine/yard-activesupport-concern

**Comment by phallguy** [comment]
Nice, thanks olance!

**Comment by olance** [comment]
Glad to help :)

**Comment by lsegal** [comment]
Seems like this can be closed, thanks for the work on this @olance!

**Comment by olance** [comment]
Well, thank you @lsegal for writing such a clear documentation and building a well-thought tool ;)
