### ISSUE TITLE
"Cannot resolve link to" warnings list parent file instead of child file.

### ISSUE THREAD

**Issue by DanRathbun** [lsegal/yard#870]
**"Cannot resolve link to" warnings list parent file instead of child file.**
```
[warn]: In file `RELEASE_NOTES.md':28: Cannot resolve link to ClassName#instance_method_name from text:
[warn]: ...{ClassName#instance_method_name}...
```
In the warning above,... the line number **28** is _correct_, but the markdown _filename is not_.

The file listed does not have the error at or near that line number, nor anywhere else.
The file is a "parent" file, that has the Introduction section, and a Build Number section with a small text note.

Following that is a **{include:file:build_number_tabel.html}** which works fine.
Afterward is a list of six lines like:
**{include:file:RELEASE_*YEAR*.md}**
Each markdown is for the yearly major version number release notes (and get included without problem, _along with my own mistakes_.)

The above error was actually in the 5th file down. Although the line number was correct, it took me several days to realize where the actual error was.

Some time (in the future,) YARD needs to keep track of what file it is walking/parsing as it digs down into child and grandchild files.

I just now thought of a workaround. Since the "parent" file renders without issue, I can comment it out of the opts file, and specifically list each child file, so they are parsed individually. That way the warnings correctly point me to the erroneous file(s).

When all is done, I'll put the opts back the way they were.

**Comment by lsegal** [comment]
> Some time (in the future,) YARD needs to keep track of what file it is walking/parsing as it digs down into child and grandchild files.

I don't have any plans to add this myself, but if you want to throw together a pull request I would happily take a look.

**Comment by DanRathbun** [comment]
I haven't the foggiest idea where in the yard codebase this work needs to be done.

Any helpful pointers ?

**Comment by lsegal** [comment]
https://github.com/lsegal/yard/blob/master/lib/yard/templates/helpers/base_helper.rb#L71 is a great place to start. Let me know if you need any extra pointers.

**Comment by DanRathbun** [comment]
**This old blog is still valid?** (I found via web search)
http://gnuu.org/2009/11/18/customizing-yard-templates/

**Comment by lsegal** [comment]
It is, but it's not exactly relevant to this specific issue.

**Comment by lsegal** [comment]
Closing out old issues.

I am marking this as closed since there are no plans to support this from my end. I would gladly look at a PR for this, if someone was interested in throwing one together.
