### ISSUE TITLE
Support for inclusion of YAML files in generated documentation

### ISSUE THREAD

**Issue by fabn** [lsegal/yard#871]
If I include a ruby file in any markdown file its content is included and highlighted as ruby code

```
{include:file:config/application.rb} # replaced by highlighted file content
```

If I include other type of files they are included as is

```
{include:file:config/application.example.yml} # File content parsed as markdown
```

I'd like to embed the content of `application.yml` into readme but currently it seems impossible.

Am I doing something wrong?

**Comment by lsegal** [comment]
YARD only supports syntax highlighting for Ruby files. You could write your own plugin to support highlighting for other types of files. This is a good place to look on how to do that:

https://github.com/lsegal/yard/blob/master/lib/yard/templates/helpers/html_syntax_highlight_helper.rb

Adding a method there could make things work.

**Comment by fabn** [comment]
I understand. Since this is not currently possible, I'd like to include the file as is (with no highlighting) however if I try to include it within a `<pre>` tag, with a \`\`\` or with four spaces indentation file is not included anymore, instead a literal `{include:file:config/application.example.yml}` appears in the document. Is it possible to bypass this in some way?

**Comment by lsegal** [comment]
YARD does not evaluate YARD-specific markup inside of code blocks, since those markups are explicitly meant for unescaped code. There's currently no way to switch this off.

The best way forward is definitely to write a plugin that embeds your markup and highlights appropriately.

**Comment by lsegal** [comment]
Closing out old issues.

I'm marking this as closed since a plugin is the best way forward. If the plugin works well, I would consider a PR that merged the functionality in, provided it is simple enough and does not bring in extra dependencies. If you have/had issues making this into a plugin, I would accept PRs that directly unblock any issues to that end, as well.
