### ISSUE TITLE
gem update w/ --prerelease ?

### ISSUE THREAD

**Issue by DanRathbun** [lsegal/yard#872]
I wish to update to the latest commit.
I thought the following might work:
**`gem update yard  --prerelease`**
or
**`gem update yard-0.8.7.6  --prerelease`**
but it gives "nothing to update".

How do I get the latest commit into my gem directory ?

**Comment by DanRathbun** [comment]
I ended up just d/l'g the ZIp and manually copying it, as I kept getting an invalid gemspec error trying to have gem.bat install it.

**Comment by lsegal** [comment]
If you want to use the Git repository you should rely on [Bundler](http://bundler.io/) and point your Gemfile at the repository directly. RubyGems don't map to Git commits.

**Comment by lsegal** [comment]
Marking as closed since there is no way to install a RubyGem from Git source.

**Comment by DanRathbun** [comment]
... which I found out when I tried to use the **-s** source param with the **gem** command.

It gave me some message like "no gem package found" or whatever.

**Comment by DanRathbun** [comment]
@lsegal said:

> If you want to use the Git repository you should rely on **Bundler** ...

**Bundler is Cool!** Didn't know about it.

**`gem install bundle`** went okay.

@lsegal said:

> ... and point your Gemfile at the repository directly.

Well it was your Gemfile. For any reader's info, I modified it to add the **git source url** to the "**development**" group, leaving the common gem source as the rubygems server.
From the top of the "GemFile" (in the root of the YARD project) :
```ruby
source 'https://rubygems.org'

group :development do
  gem 'yard', :git => 'https://github.com/lsegal/yard.git'
  gem 'rspec', '= 2.12'
  gem 'rake'
  gem 'rvm-tester'
  gem 'simplecov'
  gem 'samus'
end
```
... _and the rest of the "GemFile" continues_ ...

Switched to the the yard gem root. (Others who are collaborating on YARD might keep their projects else where.)

Tried **`bundle install`**: 
... but then I had issues with Git only being setup while the GitHub Win client is running. 
Had to read this: https://help.github.com/articles/set-up-git/
In order to configure Git Shell...
It creates a PowerShell script at **`%LocalAppData%/GitHub/shell.ps1`**
The paths are unique for every user, for security reasons.

I mimicked all the commands in it's powershell script, in a normal "cmd" batch script. 
(My machine was configured to not run Powershell scripts for security purposes, and I had no desire to waste hours learning about MS Powershell. _Never have found the time, nor had the desire_.) Now I have a cmd script to run from my path, that sets environment vars and the **`%PATH%`** for using Git from the shell.

Tried **`bundle install`** again ... seemed like it was working.. then it choked trying to compile the  RedCloth gem.

Seems I had forgotten to configure the DevKit64 on the two latest Ruby installations...
... got that done (after relearning how to do that.)
Ie, switch to "`C:/DevKt64`"
**`ruby dk.rb init`
`ruby dk.rb install`**

The first time bundler choked installing RedCloth, it recommended (after properly configuring the Ruby Development Kit,) to install that alone as a test, ie:
**`gem install RedCloth-4.2.9`**
... which I did, and it went fine once Ruby 2.2 had access to DevKit64.

Finally the **`bundle install`** whilst in the gem folder seems to have worked:
```shell
C:\Ruby22-x64\lib\ruby\gems\2.2.0\gems\yard-master>bundle install
Updating https://github.com/lsegal/yard.git
Fetching gem metadata from https://rubygems.org/.......
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.4.2
Using RedCloth 4.2.9
Installing asciidoctor 1.5.2
Installing diff-lcs 1.1.3
Installing docile 1.1.5
Installing locale 2.1.1
Installing text 1.3.1
Installing gettext 3.1.6
Installing json 1.8.2
Installing mob_spawner 1.0.0
Installing rack 1.6.1
Installing rspec-core 2.12.2
Installing rspec-expectations 2.12.1
Installing rspec-mocks 2.12.2
Installing rspec 2.12.0
Installing rvm-tester 1.1.0
Installing samus 1.4.3
Installing simplecov-html 0.10.0
Installing simplecov 0.10.0
Using yard 0.8.7.6 from https://github.com/lsegal/yard.git (at master)
Using bundler 1.9.9
Bundle complete! 12 Gemfile dependencies, 21 gems now installed.
```

Now, to write a cmd script to do this via a double-click. ...

**P.S.** This could added as a FAQ answer on the repo wiki, or where ever...
