### ISSUE TITLE
Overloading docs for various rubies

### ISSUE THREAD

**Issue by nepalez** [lsegal/yard#873]
Is this a conventional way to overload docs for various ruby versions (or another context)? M.b. something like `@context` needed?

The use case is the following:

```ruby
# ...
# @context rubies 2.1-
#   @raise [ArgumentError]
#
# @context rubies 2.2+
#   @raise [UncaughtThrowError]
#
def do_something
  # ...
  throw :done_something
end
```

**Comment by lsegal** [comment]
The following should be fine:

```ruby
# @raise [UncaughtThrowError, ArgumentError]
```

There's no need to model Ruby interpreters differently. If you find yourself actually needing this, your API might be the problem. This seems like a very special case.

**Comment by nepalez** [comment]
Thank you! Will do this :)

**Comment by lsegal** [comment]
Also note that you can use multiple individual `@raise` tags that each explain their context in the description, i.e., "only raised in Ruby 2.2+".
