### ISSUE TITLE
Using @!attribute + @api = readonly attribute

### ISSUE THREAD

**Issue by mainameiz** [lsegal/yard#874]
Consider I have these lines:

```
# @!attribute [rw] state
#   @api v2
#   @return [String] Текущее состояние проекта.
```

![_038](https://cloud.githubusercontent.com/assets/393611/7810382/22f9b17a-03aa-11e5-9686-8e798aa2f814.jpg)

Making attribute readwrite explicitly doesn't work. Otherside making it only writable works just fine.

**Comment by lsegal** [comment]
Cleaning up old issues, sorry for lack of response.

I can't reproduce this. The snippet seems to be incomplete, but presumably you have an `attr_accessor` somewhere after the directive. This is likely what is toggling the attribute to be writable again. If you are using `attr_*`, put your documentation there and *do not* use a directive. Directives are meant for when `attr_*` DSL syntax cannot be used (attributes are dynamically created).
