### ISSUE TITLE
Specifying base url

### ISSUE THREAD

**Issue by jbodah** [lsegal/yard#875]
Not sure if this is the correct place for this or not, but I'm trying to use nginx to serve as a reverse proxy to create a tools server. What I'd like to do is have the `/yard` route map to the yard server.

Right now I have this working fine for reaching the server, however all of the routes coming from the server; navigating to `/yard` correctly hits the server and returns the response. The issue is that all of the paths for assets and links are broken now (for example, the `.js` files are trying to hit `/js` instead of `/yard/js`).

Does yard have a parameter for specifying a base url?

**Comment by lsegal** [comment]
There's no command-line switch for this, but there's a couple of programmatic APIs you could plug into with a plugin/extension.

This is how we do it in Rubydoc.info: https://github.com/lsegal/rubydoc.info/blob/master/lib/extensions.rb#L7-L28

**Comment by jbodah** [comment]
Just going to use redirects. Sub-uri's seem like too much of a pain. Thanks for the link though!
