### ISSUE TITLE
Method aliases not shown in "Methods inherited from" section

### ISSUE THREAD

**Issue by holtrop** [lsegal/yard#876]
Given the following test file:

    class Foo
      def bar; end
      alias_method :baz, :bar
    end
    class Bar < Foo
    end

The YARD documentation page for the Foo class will list "Also known as: baz" for the bar method so YARD is aware of the method alias. However, the "Methods inherited from Foo" section of the Bar class documentation page only lists #bar and not #baz. It would be very helpful if #baz was listed as well.

**Comment by lsegal** [comment]
Closing out old issues.

This is a relatively low priority feature, so unfortunately I will be marking it as WontFix. That said, if someone was interested in making this work, I would accept this as a PR.
