### ISSUE TITLE
yard server: SystemStackError when {render:...} is used

### ISSUE THREAD

**Issue by mherold** [lsegal/yard#877]
When running `yard server` and trying to display a file which has a `{render:...}` statement, I get:

```
ERROR SystemStackError: stack level too deep
    [...]/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rdoc/markup/attribute_manager.rb:133:in `convert_attrs'
```

`yard doc` works fine with it. Using yard 0.8.7.6. I tried different setup scenarios (ruby/rdoc versions, different server), always the same. Any ideas?

**Comment by MSP-Greg** [comment]
I found the same issue when using the following in an md file --

{render:ConstantTemplateCode.length_1}

Works fine using yard doc, but stops the server.

First few lines of error info --

Unexpected error while processing request: stack level too deep
	C:/Ruby22/lib/ruby/gems/2.2.0/gems/yard-0.8.7.6/lib/yard/templates/helpers/markup_helper.rb:155:in `markup_class'
	C:/Ruby22/lib/ruby/gems/2.2.0/gems/yard-0.8.7.6/lib/yard/templates/helpers/html_helper.rb:59:in `html_markup_markdown'
	C:/Ruby22/lib/ruby/gems/2.2.0/gems/yard-0.8.7.6/lib/yard/templates/helpers/html_helper.rb:41:in `htmlify'
	C:/Ruby22/lib/ruby/gems/2.2.0/gems/yard-0.8.7.6/templates/default/layout/html/setup.rb:65:in `diskfile'

**Comment by lsegal** [comment]
What is in `ConstantTemplateCode.length_1`?

A fully reproducible example would help, or, at the very least, a full stack trace. It's hard to debug based on incomplete stack traces and examples.

**Comment by MSP-Greg** [comment]
Loren,

That's a class method in a module that is included in my .yardoc database. The render line appears in an .md file.

Browsing the files generated by yardoc, everything is fine.

Running server, I can view the module and class method.  When I try to view the .md file that includes the render line, server throws errors non-stop.

I assume you'd get a similar issues (running server) if you included the following as a line in an .md file.

{render:YARD::Parser::SourceParser.parse_string}

I piped server output to a file.  By the time I shut down server, it was 871 KB.

I can attached that file if you think it would be helpful.

**Comment by MSP-Greg** [comment]
Yesterday (writing code & football) I read

'What is in'
as
'What is'

Sorry.  I'll see if I can come up with a pair of simple files (rb & md) that cause the error.

Greg

**Comment by lsegal** [comment]
@MSP-Greg the `{render:YARD::Parser::SourceParser.parse_string}` example was indeed able to reproduce an issue, though it hangs without the stack error, so I'll have to dig some more to actually get to the root cause. Thanks though!
