### ISSUE TITLE
Cannot skip parsing png file

### ISSUE THREAD

**Issue by marlinpierce** [lsegal/yard#879]
I saved an ER diagram to a .png file and added it to my --files list.  However, yard is generating errors and potentially unpredictable behavior because it is scanning the .png file for links and markup.  How can I indicated to yard that this is a binary file so it will not try to parse it?

**Comment by lsegal** [comment]
@marlinpierce using `--files` is explicitly meant to parse file contents. You're probably looking for the `--asset` option to copy any extra image assets over to your doc/ directory after generation.
