### ISSUE TITLE
Only use given markup provider for markdown format

### ISSUE THREAD

**Issue by mvz** [lsegal/yard#881]
After struggling with getting GFM to work and looking at issues like #404, it seems `--markup-provider` will set the provider for all formats and completely bypass YARD's format detection. This means you cannot have RDoc formatted code comments **and** specify the markdown formatter for the README.md (See also this comment: https://github.com/lsegal/yard/issues/404#issuecomment-2879937).

Since markdown is the only format that has different providers (see https://github.com/lsegal/yard/blob/295a15a23e6c9341d3425246c9efd7680d2131b5/lib/yard/templates/helpers/markup_helper.rb#L23), I think the markup provider loading should only use the provider set by `--markup-provider` if the format is markdown.

Ideally, once several formats have more than one provider, it should be possible to set a different provider for each such format.

**Comment by lsegal** [comment]
> After struggling with getting GFM to work

To quickly short-circuit this, note that GFM is supported out of the box in YARD. #404 is a very old issue and is no longer applicable. If you have `rdiscount` installed, YARD will prefer that library over others and work correctly.

The solution here is simply to install a GFM supported library like rdiscount and do not use `--markup-provider` option. This option is only necessary if you want to override YARD's default-- in this case you do not.

**Comment by mvz** [comment]
>  If you have rdiscount installed, YARD will prefer that library over others and work correctly.

Right. It turns out I had neither rdiscount nor redcarpet installed. Thanks!
