### ISSUE TITLE
Backticks containing HTML snippets mangled in summaries

### ISSUE THREAD

**Issue by csuhta** [lsegal/yard#883]
Using the Markdown format, I have a function documentation comment that starts with:

```ruby
# Returns an `<i>` tag
```

This is how it renders in the documentation:

![jfhj7](https://cloud.githubusercontent.com/assets/769083/8333140/a8840fd6-1a5f-11e5-9d81-4567d15192fb.png)

But in the summary, the `<code>` tag is mangled:

![l3gg4](https://cloud.githubusercontent.com/assets/769083/8333129/9aa9397c-1a5f-11e5-82f2-9ea2f3ea47fb.png)

![svnuc](https://cloud.githubusercontent.com/assets/769083/8333160/bc17b2b4-1a5f-11e5-9a2f-b294912ceafb.png)

```
$ yard --version
yard 0.8.7.6
```

**Comment by lsegal** [comment]
This has to do with the fact that HTML tags are stripped out of docstring summaries because they wreak all sorts of havoc on rendering-- unfortunately it's not possible for YARD to know what HTML tags are being escaped by markdown or other markup syntaxes at that layer.

**Comment by lsegal** [comment]
Closing as WontFix since it is too low priority. If you can find a way to fix this without encoding markup specific logic into the summary generation code, I would accept a PR.
