### ISSUE TITLE
attr_accessible not taken into account

### ISSUE THREAD

**Issue by patfrat** [lsegal/yard#884]
Hello

Using ActiveRecord on one of my project if i document my model's attr_accessible attributes with @!attribute directive, the getter is ok but not the setter

```ruby
# @!attribute my_attr
#   My description
#   @return [Type] What it returns
```
Setter documented but getter not (my_attr=)
Appears in --list-undoc list

Trying to add it manually

```ruby
# @!attribute [r] my_attr
#   My description
#   @return [Type] What it returns
# @!attribute [w] my_attr=
#   Set my attr
```
Setter ok
Getter not good: it appears with my_attr== on documentation

How to correctly document attr_accessible ?
Thank you in advance

**Comment by lsegal** [comment]
> How to correctly document attr_accessible ?

The correct way to document an `attr_accessible` is the same way you would document an `attr_accessor`:

```ruby
# @!attribute
# @return [Type] this attribute blah blah
attr_accessible :foo, ...
```

That's it. See the [Documenting DSL Methods](http://www.rubydoc.info/gems/yard/file/docs/GettingStarted.md#Documenting_DSL_Methods) section in the Getting Started guide for information.

> Setter documented but getter not (my_attr=)
> Appears in --list-undoc list

This is an unrelated issue. If you're explicitly defining a `my_attr=` method without attaching docstring comments to that `def my_attr=` method, it will show up without documentation in your doc list. Please don't rely on the `--list-undoc` information to provide an authoritative list of what shows up in your generated HTML documentation; it is simply a tool to determine which objects do not have explicit docstrings attached. If you don't want to see this in your list you can add placeholder comments to the definition:

```ruby
# @see #my_attr
def my_attr=(v) ... end
```

And now YARD won't complain.
