### ISSUE TITLE
RDoc links cannot parse obfusticated email addresses

### ISSUE THREAD

**Issue by postmodern** [lsegal/yard#887]
### README.rdoc:

    * {Email}[mailto:postmodern.mod3 at gmail.com]

### Output

    $ yardoc
    [warn]: In file `README.rdoc':10: Cannot resolve link to Email from text:
    [warn]: ...{Email}...
    $ yard --version
    yard 0.8.7.6

**Comment by lsegal** [comment]
This is an issue with RDoc. The link isn't valid RDoc syntax.

http://docs.ruby-lang.org/en/2.1.0/RDoc/Markup.html

Looks like you can't have spaces in the URL portion. Might want to use + or %20.

**Comment by postmodern** [comment]
`%20` fixed it. Submitted a bug to rdoc as well. Thanks!
