### ISSUE TITLE
ArgumentError in VisibilityHandler on private method with gsub

### ISSUE THREAD

**Issue by akostadinov** [lsegal/yard#888]
Using ruby 2.2.2 and yard 0.8.7.6

Here's my method:
```
    private def ssh_opts(opts)
      ssh_opts = {}
      properties.each { |prop, val|
        if prop.to_s.start_with? 'ssh_'
          ssh_opts[prop.to_s.gsub(/^ssh_/,'').to_sym] = val
        elsif prop == :user
          ssh_opts[:user] = val
        end
      }
      ssh_opts.merge! opts

      return ssh_opts
    end
```

If I remove the gsub line, then all works fine. But in the way it is written above, I'm getting:
```
[error]: Unhandled exception in YARD::Handlers::Ruby::VisibilityHandler:
[error]:   in `lib/host.rb`:406:

	406: private def ssh_opts(opts)

[error]: ArgumentError: invalid empty object name
[error]: Stack trace:
	/home/avalon/.gem/ruby/gems/yard-0.8.7.6/lib/yard/code_objects/base.rb:168:in `new'
	/home/avalon/.gem/ruby/gems/yard-0.8.7.6/lib/yard/handlers/ruby/visibility_handler.rb:20:in `block (2 levels) in <class:VisibilityHandler>'
	/home/avalon/.gem/ruby/gems/yard-0.8.7.6/lib/yard/parser/ruby/ast_node.rb:209:in `block in traverse'
	/home/avalon/.gem/ruby/gems/yard-0.8.7.6/lib/yard/parser/ruby/ast_node.rb:208:in `each'
	/home/avalon/.gem/ruby/gems/yard-0.8.7.6/lib/yard/parser/ruby/ast_node.rb:208:in `with_index'
	/home/avalon/.gem/ruby/gems/yard-0.8.7.6/lib/yard/parser/ruby/ast_node.rb:208:in `traverse'
```

Couldn't find out why is it like that and couldn't find any workarounds.

**Comment by lsegal** [comment]
> Couldn't find out why is it like that and couldn't find any workarounds.

Because this syntax is not yet supported in YARD. Marking this as a feature request.

**Comment by akostadinov** [comment]
The interesting thing is that if I remove `gsub(/^ssh_/,'')`, not the whole line, I don't see any such errors. If I remove the `private` keyword, I don't see such error. I mean, why should `gsub` have anything to do with it? I have a lot of `private def ...` definitions.

**Comment by lsegal** [comment]
> I have a lot of private def ... definitions.

Most likely your other `private def` definitions are being ignored by YARD. As for removing the `grep()`, it's very possible that some of your method body may be throwing off the parser to raise the exception, but this is precisely due to lack of support for this syntax, not some other reason.

**Comment by jessebs** [comment]
It's probably the same fix, but sub has the same problem.
