### ISSUE TITLE
Rake task for testing if documentation complete

### ISSUE THREAD

**Issue by joerg** [lsegal/yard#890]
I'd find it awefully helpful to have a Rake task ready for checking if 100% of my project is documented. This task could also be executed by some CI server like Jenkins or Bamboo. Having a complete documentation is in my eyes a requirement for a successful build.
My Rake task doing this currently looks like this:
```
begin
  require 'yard'
  desc 'Run yard documentation checks'
  task :yard do
    stdout_str, _stderr_str, status = Open3.capture3("yard stats")
    fail 'Generating docs failed' unless status == 0
    # Match if >0 undocumented or <100% documented is found in output
    if stdout_str.match(/[1-9]+ undocumented/) || stdout_str.match(/^\s*[0-9]{1,2}(\.[0-9]{1,2})*% documented/)
      puts stdout_str
      fail "The project is not fully documented. Check with 'yard stats'"
    end
  end
rescue LoadError
  puts '>>>>> Yard gem not loaded, omitting tasks' unless ENV['CI']
end
```
With this .yardopts file
```
--no-output
--no-cache
--list-undoc
--exclude ./test/*
--exclude ./spec/*
--exclude ./*_spec.rb
--exclude ./*matchers.rb
./**/*.rb
```

**Comment by lsegal** [comment]
The output of `yard stats --list-undoc` will list undocumented methods, you can check for empty output there.

You can also do this without a subprocess:

```ruby
require 'yard'

# ideally you've already generated the database to .load it
# if not, have this task depend on the docs task.
YARD::Registry.load
objs = YARD::Registry.select do |o|
  # your rules for what "undocumented" means here,
  # possibly just:
  o.docstring.blank? 
end
raise "undocumented methods" unless objs.empty?
```

**Comment by lsegal** [comment]
I will also add that, in practice, breaking your build on a non-functional check incentivizes you to find the quickest solution to solve the problem, and the quickest solution is rarely "correct documentation". More realistically, it will involve tricking your "blind" coverage tool into thinking everything is fine, which usually means adding things like `# TODO document this later`, or even the more insidious `# split will split a string.`.

If it's failing at CI, it's too late. It means you failed to incorporate documentation in your development cycle from the start. This stuff should be in your unit tests if you care that much about it, IMO.

**Comment by lsegal** [comment]
Marking as WontFix. YARD is not a coverage tool, but you can certainly write YARD plugins that are!
