### ISSUE TITLE
Cannot include square brackets in @overload method signature

### ISSUE THREAD

**Issue by xaviershay** [lsegal/yard#893]
While documenting the `.[]` method for an array-like, I wanted to do the following: 

```
@overload vector[index]
  @param index [Integer] The index to retrieve
@overload vector[start..end]
  @param range [Range] Range of indexes to retrieve
```

`[index]` and `[start..end]` are stripped out in rendering. The [documentation](http://www.rubydoc.info/gems/yard/file/docs/Tags.md#overload) doesn't appear to preclude this.

I tried various methods of escaping (e.g. `\[`) but couldn't find one that works.

Is there a way to do this?

**Comment by lsegal** [comment]
There isn't a way currently but I wouldn't be opposed to adjusting the overload syntax to support it.

**Comment by lsegal** [comment]
Closing out old issues.

I'm marking this as closed since there are no plans to implement this on my end, but if someone put together a PR I would take a look!
