### ISSUE TITLE
Asset files in custom templates not loading when using yard server

### ISSUE THREAD

**Issue by mcmire** [lsegal/yard#901]
I'm using a custom template with YARD. My file structure looks like this:

```
doc_config/
`- yard/
   `- templates/
      `- default/
         `- fulldoc/
            `- html/
               `- css/
                  `- some_file.css
               `- js/
                  `- some_file.js
               `- setup.rb
   `- setup.rb
```

I am using the `-e` option inside of `.yardopts` to load a custom `setup.rb` file that adds `doc_config/yard/templates/` to the template path:

```
-e ./doc_config/yard/setup.rb
```

And here is what `setup.rb` does: 

``` ruby
YARD::Templates::Engine.register_template_path(File.dirname(__FILE__) + '/templates')
```

Additionally, the `default/fulldoc/html` folder also contains a setup.rb file that adds some stylesheets and JavaScript files to the layout:

``` ruby
def stylesheets
  %w(css/some_file.css) + super
end

def javascripts
  %w(js/some_file.js) + super
end
```

When I run `yard server` and go to http://localhost:8808, I see none of my styles, only the default styles.
If I go to the console in the browser I see errors like:

```
X  GET http://localhost:8808/css/some_file.css
X  GET http://localhost:8808/css/some_file.js
```

I spent the better part of today investigating this and here is what I found:

* `doc_config/yard/setup.rb` is actually loaded twice for some reason, I'm not sure why
* When the server sees a request for `GET /`, it will [translate this into a request for the main page](https://github.com/lsegal/yard/blob/da5122b1cfebdf93148b8f05f2855a037b04a606/lib/yard/server/router.rb#L142) and then [forward the request object onto to a Server::Commands::DisplayObjectCommand object](https://github.com/lsegal/yard/blob/da5122b1cfebdf93148b8f05f2855a037b04a606/lib/yard/server/router.rb#L132)
* Server::Commands::DisplayObjectCommand inherits from Server::Commands::LibraryCommand
* `Server::Commands::LibraryCommand#call` ultimately passes control up to [`Server::Commands::Base#call`](https://github.com/lsegal/yard/blob/da5122b1cfebdf93148b8f05f2855a037b04a606/lib/yard/server/commands/base.rb#L88) which builds a response based on `#run` (implemented by Server::Commands::DisplayObjectCommand in this case)
* `Server::Commands::LibraryCommand#call` will [load `.yardopts` before handling the request](https://github.com/lsegal/yard/blob/da5122b1cfebdf93148b8f05f2855a037b04a606/lib/yard/server/commands/library_command.rb#L98), so if this method is ever called twice, then `.yardopts` will be parsed/evaluated twice
* Most importantly, `Server::Commands::LibraryCommand#call` [saves the global `template_paths` array before loading `.yardopts` and then restores it after building the response](https://github.com/lsegal/yard/blob/da5122b1cfebdf93148b8f05f2855a037b04a606/lib/yard/server/commands/library_command.rb#L98).
* This is problematic, because that means whatever `.yardopts` adds is thrown away for future requests, which means adding new template paths via `.yardopts` is pointless.
* You might think, what if a request for an asset comes in -- won't that trigger the above logic and thereby add new template paths before that asset is served? No, because if Server::Router looks at the incoming path and doesn't know what to do with it, it [delegates the request to Server::Commands::StaticFileCommand](https://github.com/lsegal/yard/blob/da5122b1cfebdf93148b8f05f2855a037b04a606/lib/yard/server/router.rb#L57) instead of using LibraryCommand.

Given all of this, is this a bug or by design? Is there a better way to add a new template path than by adding it through `.yardopts`?

I'm using YARD 0.8.7.6 on Ruby 2.2.2, for what it's worth. (I feel like this worked on a past YARD or Ruby version and now it doesn't work anymore.)

**Comment by lsegal** [comment]
Sorry for the really late reply,

The short answer was this was partially by design, but ultimately the StaticFileCommand being unrelated to LibraryCommand meant all static files were shared. I just pushed a change which makes it so all static files are now served relative to their library. Not only does this allow your use case to work as-is, but it fixes a long-standing issue where multiple projects would clobber each other's template customizations due to the way caching works.

The behavior w.r.t. resetting template paths is by design though-- that needs to stay, otherwise each library would overwrite template customizations for subsequent requests.
