### ISSUE TITLE
Signature for initialization functions

### ISSUE THREAD

**Issue by thomthom** [lsegal/yard#909]
I am looking into switching the documentation for our C based Ruby API to use YARD. However, I ran into an obstacle: The signature of the functions being scanned - they are all assumed to be `void`.

What we do is have a function for each class we define, but some are nested inside of modules. our functions then look like this:

```
// base.cpp
VALUE InitBase() {
  VALUE mBase = rb_define_module("Base");
  // ...
  return mBase;
}
```

```
// foo.cpp
VALUE InitFoo(VALUE parent) {
  VALUE cFoo = rb_define_class_under(parent, "Foo");
  // ...
  return cFoo;
}
```

Then we have the main init function:

```
#include "base.cpp"
#include "foo.cpp"

void InitializeAPI() {
  VALUE mBase = InitBase();
  VALUE cFoo = InitFoo(mBase);
}
```

Simplified off course - but it's the gist of it. Our problem is that the parse doesn't scan our functions.
https://github.com/lsegal/yard/blob/master/lib/yard/handlers/c/init_handler.rb#L3

I was wondering if there could be a way to adjust to this. We'd be happy to assist on doing this work, but I just want to check if such a change would be accepted.

Could change the signature to allow for either `void` or `VALUE` return type (with possible function parameters).

Then the second question would be, how can YARD handle the case of how we define modules/classes wrapped under another namespace - since we pass in the parent namespace as an argument. Would there have to be some magic comment to the `rb_define_class/module_under` to tell YARD what namespace it's really under?

(Apologies if there is a solution for this already - in which case I will have failed completely to find it.)

**Comment by thomthom** [comment]
So in a quick test - allowing VALUE return type seemed easy. (Being a complete n00t to the YARD code base.)

It allowed YARD to quickly pick up on our C/C++ defined functions.

Though it failed to document most of them because it couldn't resolve the parent.  I guess it's because our real world code base use generic variable name for the parent argument.

This won't work:

```
// base.cpp
VALUE InitBase() {
  VALUE mBase = rb_define_module("Base");
  // ...
  return mBase;
}
```

```
// foo.cpp
VALUE InitFoo(VALUE parent) {
  VALUE cFoo = rb_define_class_under(parent, "Foo");
  // ...
  return cFoo;
}
```

This will work:

```
// base.cpp
VALUE InitBase() {
  VALUE mBase = rb_define_module("Base");
  // ...
  return mBase;
}
```

```
// foo.cpp
VALUE InitFoo(VALUE mBase) {
  VALUE cFoo = rb_define_class_under(mBase , "Foo");
  // ...
  return cFoo;
}
```

I guess we could go around and rename things in our code base. Though, is there some mechanism already to acocunt for this? Some way to tag the parent argument for `rb_define_*_under`?

**Comment by lsegal** [comment]
> Though, is there some mechanism already to acocunt for this? Some way to tag the parent argument for rb_define_*_under?

YARD does not support tagging variables (right now), it relies on the convention that class/module vars are named consistently throughout the Init method.

As for Init methods (and #910) in particular, you should be naming the init method of each module as:

```c
void Init_MyModName() { ... }
```

This is the expected signature that [Ruby's ABI uses](http://phrogz.net/programmingruby/ext_ruby.html) and the only one that would be supported by YARD. Specifically, you should not be returning things from an Init method, and you should never be calling the Init method yourself, as Ruby manages this for you.

Typically if you want to share a mod/class definition across other modules / implementations, you would mark the `mFoo` variable as extern as is done [in the Ruby source](https://github.com/ruby/ruby/blob/832c74f428db6c5bd6e575e1f6ea7fe0891c84d2/ext/bigdecimal/bigdecimal.h#L104).

**Comment by thomthom** [comment]
Right, yes - I have omitted the part where we're not actually writing C Extensions, but embedding the Ruby interpreter into our applications to provide an Ruby API. So we don't have the regular init functions a Ruby C Extension would have. We initialize the Ruby interpreter then call a set of functions that define the modules and classes that makes up our API that grants access to our application.

I saw some code out there where the "Init" function delegated to other functions to create multiple modules and classes - which was similar to what we do. We just don't have that global `Init_` function.

We've always been a bit of an edge case when it come to Ruby. And I understand if it doesn't make sense to accommodate that into YARD. I just though the parser looked for generic functions, with the "Init" part being optional in the regex that searched for it.

We could always just fork YARD and tweak it to fit, though at the expense of maintenance every time YARD updates. Would that method signature be something we could customize without forking? Would it be possible via the plugin system?

**Comment by lsegal** [comment]
> Would it be possible via the plugin system?

Yes, you could absolutely write your own handler to look for whatever you want to in the parse tree. It's how all the C file processing is done (including the init file you were playing with). Anything extending from `YARD::Handlers::C::Base` will get executed.

**Comment by lsegal** [comment]
Incidentally, you could also emulate this with a few `@!parse` directives:

```c
/**
 * @!parse [ruby] class A::MyClass < MySuperClass; end
 */
```

Though I'm not sure if that will help to correctly wire up any methods defined on the class.

**Comment by thomthom** [comment]
I'm guessing the `@!parse` directive would require to stub out all classes/modules and their methods in the special directive comment?

I think I'll poke into the plugin system and see if making a special parser plugin for our code. Sounds like the most attractive solution right now - if that lets YARD pick up our custom init functions. We might end up tweaking the source somewhat such that the parent class/module is picked up. If that leads to trouble in terms of the current code base have to explore other options (maybe that can be addressed with custom directive in plugin-form?)

Thanks for taking the time to respond. Getting our API docs generated with YARD has been a long standing wish. About time we got that done. :)

**Comment by thomthom** [comment]
Do `!@parse` directives work in C files? Or am I trying to use it incorrectly?

```
// Hello This
void Init_ThisThing() {
  g_rbBiz = rb_define_class("ThisThing", rb_cObject);
}

/**
 * Hello That
 * @!parse [ruby] class ThatThing; def foo; end; end
 */
```

In the snippet above only `ThisThing` is added to the docs.
