### ISSUE TITLE
Yard changes the visibility on the wrong methods when using `protected def` and friends

### ISSUE THREAD

**Issue by miquella** [lsegal/yard#911]
Because of a change in Ruby 2.1's parser, it is now possible to use the return value of `def` (a symbol matching the name of the method defined) as an argument to another method, such as a visibility modifier.

Unfortunately, Yard handles this new behavior incorrectly. When a `def` is prefixed by a visibility modifier (e.g. `protected def`), Yard appears to mark the first symbol found (even if its in the method's body) as the method that is protected.

For example:
```ruby
class YardTest
  # Documentation for #my_method.
  def my_method
  end

  protected def other_method
    :my_method
  end
end
```
The method `#my_method` is public and should be shown as such in Yard. However, Yard shows this method as protected.

Two workarounds for this are:

1. Change the symbol inside `#other_method`. For example:
  ```ruby
  class YardTest
    # Documentation for #my_method.
    def my_method
    end
  
    protected def other_method
      :something_else
    end
  end
  ```

2) Move the `protected` visibility modifier to its own line. For example:
  ```ruby
  class YardTest
    # Documentation for #my_method.
    def my_method
    end
  
    protected
    def other_method
      :my_method
    end
  end
  ```

**Comment by lsegal** [comment]
This is a known issue and YARD does not yet support this syntax. There is an old PR in #773 but I admittedly dropped the ball in reviewing and merging it in. You might want to try out that branch and see if it works for you.

**Comment by lsegal** [comment]
This is supported as of v0.9.0.
