### ISSUE TITLE
Missing methods

### ISSUE THREAD

**Issue by thomthom** [lsegal/yard#913]
In an effort to make YARD document our Ruby API written in C - originated a long time ago, I find that some methods fail to document.

```
// foo.cpp
void Init_Foo(VALUE module) {

  g_rbFoo = rb_define_class("Foo", rb_cObject);

  rb_define_method(g_rbFoo, "hello", VALUEFUNC(_wrap_hello),
    0);

  rb_define_method(g_rbFoo, "world", VALUEFUNC(_wrap_world)
                   , 0);
}
```

The generated docs only output `hello`, but not `foo`:

![image](https://cloud.githubusercontent.com/assets/192418/11120478/39715350-8950-11e5-8150-6ccdcf927b07.png)

I thought it might be the parsing regex (https://github.com/lsegal/yard/blob/master/lib/yard/handlers/c/method_handler.rb), but when I test it, it appear to be able to pick out both methods:

![image](https://cloud.githubusercontent.com/assets/192418/11120489/595f264c-8950-11e5-81fe-6ad5d8a79998.png)

So I'm lost to why `world` isn't documented. Our API have thousands of methods, many have that weird formatting of a comma on the next line. So many that it's worth it for us trying to figure out how to make the parser read it rather than reformat all the source code. But I got stuck at this point.

(What are the tools you use when debugging how YARD parses a file? I tried `--debug`, but that didn't provide any clues to why `world` was skipped.)

**Comment by thomthom** [comment]
`yard list` shows that YARD only knows about `Foo#hello`.

```
yard list
:: Foo#hello
foo.cpp:3: Foo
```

**Comment by lsegal** [comment]
Is it always only documenting the first method in the block? If so, I have a few theories.

**Comment by thomthom** [comment]
Sorry, I wasn't entirely clear in my original post. The order of the methods doesn't matter, if I swap it out like this:

```
void Init_Foo(VALUE module) {

  g_rbFoo = rb_define_class("Foo", rb_cObject);

  rb_define_method(g_rbFoo, "world", VALUEFUNC(_wrap_world)
                   , 0);

  rb_define_method(g_rbFoo, "hello", VALUEFUNC(_wrap_hello),
    0);
}
```

Then the results is still the same.

It appear that the position of the comma makes a difference. If it is placed on the first line then the method is document, but it's been placed (oddly) such that it's first on the second line the method isn't documented.

**Comment by lsegal** [comment]
I'm not sure I'm able to reproduce this. When I run YARD against the code you provided (in both method orders) I get 2 methods documented:

```
Files:           2
Modules:         0 (    0 undocumented)
Classes:         1 (    1 undocumented)
Constants:       0 (    0 undocumented)
Methods:         2 (    2 undocumented)
 0.00% documented
```

Is there something else in the code that might be tripping this up?

**Comment by thomthom** [comment]
hmm... that's strange. That snipped is the only thing in the file.

Which version are you using? Dev build? As far as I can tell I have the latest release gem installed. On both my work and home computer I only see one method documented:

![2015-11-15_03h40_17](https://cloud.githubusercontent.com/assets/192418/11166878/9c46f61e-8b4a-11e5-844e-eddfc53117ec.png)

**Comment by lsegal** [comment]
I'm running off of the master branch. It's very possible that a relevant bug was fixed recently.

**Comment by thomthom** [comment]
I'll try with master tomorrow.

**Comment by thomthom** [comment]
Using the master branch build worked! On both my test and our API.

Notice some subtle tweaks and adjustments to the template - I like it. Added bonus. :)
