### ISSUE TITLE
Methods ending in question mark ? cannot be found. Again.

### ISSUE THREAD

**Issue by esaborit4code** [lsegal/yard#922]
I'm afraid issue #54 is happening again (yes, that's from 6 years ago, sorry).

See this example in RubyDoc.info: [http://www.rubydoc.info/github/jnicklas/capybara/master/Capybara/RackTest/Node:visible?](http://www.rubydoc.info/github/jnicklas/capybara/master/Capybara/RackTest/Node:visible?)

I've manually replaced the question mark by `%3F` and it works, so I guess it must be an URL escaping problem.

**Comment by lsegal** [comment]
Can you explain how you got this link?

**Comment by esaborit4code** [comment]
Of course.

I went to http://www.rubydoc.info/github/jnicklas/capybara, typed `visible` in the upper-right search box and clicked on the second result.

I hope this helps. And thanks for your quick reply.

**Comment by lsegal** [comment]
Thanks I was able to reproduce this.

**Comment by lsegal** [comment]
This fix was just deployed to rubydoc.info. Sorry for the delay, but it should now work.
