### ISSUE TITLE
--fail-on-warning option for yard doc

### ISSUE THREAD

**Issue by bertBruynooghe** [lsegal/yard#935]
As to facilitate notifications from CI when somebody messes up documentation, it would be nice to have a ```fail-on-warning``` option that makes yard doc exit with error level <> 0 if an warning passed along.

**Comment by lsegal** [comment]
I would accept a PR for this if someone wanted to put one together.

**Comment by jbodah** [comment]
+1 for this feature, might take a stab if I get time

**Comment by lsegal** [comment]
Closing. Will accept as PR (see [CONTRIBUTING.md](https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md) for why this was closed).
