### ISSUE TITLE
`yardoc --verbose` shows less information than `yardoc`

### ISSUE THREAD

**Issue by paddor** [lsegal/yard#936]
If I run `yardoc --verbose`, no progress is shown. But it's shown with `yardoc`.

**Comment by lsegal** [comment]
Inline progress is not shown when verbose or debug modes are enabled. These modes are meant for debugging, and, typically, piping to external streams for logs, so progress data is disabled to ensure that the ANSI/progress data doesn't flood the log. Incidentally, verbose mode only adds backtrace information on errors, as far as I recall, so it's not typically something you would use unless debugging an error, at which point `--debug` is often more useful anyway.

**Comment by paddor** [comment]
So it's a feature, not a bug? ;-) Thanks for the response. :)
