### ISSUE TITLE
Preferred syntax for @param

### ISSUE THREAD

**Issue by hakanensari** [lsegal/yard#937]
It seems there are two competing versions in the wild, and I was wondering if one should be preferred over the other.

Yard's own docs describe:

```ruby
@param name [Types] description
```

The source code itself seems to lean towards:

```ruby
@param [Types] name description
```

Anecdotally, latter feels more common.

What's the "right" way? Should one even worry about this?

**Comment by lsegal** [comment]
Either syntax is supported and "correct". The former are part of the new official recommendation, the latter being more legacy (and therefore more widespread), but it's not going away. You can decide which one you like more.

**Comment by lsegal** [comment]
Marking this as closed since the question is (hopefully) answered. Feel free to comment or reopen if you think there is something else to discuss.
