### ISSUE TITLE
Macros in Markdown documents?

### ISSUE THREAD

**Issue by gavinlaking** [lsegal/yard#938]
Hi,

I'm not sure "Issues" is the best place for this, but don't wish to bombard you @lsegal with an email or tweet. I've had a look through the documentation, but I can't find something relating to my problem (I'm sure it's possible and I'm going to feel like a berk!).

I'm wanting to use some macros in my markdown documentation. I have various methods throughout my project where I want to have both a single file which contains all the relevant information, and then `{include:file:docs/path/path/method_name.md}`. I'd like the `method_name.md` to support `@param` and `@return` etc. Is this possible?

I'd also like to use the `@macro` functionality, but not sure where to put the actual expanded macros or how to ask Yard to include/use them.

If I've missed it, my apologies. If you have an example of how this works (that's not documented, in another project, a link will be awesome; I'll work it out from there!)

Thanks very much for your time, and great work. I love Yard! :-D

Gav

**Comment by lsegal** [comment]
Hi Gav,

YARD does not support macros within "extra files" (i.e., a Markdown document). Macros are only expanded in the context of a code object. In addition, `{include:...}` syntax is not resolved during parsing (no markup besides `@tags` are), so you could not use an include call to bring in macros from another file. This is in fact a limitation of YARD, and probably not something that could change via PR / feature request.

Hope that clarifies!

**Comment by gavinlaking** [comment]
Thanks very much for your rapid response, I'm going to have to get creative! (This won't hurt...) :-D
