### ISSUE TITLE
Not generating documentation where alias is used

### ISSUE THREAD

**Issue by kashishm** [lsegal/yard#941]
For the following code it is not generating documentation
```
# @api public
module Kernel
  class << self
    private
    # @!macro [attach] self.hook
    #   @method $1(&block)
    #   @api public
    #   @param block [block] this block is called while executing the $1 hook
    #   @example
    #      $1 do
    #         puts "I am the $1 hook"
    #      end
    def hook(hook)
      define_method hook do |options={}, &block|
      end
    end

    alias tagged_hook hook
  end

  # generating hook
  hook 'generated_hook'

end
```
If I remove the alias it generates documentation for hook method.

**Comment by kashishm** [comment]
```
# @api public
module Kernel
  class << self
    private
    # @!macro [attach] self.hook
    #   @method $1(&block)
    #   @api public
    #   @param block [block] this block is called while executing the $1 hook
    #   @example
    #      $1 do
    #         puts "I am the $1 hook"
    #      end
    def hook(hook)
      define_method hook do |options={}, &block|
      end
    end

    # @!macro [attach] self.tageed_hook
    #   @method $1(&block)
    #   @api public
    #   @param block [block] this block is called while executing the $1 hook
    #   @example
    #      $1 do
    #         puts "I am the $1 tagged hook"
    #      end
    alias tagged_hook hook
  end

  # generating hook
  hook 'generated_hook'
  tagged_hook 'generated_tagged_hook'

end
```
My actual use case is to have different documentation for actual and alias method i.e generated_hook and generated_tagged_hook.

**Comment by lsegal** [comment]
@kashishm there is an issue with macros when attached to an aliased method, but fixing the reported bug will not enable your use case to work. Aliases are not considered separate methods and are never displayed separately. If you have separate documentation for the aliased method, you effectively have a different contract for it, and therefore it is not truly an alias-- not semantically, anyway.

The easy workaround here, which avoids the reported bug *and* allows the intended use case to work, would be to create two separate methods that have separate docstrings. If you need to keep code DRY, their implementations can call to a shared private method:

```ruby
class << Foo
  # @!macro [attach] self.hook
  # ...
  def hook(*args, &block)
    add_hook(*args, &block)
  end

  # @!macro [attach] self.tagged_hook
  # ...
  def tagged_hook(*args, &block)
    add_hook(*args, &block)
  end

  private

  def add_hook(*args, &block)
    define_method ...
  end
end
```

**Comment by kashishm** [comment]
I agree with you on creating two separate methods. Thanks for the suggestion.

**Comment by lsegal** [comment]
Aliases of DSL declarations can now be used to capture macro behavior, but note that the aliases cannot have their own macro declarations. The latter behavior is not yet supported.
