### ISSUE TITLE
Create a yard documentation server from github

### ISSUE THREAD

**Issue by dasbiswajit** [lsegal/yard#944]
Hi Team,
I am very new to usage of Yard. Actually I am trying to setup a yard server which will generate automatically documentation from Github projects and specific branch on push event? Any ideas?

**Comment by lsegal** [comment]
@dasbiswajit you are probably looking to run the rubydoc.info server locally: http://github.com/docmeta/rubydoc.info -- which handles pulling code from GitHub.

**Comment by lsegal** [comment]
Closing this since the above suggestion should answer this question.
