### ISSUE TITLE
Three-level nested lists

### ISSUE THREAD

**Issue by dasch** [lsegal/yard#945]
In the table of contents on http://www.rubydoc.info/github/zendesk/ruby-kafka/master I have three list levels, which show up correctly on [GitHub](https://github.com/zendesk/ruby-kafka) – but the list is flattened to two levels when rendered with YARD.

**Comment by lsegal** [comment]
YARD doesn't actually convert Markdown into HTML; this is delegated to the markdown library being used. It looks like you are using redcarpet as your markdown provider. My guess is that redcarpet does not handle nested lists. You can give this a test (I think redcarpet ships with a separate rendering executable). If so, the solution would be to try another markdown library (rdiscount, etc.).

**Comment by dasch** [comment]
Thanks, I'll give that a try!

**Comment by lsegal** [comment]
I'm closing this as working-as-intended since YARD does not manage markup. Hopefully trying out another markup library worked for you! I have seen deeply nested lists work in other codebases before, so I know it's possible.
