### ISSUE TITLE
Yard fails with Rake 11

### ISSUE THREAD

**Issue by dgolombek** [lsegal/yard#947]
Rake 11.0.1 removed the last_comment method (https://github.com/ruby/rake/blob/ed197e56cc626725f02431d909e02e048244488e/lib/rake/task_manager.rb#L8), which Yard requires. Failure looks like:

`2016-03-09 11:39:40 NoMethodError: undefined method `last_comment' for #<Rake::Application:0x000000015478a0>`

**Comment by lsegal** [comment]
This is due to a breaking change in Rake, see #946.

**Comment by lsegal** [comment]
The workaround right now is to lock your Gemfile to Rake 10.x.

**Comment by dgolombek** [comment]
Oops, didn't see that, was about to submit the same pull request.

**Comment by lsegal** [comment]
Fixed by #946
