### ISSUE TITLE
Reference overload tags?

### ISSUE THREAD

**Issue by thomthom** [lsegal/yard#952]
Is there a way to reference tags with replacement for some of the data?

I have some methods with a set of similar overloads. If I reference the `@overload` tag then the method name will be misleading.

```
# @overload foo(number)
#   @param [Integer] number
# @overload foo(string, number)
#   @param [Integer] number
def foo; end

# @overload (see #foo)
def bar; end
```

The result is that the param docs for `bar` reference `foo`. Is there anything in YARD I can use to reference another overload set but also update the method name?

**Comment by MSP-Greg** [comment]
Can you use macros?

```
class YardTagExamples
  # @!macro [new] ol1
  #   @overload $0(key, value)
  #     Sets a value on key
  #     @param key [Symbol] describe key param
  #     @param value [Object] describe value param
  #   @overload $0(value)
  #     Sets a value on the default key +:foo+
  #     @param value [Object] describe value param
  #

  # olTest1 doc string info
  # @!macro ol1
  def olTest1(*args)
  end
  
  # olTest2 doc string info
  # @!macro ol1
  def olTest2(*args)
  end
end
```

**Comment by thomthom** [comment]
Hm... I've overlooked macros. Need to look at how they work. I don't quite see that `$0` comes from there, but I need to read up on the docs.

**Comment by MSP-Greg** [comment]
See 'Macro Expansion Variables' at
[T24YARD Tags Macro](http://msp-greg.github.io/YARD/file.Tags.html#macro)

I've started a file that I use for tag testing, I'll probably add it to the T24YARD files.

**Comment by lsegal** [comment]
I'm going to mark this as closed since macros are the right solution here. Let me know if it didn't end up solving your specific issue.
