### ISSUE TITLE
index.html not generated

### ISSUE THREAD

**Issue by thomthom** [lsegal/yard#955]
I got a project where YARD isn't producing an `index.html` file anymore. I only see a `_index.html`.

When I try to reproduce on a separate test the `index.html` is there.

I tried to clean out the `.yardoc` and `doc` folder, but no avail. I can't see any reason for it to be missing either. I see no errors when generating the docs that would indicate something is amiss.

Anyone experienced this?

**Comment by MSP-Greg** [comment]
I think (but I'm not totally sure) --

If there is no README file in the start folder, and if there is no -r, --readme, or --main declaration in the the .yardopts file,

* YARD DOC will not generate an index.html file, the root will be empty (404)
* YARD SERVER will use the 'index' file as the root.

HTH,

Greg

**Comment by lsegal** [comment]
YARD should still generate an index in this case which should be a direct copy of `_index.html`. If that's not happening, it's a bug.

**Comment by thomthom** [comment]
There this one project that stopped creating index.html. I still haven't been able to isolate it. Trying to figure out a way to hook up a ruby debugger to the YARD cli so I can step through the code. Though I've yet to figure out how.

**Comment by MSP-Greg** [comment]
Might have found it.  Obviously, only applies when no README or  -r, --readme, or --main options.

*An index is generated (from _index) iff you have no 'additional doc files' [- extra_files] listed in .yardopts
*An index is not generated if there are 'additional doc files'

I believe the following change fixes it.
```
line 32 of templates/default/fulldoc/html/setup.rb
#  serialize_index(options) if object == '_index.html' && options.files.empty?
  serialize_index(options) if object == '_index.html' && options.readme.nil?
```

**Comment by lsegal** [comment]
That is indeed the fix. Thanks!

**Comment by MSP-Greg** [comment]
No, thank you (for YARD).

Question - what are the 'guide' templates for?

**Comment by lsegal** [comment]
The guide templates generate guide-style documentation from your extra-files. The best example that I know of is [this](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-intro.html) (though it's not Ruby).

**Comment by MSP-Greg** [comment]
Thanks, I kind of suspected as much, as I've never needed to touch them with 'code' libraries.

I've been having some 'fun' getting the (your?) AWS SDK plugins (Ruby & JS) to work with my template system.

Would the following code need a change also?
```
starting at line 55 of templates/guide/fulldoc/html/setup.rb

  if file == options.readme
    serialize_index(options)
  else
    serialize_index(options) if !options.readme && index == 0
    Templates::Engine.with_serializer(outfile, options.serializer) do
      T('layout').run(options)
    end
  end
```

**Comment by lsegal** [comment]
The guide template seems to crash without a README. I guess it's never come up! Good catch there, @MSP-Greg.

**Comment by thomthom** [comment]
@MSP-Greg - thank you very much for digging into this! I think you nailed my configuration exactly! (You must be physic :D) I'll try this as soon as I get into office tomorrow.

Are you making a PR for this?

**Comment by MSP-Greg** [comment]
@lsegal,

Not surprising (that it's never come up).  How would I get YARD to use those templates?  A project with extra files and no code files?  Thinking of testing.

I can dig around the AWS Rake files...

**Comment by lsegal** [comment]
@MSP-Greg all you need is `-t guide`.

**Comment by MSP-Greg** [comment]
@lsegal,

Thanks.  I'll take a look.  Until I've got a setup to test it, can you do the pr for the guide template?

I've switched back and forth between regular YARD and my template enough this weekend...

**Comment by lsegal** [comment]
Sounds good. I'll update the guide template if you want to throw together the fix for this issue.

**Comment by lsegal** [comment]
Thanks @MSP-Greg! Turns out the guide code was generating the index correctly, it was just an unrelated no-README-issue.
