### ISSUE TITLE
Return Type Defaults to Object when attr_* Methods are Used

### ISSUE THREAD

**Issue by manchunlam** [lsegal/yard#959]
Using the `@!attribute` directive, the type can be defined within `[]`

```
class Task < ActiveRecord::Base
  # @!attribute [r] name
  #   @return [String] The name of the task.
end
```

This works perfectly, with the generated document showing

```
#name ⇒ String (readonly)
```

Unfortunately, by adding a `attr_*` method to the class,  the generated doc shows `Object` as the return type.

This code

```
class Task < ActiveRecord::Base
  # @!attribute [r] name
  #   @return [String] The name of the task.

  attr_reader :name
end
```

generates this document

```
#name ⇒ Object (readonly)
```

Could you please take a look? Thanks.

**Comment by lsegal** [comment]
You should not be using `@!attribute` on the `attr_reader` DSL, you should document it normally because YARD already understands `attr_reader`:

```ruby
# @return [String] the name of the task
attr_reader :name
```

**Comment by manchunlam** [comment]
Thank you.

Does that mean I should separate my variables into multiple lines of `attr_reader`?

```
# @return [String] the name of the task
attr_reader :name

# @return [CustomClass] lorem ipsum
attr_reader :foo
```

Otherwise, how does the `@return` statement tell which variable they are
referring to?

```
# @return [String] the name of the task
# @return [CustomClass] lorem ipsum
attr_reader :name, :foo
```

**Comment by lsegal** [comment]
Yes, for documentability you should have separate declarations for each attribute.

**Comment by manchunlam** [comment]
Thanks.
