### ISSUE TITLE
Improved documentation for standard Ruby accessors

### ISSUE THREAD

**Issue by chronodm** [lsegal/yard#963]
It would be nice if at least one of (1) the [Getting Started guide](http://www.rubydoc.info/gems/yard/file/docs/GettingStarted.md), (2) the deprecated `@attr_xxx` [tag docs](http://www.rubydoc.info/gems/yard/file/docs/Tags.md#attr_reader), or (3) the `@!attribute` [directive docs](http://www.rubydoc.info/gems/yard/file/docs/Tags.md#attribute) gave clear examples of documenting `attr_reader/writer/accessor`. It's easy enough to guess that `attr_reader` takes the same form as a method that returns a value:

```ruby
# The thing, if any
# @return [Thing, nil] the thing, or nil if not present
attr_reader :thing
```

However, the writeable form is less obvious, and in fact I still haven't figured it out.

The obvious --

```ruby
# The thing, if any
# @param [Thing, String, nil] the thing; if passed as a string, 
#   will be parsed with {Thing#from_str}
# @return [Thing, nil] the thing, or nil if not present
attr_accessor :thing
```

-- interprets the word `the` as the parameter name, producing the warning **@param tag has unknown parameter name: the**, and the following documentation:

> Parameters:
> - the `(Thing, String, nil)` — thing; if passed as a string, will be parsed with Thing#from_str

Adding a dummy parameter name, `value`, thus:

```ruby
# The thing, if any
# @param value [Thing, String, nil] the thing; if passed as a string, 
#   will be parsed with {Thing#from_str}
# @return [Thing, nil] the thing, or nil if not present
attr_accessor :thing
```

-- produces more or less the correct documentation, so it's what I'm using pro tem, but since it still produces an **unknown parameter name** warning I'm guessing it's not really correct either.

I assume I'm not the only person confused by this or there wouldn't be issues like #768 and #787.

**Comment by lsegal** [comment]
> -- interprets the word the as the parameter name, producing the warning @param tag has unknown parameter name: the, and the following documentation:

The `@param` tag always takes an argument name as the first parameter.

> Adding a dummy parameter name, value, thus: ... but since it still produces an unknown parameter name warning I'm guessing it's not really correct either.

You're adding the `@param` tag to both the reader and the writer, there. The warning isn't coming from the writer, but the reader, which will have a parameter tag with no parameters, and is invalid.

The real way to do this is with overloads:

```ruby
# @overload thing
#   @return [Thing, nil] the thing
# @overload thing=(value)
#   @param value [Thing, String, nil] ...
attr_accessor :thing
```

Adding this to the getting started guide wouldn't be a bad idea. This has been answered in a number of places indeed.

**Comment by lsegal** [comment]
Documenting attributes is now part of the updated documentation in v0.9.0. Marking this as closed. If you want to make updates to the existing documentation I'd look at other PRs.
