### ISSUE TITLE
Rake's last_comment method

### ISSUE THREAD

**Issue by dominicsayers** [lsegal/yard#964]
The rake method `last_comment` is deprecated. You use it here: https://github.com/lsegal/yard/blob/v0.8.7.6/lib/yard/rake/yardoc_task.rb#L69

The method will be removed in rake 12 and was briefly removed in rake 11.0 although they restored it in rake 11.1 after it caused knock-on problems in other projects.

It's a simple fix to change this method to the supported `last_description`. I will submit a PR if I get time but this is not looking likely for the moment.

(This caused a problem for my project because another project that uses Yard for documentation introduced a dependency on rake < 11.0 as a consequence of a test failure in Yard during the dark days of rake 11.0)

**Comment by lsegal** [comment]
This has already been addressed in #946.

**Comment by dominicsayers** [comment]
Cool. I did search Issues for `rake` before I posted but nothing came up. Thanks for addressing this.

**Comment by karmi** [comment]
Thanks, @lsegal! I guess it will be included in the next release?

**Comment by dominicsayers** [comment]
@karmi It has been a long time since the last release (Oct 2014). I noticed @lsegal's comment here https://github.com/lsegal/yard/issues/850 so it may be some time before it's officially released.

**Comment by weppos** [comment]
@lsegal any chance to have at least a patch release released to address this issue?
