### ISSUE TITLE
Templates::Helpers::HtmlHelper#signature (CodeObject or Tag)

### ISSUE THREAD

**Issue by MSP-Greg** [lsegal/yard#968]
Loren,

Good day.  I've been working to get yard-t2 to parse Ruby core and std-lib.  Noticed an issue with a method signature, and began tracking it down.  Of course, I started from the wrong end...

Issue is with 
`Templates::Helpers::HtmlHelper#signature`
which is called with the first parameter as either a CodeObject or an overload tag by
`templates/default/method_details/html/method_signature.erb`

I have never noticed a problem with 'normal' Ruby, but with c code (and maybe some DSL code) it causes issues.  You doc'd the method as only having CodeObject for the parameter.

Any thoughts or pointers?  I believe the current code can change the meth pointer from the CodeObject to it's first overload tag.  Since Tags and CodeObjects share a lot of attributes, it probably wasn't noticed before...

I'll get a fix going, probably need to have a reference to both the ov (overload tag) and the co (CodeObject).  Probably use those for variable names, unless you'd prefer something else...

Greg

**Comment by MSP-Greg** [comment]
I think it's a problem with parsing overload parameters with some call-seq declarations.

**Comment by lsegal** [comment]
YARD doesn't parse call-seq declarations, since those are defined using RDoc syntax. YARD only parses tags. You would have to convert the call-seq syntax to YARD's tag syntax (using `@overload`).

**Comment by lsegal** [comment]
Closing this because YARD does not support call-seq syntax.
