### ISSUE TITLE
Safe navigation operator (&.) is treated as a syntax error

### ISSUE THREAD

**Issue by 907th** [lsegal/yard#973]
YARD says:
> [warn]: Syntax error in `app/controllers/xxx_controller.rb`:(78,30): syntax error, unexpected '.'

where line 78 contains: `amount   = p[:amount] &. to_d`

**Comment by lsegal** [comment]
What Ruby version are you using? This is likely a Ripper bug that should be reported against Ruby. YARD doesn't raise syntax errors, it just passes them through from Ripper.

**Comment by 907th** [comment]
Using yard 0.8.7.6

**Comment by lsegal** [comment]
Ruby version, not YARD.

**Comment by 907th** [comment]
Oh, I'm sorry! That is my bug! I'm using old Ruby on the server. Thank you
