### ISSUE TITLE
Link return type to external URL in @return tag?

### ISSUE THREAD

**Issue by mrdziuban** [lsegal/yard#975]
I'm wondering if there's a way to link the return type of a method to an external URL in the `@return` tag? For example, I'd like to be able to do something like this:

```ruby
# Returns an external resource
# @return [{http://example.com ExternalResource}]
def my_method
  # ...
end
```

Is there any way to accomplish this? Thanks!

**Comment by lsegal** [comment]
This is not supported by YARD core. Types are freeform strings but expected to be the typename (plus optional modifiers) only. There are no plans to support YARD's special `{}` syntax in type specifiers.

You can write a plugin to detect and link special names by overriding [YARD::Templates::Helpers::HtmlHelper#format_types](https://github.com/lsegal/yard/blob/master/lib/yard/templates/helpers/html_helper.rb#L425-L433), or by writing JavaScript to parse tags and replace that class with a link.

**Comment by mrdziuban** [comment]
Thanks @lsegal! I got it working by overriding `format_types`.
