### ISSUE TITLE
Extra files meta data vs Markdown syntax

### ISSUE THREAD

**Issue by tf** [lsegal/yard#976]
Meta data for extra files has to be placed at the top of the file at the moment. Since each line has to be prefixed with a `#` those lines are displayed as ugly headers when viewing Markdown files on Github. I really like Yard's extra files functionality for guides, but would also like to ensure correct display for users viewing those guides on Github.

Would you consider merging a PR that allows to wrap the meta data section in HTML comments like this:

```
<!--
# @title Something
-->
# Headline 1
```

That would prevent meta data from being printed on GitHub. 

As an alternative - since markdown seems to be the default markup anyway - the first Markdown header could be used as the title by default. That would probably have to be guarded by a `.yardopts` option to prevent a breaking change and would not solve the issue for other meta data tags.

Do you see a better solution? Or do you even see this as a non issue in the first place?

Thanks
Tim

**Comment by lsegal** [comment]
Markdown is not the default markup in YARD, but I don't see a big problem with a PR that would skip past an open comment tag assuming the very next line contained metadata.

**Comment by tf** [comment]
Great. See #977.
