### ISSUE TITLE
What is the correct order for @param tag?

### ISSUE THREAD

**Issue by jcoyne** [lsegal/yard#980]
In the documentation published here:
http://www.rubydoc.info/gems/yard/file/docs/Tags.md#param

it indicates that name comes before `[Types]`

```
@param name [Types] description 
```

But [elsewhere in the same document](http://www.rubydoc.info/gems/yard/file/docs/Tags.md#option) it uses examples like:
```
# @param [Hash] opts the options to create a message with.
```

Is one the correct way, or are both correct?

**Comment by lsegal** [comment]
Both are correct. This is documented but the question comes up a bit so I've updated the docs to be more consistent / clear.
