### ISSUE TITLE
yard server -g does not serve static files

### ISSUE THREAD

**Issue by codeforkjeff** [lsegal/yard#990]
In 0.9.1 and 0.9.2, "yard server -g" does not serve static files. You can see 404 errors for the .css and .js files.

The HTML references "/css/style.css" instead of "/static/css/style.css" so the router doesn't route it correctly. Also, YARD::Server::Commands::StaticFileCommand is a LibraryCommand, but with the gem listing page, there is no selected library yet.

"yard server" works just fine.

## Steps to reproduce

Run "yard server -g"
Local "http://localhost:8808/" in the browser

## Actual Output

A list of installed gems is shown in the browser, but the html style is incorrect.
Clicking on a gem takes you to a "Processing [gem]" page with a broken image link, and nothing happens because the jquery.js file never loaded.

## Expected Output

A working HTML page.

## Environment details:

* OS: Xubuntu 16.04
* Ruby version (`ruby -v`): 2.3.1 (also happens on 2.2.5)
* YARD version (`yard -v`): 0.9.2
* Relevant software dependency/versions: none

I have read the [Contributing Guide](contrib).

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by lsegal** [comment]
Fixed and tagged! Thanks for reporting this.

**Comment by codeforkjeff** [comment]
Thanks for the rapid fix!
