### ISSUE TITLE
YARD vs Memoist

### ISSUE THREAD

**Issue by zverok** [lsegal/yard#994]
Modern Ruby returns method name symbol for `def method_name` statement.

Several metaprogramming techniques can benefit from that. For example, on our project, we use [memoist](https://github.com/matthewrudy/memoist), and instead of verbose code:
```ruby
class A
  extend Memoist

  def m
  end
  memoize :m
end
```
we use more DRY (and readable):
```ruby
class A
  extend Memoist

  memoize def m
  end
end
```

I believe this is widely used technique currently, yet YARD does not "see" those methods: if you'll try to generate documentation for such code, the output will be
```
Files:           1
Modules:         0 (    0 undocumented)
Classes:         1 (    1 undocumented)
Constants:       0 (    0 undocumented)
Methods:         0 (    0 undocumented)
```
Note the "Methods: 0" part.

I'm not sure if a change of this behavior should be considered a "bug" or rather "feature request", though.

**Comment by lsegal** [comment]
There are no plans to support arbitrary decorators, but YARD is pluggable for this reason. You can [write your own handler](http://yardoc.org/guides/extending-yard/writing-handlers.html) to deal with `memoize` calls, or any other form. Here's what the handler looks like for [Ruby's public/protected/private methods](https://github.com/lsegal/yard/blob/master/lib/yard/handlers/ruby/visibility_handler.rb#L16-L18) (the [#process_decorator](http://www.rubydoc.info/gems/yard/YARD/Handlers/Ruby/DecoratorHandlerMethods#process_decorator-instance_method) portion is the call that hooks everything up).

**Comment by zverok** [comment]
Thanks @lsegal! YARD's flexibility is fascinating :)

**Comment by lsegal** [comment]
No problem! Marking this as closed, but feel free to jump back here if you have trouble getting a custom handler working.
