### ISSUE TITLE
lib\yard\handlers\ruby\constant_handler.rb - parsing constants like NS1::NS2::Cnst

### ISSUE THREAD

**Issue by MSP-Greg** [lsegal/yard#995]
I hate to post this after the commit you just did, but I was checking some things, and noticed that in the following code, `A::AA::Cnst` won't be picked up by YARD.

I believe in this situation statement[0][0] has a 'child' for each 'namespace section' of the full constant, ie statement[0][0][0] is `A`, statement[0][0][1] is `AA`, and statement[0][1] is `Cnst`.  You probably already knew that, because I really haven't needed to go thru the Ruby parser...

```ruby
module A
  class AA
  end
end
A::AA::Cnst = 'Cnst Created'
```

**Comment by lsegal** [comment]
Fortunately this seems unrelated to the previous issues. I can reproduce this in 0.8.7.6.

**Comment by lsegal** [comment]
Thanks for reporting!

**Comment by lsegal** [comment]
FWIW, that old implementation (and the lack of support for compound const assignment) dates back to yard 0.4.x.

**Comment by MSP-Greg** [comment]
You're welcome, but you did a lot more work than I did.  Hence, thank you.

To some degree, we all have our own coding style, but working on Ruby Core & Std-Lib has brought into focus all of the different 'styles' of coding.  And how sloppy people are when writing comments...
