### ISSUE TITLE
iOS Issues

### ISSUE THREAD

**Issue by MSP-Greg** [lsegal/yard#996]
I made three css changes to help with iOS rendering.  One fixes the 'search' box wrapping, which may happen in other browser/OS combinations, and the other two effect scrolling.

See  https://msp-greg.github.io/yard-no-t2/ (not linked to from home site home page)

Let me know if you'd like the updates.

Note 1 - GitHub.io will not load a file named _index.html, so you can't go to the index (I made allowances for that in yard-t2 by adding a js host test and creating a copy of the file named y_index.html.)

Note 2 - I used my default .yardopts for YARD, so private & protected are visible, and I've also added the following, which I won't commit (only changes output when private is visible, changes the Class List tree)
```ruby
# lib/yard/server/rack_adapter.rb
# @!parse module Rack ; end ; private_constant :Rack

# lib/yard/server/webrick_adapter.rb
# @!parse module WEBrick ; end ; private_constant :WEBrick
```

**Comment by MSP-Greg** [comment]
I just updated it, nav list now scrolls in both desktop & iOS and is limited to window height.  Haven't tried with server yet.  I did have to move one item in a template.  Does the iOS scroll thing on both the list and main doc.

**Comment by lsegal** [comment]
I'd consider any change that fixed broken rendering on modern browsers, but it's hard to know if this specific change can be accepted without code. I'm closing this in favor of a PR-- please open one if you want the change to be considered.

**Comment by MSP-Greg** [comment]
Since these changes can't be tested within Ruby, I included the link so you could have a (quick) look at it and see if you found it worth changing.  UI/UX can be a very personal thing...

I'll prepare a PR

**Comment by MSP-Greg** [comment]
Two questions --

1. On a narrow screen (with the nav floated on the right), do you want the nav anchored to the page or the window (as is current shown in the demo)?  If to the window, do want the open/close control anchored to the window (it currently anchors to the page)?

2. Would you prefer the nav to resize for lists that are shorter in height than the main window (for instance, the YARD 'Files List').  I can also do that, but I'll have to wrap the iframe#search_frame element in a div.
